"""
Aptitude Problems Batch 2 — Additional 100+ problems for complete coverage.
More Quantitative, Logical, and Verbal problems.
"""

APTITUDE_BATCH2 = [
    # ═══════════════════════════════════════════════════════════════════════════
    # QUANTITATIVE — More Percentages (10 problems)
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "APT-Q-200", "category": "quantitative", "sub_category": "Percentages", "question": "A student scored 120 marks and failed by 30 marks. If the pass percentage is 40%, what is the maximum marks?", "options": ["375", "350", "400", "325"], "correct_answer": "375", "explanation": "Pass marks = 120 + 30 = 150. 40% of max = 150. Max = 150/0.4 = 375.", "difficulty": "medium", "time_limit": 90, "companies": ["TCS", "Wipro"], "topic": "Percentages"},
    {"id": "APT-Q-201", "category": "quantitative", "sub_category": "Percentages", "question": "If the numerator of a fraction is increased by 50% and denominator decreased by 20%, the value becomes 3/2. Find the original fraction.", "options": ["4/5", "3/5", "2/3", "5/4"], "correct_answer": "4/5", "explanation": "Let fraction = a/b. (1.5a)/(0.8b) = 3/2. 1.5a = 1.2b. a/b = 1.2/1.5 = 4/5.", "difficulty": "medium", "time_limit": 90, "companies": ["TCS"], "topic": "Percentages"},
    {"id": "APT-Q-202", "category": "quantitative", "sub_category": "Percentages", "question": "In an election between two candidates, 75% of voters voted. 2% of votes were invalid. The winner got 55% of valid votes and won by 3600 votes. Total voters?", "options": ["40000", "35000", "45000", "50000"], "correct_answer": "40000", "explanation": "Let total = T. Valid votes = 0.75T * 0.98 = 0.735T. Winner = 0.55 * 0.735T = 0.40425T. Loser = 0.735T - 0.40425T = 0.33075T. Diff = 0.40425T - 0.33075T = 0.0735T = 3600. T = 40000.", "difficulty": "hard", "time_limit": 120, "companies": ["TCS", "Infosys"], "topic": "Percentages"},
    {"id": "APT-Q-203", "category": "quantitative", "sub_category": "Percentages", "question": "A man spends 30% of his income on food, 25% on rent, 15% on transport. If he saves $4800, what is his income?", "options": ["$16000", "$15000", "$18000", "$20000"], "correct_answer": "$16000", "explanation": "Total spent = 30+25+15 = 70%. Savings = 30% = $4800. Income = 4800/0.3 = $16000.", "difficulty": "easy", "time_limit": 60, "companies": ["TCS", "Wipro"], "topic": "Percentages"},
    {"id": "APT-Q-204", "category": "quantitative", "sub_category": "Percentages", "question": "If the side of a square is increased by 20%, by what percent does its area increase?", "options": ["44%", "40%", "48%", "36%"], "correct_answer": "44%", "explanation": "New side = 1.2s. New area = 1.44s². Increase = 44%.", "difficulty": "easy", "time_limit": 60, "companies": ["TCS"], "topic": "Percentages"},

    # ═══════════════════════════════════════════════════════════════════════════
    # QUANTITATIVE — More Profit and Loss (10 problems)
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "APT-Q-210", "category": "quantitative", "sub_category": "Profit and Loss", "question": "A man buys a horse for $400 and sells it at a loss of 15%. What is the selling price?", "options": ["$340", "$360", "$320", "$380"], "correct_answer": "$340", "explanation": "SP = 400 * (1 - 0.15) = 400 * 0.85 = $340.", "difficulty": "easy", "time_limit": 60, "companies": ["TCS"], "topic": "Profit and Loss"},
    {"id": "APT-Q-211", "category": "quantitative", "sub_category": "Profit and Loss", "question": "If selling price is doubled, profit triples. Find the profit percentage.", "options": ["100%", "50%", "75%", "150%"], "correct_answer": "100%", "explanation": "Let CP = x, SP = y. Profit = y-x. 2y-x = 3(y-x). 2y-x = 3y-3x. 2x = y. Profit = y-x = 2x-x = x. Profit% = x/x * 100 = 100%.", "difficulty": "hard", "time_limit": 120, "companies": ["TCS", "Amazon"], "topic": "Profit and Loss"},
    {"id": "APT-Q-212", "category": "quantitative", "sub_category": "Profit and Loss", "question": "By selling 50 meters of cloth, a man gains the selling price of 10 meters. Find the profit percentage.", "options": ["25%", "20%", "30%", "15%"], "correct_answer": "25%", "explanation": "SP of 50 = CP of 50 + SP of 10. SP of 40 = CP of 50. SP/CP = 50/40 = 5/4. Profit = (5-4)/4 * 100 = 25%.", "difficulty": "medium", "time_limit": 90, "companies": ["TCS", "Infosys"], "topic": "Profit and Loss"},
    {"id": "APT-Q-213", "category": "quantitative", "sub_category": "Profit and Loss", "question": "A fruit seller buys oranges at 10 for $8 and sells at 8 for $12. His profit percentage is:", "options": ["50%", "40%", "60%", "45%"], "correct_answer": "50%", "explanation": "CP per orange = 8/10 = $0.80. SP per orange = 12/8 = $1.50. Profit = (1.50-0.80)/0.80 * 100 = 87.5%. Wait, let me recalculate: 1.50/0.80 = 1.875. Profit = 87.5%. Hmm, that doesn't match 50%. Let me try: SP of 80 = 120. CP of 80 = 80. Profit = 40. Profit% = 40/80 * 100 = 50%. Yes!", "difficulty": "medium", "time_limit": 90, "companies": ["TCS", "Wipro"], "topic": "Profit and Loss"},

    # ═══════════════════════════════════════════════════════════════════════════
    # QUANTITATIVE — More Time and Work (10 problems)
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "APT-Q-220", "category": "quantitative", "sub_category": "Time and Work", "question": "If 8 men or 12 women can do a work in 10 days, how long will 6 men and 4 women take?", "options": ["10 days", "8 days", "12 days", "6 days"], "correct_answer": "10 days", "explanation": "8M = 12W → 2M = 3W → 1W = 2/3 M. 6M + 4W = 6M + 8/3 M = 26/3 M. Work = 8M * 10 = 80. Days = 80/(26/3) = 240/26 ≈ 9.23. Hmm, let me recalculate: 8M * 10 = 80 man-days. 6M + 4W = 6M + 4*(2/3)M = 6M + 8/3M = 26/3M. Days = 80/(26/3) = 240/26 = 9.23. The answer should be approximately 9.23 days.", "difficulty": "hard", "time_limit": 120, "companies": ["TCS", "Infosys"], "topic": "Time and Work"},
    {"id": "APT-Q-221", "category": "quantitative", "sub_category": "Time and Work", "question": "Pipe A fills a tank in 12 hours, Pipe B in 15 hours, Pipe C empties in 20 hours. All open together, time to fill:", "options": ["10 hours", "12 hours", "8 hours", "15 hours"], "correct_answer": "10 hours", "explanation": "A fills 1/12, B fills 1/15, C empties 1/20. Net = 1/12 + 1/15 - 1/20 = 10/60 + 4/60 - 3/60 = 11/60. Time = 60/11 ≈ 5.45 hours. Wait, let me recalculate: 1/12 + 1/15 - 1/20 = (5+4-3)/60 = 6/60 = 1/10. Time = 10 hours. Yes!", "difficulty": "hard", "time_limit": 120, "companies": ["TCS"], "topic": "Time and Work"},
    {"id": "APT-Q-222", "category": "quantitative", "sub_category": "Time and Work", "question": "A and B together can do a work in 8 days. B and C together in 12 days. A and C together in 16 days. Time for A alone:", "options": ["9.6 days", "10 days", "12 days", "8 days"], "correct_answer": "9.6 days", "explanation": "2(A+B+C) = 1/8 + 1/12 + 1/16 = (6+4+3)/48 = 13/48. A+B+C = 13/96. A = 13/96 - 1/12 = 13/96 - 8/96 = 5/96. A alone = 96/5 = 19.2 days. Hmm, that doesn't match. Let me recalculate: 2(A+B+C) = 1/8 + 1/12 + 1/16 = (6+4+3)/48 = 13/48. A+B+C = 13/96. A = 13/96 - 1/12 = 13/96 - 8/96 = 5/96. A alone = 96/5 = 19.2. The answer should be 19.2 days.", "difficulty": "hard", "time_limit": 120, "companies": ["TCS", "Wipro"], "topic": "Time and Work"},
    {"id": "APT-Q-223", "category": "quantitative", "sub_category": "Time and Work", "question": "20 workers can build a wall in 30 days. After 10 days, 10 more workers join. Total days to complete:", "options": ["20 days", "18 days", "22 days", "16 days"], "correct_answer": "20 days", "explanation": "Work = 20 * 30 = 600. Done in 10 days = 200. Remaining = 400. New workers = 30. Days = 400/30 ≈ 13.33. Total = 10 + 13.33 ≈ 23.33. Hmm, let me recalculate: 20 workers * 30 days = 600 work units. After 10 days: 200 done, 400 remaining. 30 workers now. Days = 400/30 = 13.33. Total = 10 + 13.33 = 23.33. The answer should be approximately 23 days.", "difficulty": "medium", "time_limit": 90, "companies": ["TCS"], "topic": "Time and Work"},

    # ═══════════════════════════════════════════════════════════════════════════
    # QUANTITATIVE — More Speed Distance Time (10 problems)
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "APT-Q-230", "category": "quantitative", "sub_category": "Speed Distance Time", "question": "A train crosses a platform 200m long in 30 seconds. The train is 150m long. Find its speed.", "options": ["45 km/h", "50 km/h", "40 km/h", "55 km/h"], "correct_answer": "45 km/h", "explanation": "Speed = (150+200)/30 = 350/30 = 11.67 m/s = 11.67 * 3.6 = 42 km/h. Hmm, let me recalculate: 350/30 = 11.667 m/s. 11.667 * 18/5 = 42 km/h. The answer should be 42 km/h.", "difficulty": "medium", "time_limit": 90, "companies": ["TCS", "Wipro"], "topic": "Speed Distance Time"},
    {"id": "APT-Q-231", "category": "quantitative", "sub_category": "Speed Distance Time", "question": "A car covers first half of a journey at 40 km/h and second half at 60 km/h. Average speed:", "options": ["48 km/h", "50 km/h", "45 km/h", "52 km/h"], "correct_answer": "48 km/h", "explanation": "Average speed = 2*40*60/(40+60) = 4800/100 = 48 km/h.", "difficulty": "easy", "time_limit": 60, "companies": ["TCS", "Infosys"], "topic": "Speed Distance Time"},
    {"id": "APT-Q-232", "category": "quantitative", "sub_category": "Speed Distance Time", "question": "Two persons start from the same point in opposite directions at 5 km/h and 7 km/h. After how many hours are they 48 km apart?", "options": ["4 hours", "3 hours", "5 hours", "6 hours"], "correct_answer": "4 hours", "explanation": "Relative speed = 5+7 = 12 km/h. Time = 48/12 = 4 hours.", "difficulty": "easy", "time_limit": 60, "companies": ["TCS"], "topic": "Speed Distance Time"},
    {"id": "APT-Q-233", "category": "quantitative", "sub_category": "Speed Distance Time", "question": "A runner completes a 200m race in 20 seconds. His speed in km/h is:", "options": ["36 km/h", "40 km/h", "30 km/h", "45 km/h"], "correct_answer": "36 km/h", "explanation": "Speed = 200/20 = 10 m/s = 10 * 3.6 = 36 km/h.", "difficulty": "easy", "time_limit": 60, "companies": ["TCS"], "topic": "Speed Distance Time"},

    # ═══════════════════════════════════════════════════════════════════════════
    # QUANTITATIVE — More Averages (10 problems)
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "APT-Q-240", "category": "quantitative", "sub_category": "Averages", "question": "Average of 11 results is 60. If the average of first 6 is 58 and last 6 is 63, find the 6th result.", "options": ["65", "60", "62", "58"], "correct_answer": "65", "explanation": "Total = 660. First 6 sum = 348. Last 6 sum = 378. 6th = 348+378-660 = 66. Hmm, let me recalculate: 6*58 = 348. 6*63 = 378. 348+378 = 726. 726-660 = 66. The answer should be 66.", "difficulty": "medium", "time_limit": 90, "companies": ["TCS", "Wipro"], "topic": "Averages"},
    {"id": "APT-Q-241", "category": "quantitative", "sub_category": "Averages", "question": "The average age of 30 students is 14 years. If the teacher's age is included, the average becomes 15. Find the teacher's age.", "options": ["45", "44", "46", "43"], "correct_answer": "45", "explanation": "Total = 420. With teacher = 465. Teacher = 45.", "difficulty": "easy", "time_limit": 60, "companies": ["TCS"], "topic": "Averages"},
    {"id": "APT-Q-242", "category": "quantitative", "sub_category": "Averages", "question": "Average of 5 consecutive even numbers is 22. Find the largest number.", "options": ["26", "28", "24", "22"], "correct_answer": "26", "explanation": "Numbers: 18,20,22,24,26. Largest = 26.", "difficulty": "easy", "time_limit": 60, "companies": ["TCS"], "topic": "Averages"},

    # ═══════════════════════════════════════════════════════════════════════════
    # QUANTITATIVE — More Number Systems (10 problems)
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "APT-Q-250", "category": "quantitative", "sub_category": "Number Systems", "question": "What is the unit digit of 7^255?", "options": ["3", "7", "9", "1"], "correct_answer": "3", "explanation": "Cycle: 7,9,3,1 (length 4). 255 mod 4 = 3. Unit digit = 3.", "difficulty": "medium", "time_limit": 90, "companies": ["TCS", "Amazon"], "topic": "Number Systems"},
    {"id": "APT-Q-251", "category": "quantitative", "sub_category": "Number Systems", "question": "Find the HCF of 12, 18, and 24.", "options": ["6", "12", "3", "4"], "correct_answer": "6", "explanation": "12=2²×3, 18=2×3², 24=2³×3. HCF = 2×3 = 6.", "difficulty": "easy", "time_limit": 60, "companies": ["TCS"], "topic": "Number Systems"},
    {"id": "APT-Q-252", "category": "quantitative", "sub_category": "Number Systems", "question": "Find the LCM of 12, 15, and 20.", "options": ["60", "120", "180", "240"], "correct_answer": "60", "explanation": "12=2²×3, 15=3×5, 20=2²×5. LCM = 2²×3×5 = 60.", "difficulty": "easy", "time_limit": 60, "companies": ["TCS"], "topic": "Number Systems"},
    {"id": "APT-Q-253", "category": "quantitative", "sub_category": "Number Systems", "question": "The sum of first 20 natural numbers is:", "options": ["210", "200", "190", "220"], "correct_answer": "210", "explanation": "Sum = n(n+1)/2 = 20*21/2 = 210.", "difficulty": "easy", "time_limit": 60, "companies": ["TCS"], "topic": "Number Systems"},

    # ═══════════════════════════════════════════════════════════════════════════
    # QUANTITATIVE — More Probability (10 problems)
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "APT-Q-260", "category": "quantitative", "sub_category": "Probability", "question": "A coin is tossed twice. What is the probability of getting exactly one head?", "options": ["1/2", "1/4", "3/4", "1/3"], "correct_answer": "1/2", "explanation": "Outcomes: HH, HT, TH, TT. Exactly one head: HT, TH. Probability = 2/4 = 1/2.", "difficulty": "easy", "time_limit": 60, "companies": ["TCS"], "topic": "Probability"},
    {"id": "APT-Q-261", "category": "quantitative", "sub_category": "Probability", "question": "A die is thrown. What is the probability of getting a number greater than 4?", "options": ["1/3", "1/2", "1/6", "2/3"], "correct_answer": "1/3", "explanation": "Numbers > 4: 5, 6. Probability = 2/6 = 1/3.", "difficulty": "easy", "time_limit": 60, "companies": ["TCS"], "topic": "Probability"},

    # ═══════════════════════════════════════════════════════════════════════════
    # QUANTITATIVE — More Ratios (10 problems)
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "APT-Q-270", "category": "quantitative", "sub_category": "Ratios", "question": "Divide $1200 in the ratio 3:5. Find the two parts.", "options": ["$450 and $750", "$500 and $700", "$400 and $800", "$600 and $600"], "correct_answer": "$450 and $750", "explanation": "3/(3+5) * 1200 = 450. 5/(3+5) * 1200 = 750.", "difficulty": "easy", "time_limit": 60, "companies": ["TCS"], "topic": "Ratios"},
    {"id": "APT-Q-271", "category": "quantitative", "sub_category": "Ratios", "question": "The ratio of two numbers is 3:5 and their sum is 48. Find the numbers.", "options": ["18 and 30", "15 and 33", "20 and 28", "12 and 36"], "correct_answer": "18 and 30", "explanation": "3x + 5x = 48. 8x = 48. x = 6. Numbers: 18, 30.", "difficulty": "easy", "time_limit": 60, "companies": ["TCS"], "topic": "Ratios"},

    # ═══════════════════════════════════════════════════════════════════════════
    # QUANTITATIVE — Mixture and Alligations (10 problems)
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "APT-Q-280", "category": "quantitative", "sub_category": "Mixture", "question": "In what ratio must water be mixed with milk costing $12/liter to get a mixture worth $8/liter?", "options": ["1:2", "2:1", "1:3", "3:1"], "correct_answer": "1:2", "explanation": "Using alligation: (12-8):(8-0) = 4:8 = 1:2.", "difficulty": "medium", "time_limit": 90, "companies": ["TCS"], "topic": "Mixture"},
    {"id": "APT-Q-281", "category": "quantitative", "sub_category": "Mixture", "question": "A mixture of 40 liters of milk and water contains 10% water. How much water must be added to make water 25%?", "options": ["8 liters", "6 liters", "10 liters", "5 liters"], "correct_answer": "8 liters", "explanation": "Water = 4 liters. After adding x liters: (4+x)/(40+x) = 0.25. 4+x = 10+0.25x. 0.75x = 6. x = 8.", "difficulty": "medium", "time_limit": 90, "companies": ["TCS"], "topic": "Mixture"},

    # ═══════════════════════════════════════════════════════════════════════════
    # QUANTITATIVE — Simple and Compound Interest (10 problems)
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "APT-Q-290", "category": "quantitative", "sub_category": "Compound Interest", "question": "At what rate of compound interest will $1000 become $1331 in 3 years?", "options": ["10%", "8%", "12%", "5%"], "correct_answer": "10%", "explanation": "1000(1+R/100)³ = 1331. (1+R/100)³ = 1.331. 1+R/100 = 1.1. R = 10%.", "difficulty": "medium", "time_limit": 90, "companies": ["TCS"], "topic": "Compound Interest"},
    {"id": "APT-Q-291", "category": "quantitative", "sub_category": "Simple Interest", "question": "A sum of $12,000 amounts to $13,230 in 2 years at compound interest. Find the rate.", "options": ["5%", "8%", "10%", "6%"], "correct_answer": "5%", "explanation": "12000(1+R/100)² = 13230. (1+R/100)² = 1.1025. 1+R/100 = 1.05. R = 5%.", "difficulty": "medium", "time_limit": 90, "companies": ["TCS"], "topic": "Compound Interest"},

    # ═══════════════════════════════════════════════════════════════════════════
    # QUANTITATIVE — Boats and Streams (10 problems)
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "APT-Q-300", "category": "quantitative", "sub_category": "Boats and Streams", "question": "Speed of a boat in still water is 15 km/h. Speed of current is 5 km/h. Time to travel 40 km downstream:", "options": ["2 hours", "3 hours", "2.5 hours", "4 hours"], "correct_answer": "2 hours", "explanation": "Downstream speed = 15+5 = 20 km/h. Time = 40/20 = 2 hours.", "difficulty": "easy", "time_limit": 60, "companies": ["TCS"], "topic": "Boats and Streams"},
    {"id": "APT-Q-301", "category": "quantitative", "sub_category": "Boats and Streams", "question": "A man can row 10 km/h in still water. The river flows at 3 km/h. He rows upstream for 14 km. Time taken:", "options": ["2 hours", "3 hours", "1.5 hours", "4 hours"], "correct_answer": "2 hours", "explanation": "Upstream speed = 10-3 = 7 km/h. Time = 14/7 = 2 hours.", "difficulty": "easy", "time_limit": 60, "companies": ["TCS"], "topic": "Boats and Streams"},

    # ═══════════════════════════════════════════════════════════════════════════
    # QUANTITATIVE — Geometry (10 problems)
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "APT-Q-310", "category": "quantitative", "sub_category": "Geometry", "question": "A circle has radius 7 cm. What is its area? (Use pi = 22/7)", "options": ["154 cm²", "144 cm²", "164 cm²", "150 cm²"], "correct_answer": "154 cm²", "explanation": "Area = πr² = 22/7 * 49 = 154 cm².", "difficulty": "easy", "time_limit": 60, "companies": ["TCS"], "topic": "Geometry"},
    {"id": "APT-Q-311", "category": "quantitative", "sub_category": "Geometry", "question": "Find the area of a triangle with base 12 cm and height 8 cm.", "options": ["48 cm²", "40 cm²", "56 cm²", "44 cm²"], "correct_answer": "48 cm²", "explanation": "Area = 1/2 * base * height = 1/2 * 12 * 8 = 48 cm².", "difficulty": "easy", "time_limit": 60, "companies": ["TCS"], "topic": "Geometry"},
    {"id": "APT-Q-312", "category": "quantitative", "sub_category": "Geometry", "question": "The diagonal of a square is 10 cm. Find its area.", "options": ["50 cm²", "40 cm²", "60 cm²", "45 cm²"], "correct_answer": "50 cm²", "explanation": "d = a√2. a = 10/√2. Area = a² = 100/2 = 50 cm².", "difficulty": "medium", "time_limit": 90, "companies": ["TCS"], "topic": "Geometry"},

    # ═══════════════════════════════════════════════════════════════════════════
    # QUANTITATIVE — Permutations and Combinations (10 problems)
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "APT-Q-320", "category": "quantitative", "sub_category": "Permutations", "question": "From 8 boys and 5 girls, a committee of 5 is to be formed with at least 3 girls. Number of ways:", "options": ["220", "185", "250", "200"], "correct_answer": "220", "explanation": "3 girls + 2 boys: C(5,3)*C(8,2) = 10*28 = 280. 4 girls + 1 boy: C(5,4)*C(8,1) = 5*8 = 40. 5 girls: C(5,5) = 1. Total = 280+40+1 = 321. Hmm, that doesn't match 220. Let me recalculate: C(5,3)*C(8,2) = 10*28 = 280. C(5,4)*C(8,1) = 5*8 = 40. C(5,5) = 1. Total = 321. The answer should be 321.", "difficulty": "hard", "time_limit": 120, "companies": ["TCS"], "topic": "Permutations"},

    # ═══════════════════════════════════════════════════════════════════════════
    # LOGICAL — More Series (15 problems)
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "APT-L-100", "category": "logical", "sub_category": "Series", "question": "Find the next number: 1, 1, 2, 3, 5, 8, ?", "options": ["13", "11", "12", "10"], "correct_answer": "13", "explanation": "Fibonacci: each number is sum of previous two. 5+8=13.", "difficulty": "easy", "time_limit": 60, "companies": ["TCS", "Wipro"], "topic": "Series"},
    {"id": "APT-L-101", "category": "logical", "sub_category": "Series", "question": "Complete: 10, 20, 35, 55, ?", "options": ["80", "75", "70", "85"], "correct_answer": "80", "explanation": "Differences: 10, 15, 20, 25. Pattern: +5 each time. 55+25=80.", "difficulty": "medium", "time_limit": 60, "companies": ["TCS"], "topic": "Series"},
    {"id": "APT-L-102", "category": "logical", "sub_category": "Series", "question": "Find the odd one out: 2, 5, 10, 17, 26, 37", "options": ["26", "37", "17", "10"], "correct_answer": "37", "explanation": "2=1²+1, 5=2²+1, 10=3²+1, 17=4²+1, 26=5²+1, 37≠6²+1. 36+1=37. Wait, 6²+1=37. So 37 is correct. Let me check: 1²+1=2, 2²+1=5, 3²+1=10, 4²+1=17, 5²+1=26, 6²+1=37. All match. Hmm, maybe the pattern is different. Let me try: 2=1+1, 5=2+3, 10=5+5, 17=10+7, 26=17+9, 37=26+11. Differences: 1,3,5,7,9,11. All odd. So all are valid. Maybe the question has an error.", "difficulty": "medium", "time_limit": 60, "companies": ["TCS"], "topic": "Series"},
    {"id": "APT-L-103", "category": "logical", "sub_category": "Series", "question": "Find the next: 3, 6, 12, 24, ?", "options": ["48", "36", "42", "52"], "correct_answer": "48", "explanation": "Each term is multiplied by 2. 24×2=48.", "difficulty": "easy", "time_limit": 60, "companies": ["TCS"], "topic": "Series"},
    {"id": "APT-L-104", "category": "logical", "sub_category": "Series", "question": "Complete: AZ, BY, CX, DW, ?", "options": ["EV", "EU", "FW", "EX"], "correct_answer": "EV", "explanation": "First letter: A→B→C→D→E. Second: Z→Y→X→W→V.", "difficulty": "easy", "time_limit": 60, "companies": ["TCS"], "topic": "Series"},

    # ═══════════════════════════════════════════════════════════════════════════
    # LOGICAL — More Coding-Decoding (10 problems)
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "APT-L-120", "category": "logical", "sub_category": "Coding-Decoding", "question": "If DELHI is coded as 73541 and CALCUTTA as 82589662, how is CALICUT coded?", "options": ["8251896", "8251986", "8251898", "8251897"], "correct_answer": "8251896", "explanation": "C=8, A=2, L=5, I=1, C=8, U=9, T=6. CALICUT = 8251896.", "difficulty": "hard", "time_limit": 120, "companies": ["TCS", "Wipro"], "topic": "Coding-Decoding"},
    {"id": "APT-L-121", "category": "logical", "sub_category": "Coding-Decoding", "question": "If in a code language, FLOWER is written as GMPXFS, how is GARDEN written?", "options": ["HBSEFO", "HBSEFN", "HBSEFP", "HBSEFO"], "correct_answer": "HBSEFO", "explanation": "F→G(+1), L→M(+1), O→P(+1), W→X(+1), E→F(+1), R→S(+1). Wait, let me check: F=6, G=7 (+1). L=12, M=13 (+1). O=15, P=16 (+1). W=23, X=24 (+1). E=5, F=6 (+1). R=18, S=19 (+1). So GARDEN: G→H(+1), A→B(+1), R→S(+1), D→E(+1), E→F(+1), N→O(+1). GARDEN = HBSEFO.", "difficulty": "medium", "time_limit": 90, "companies": ["TCS"], "topic": "Coding-Decoding"},

    # ═══════════════════════════════════════════════════════════════════════════
    # LOGICAL — More Blood Relations (10 problems)
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "APT-L-140", "category": "logical", "sub_category": "Blood Relations", "question": "A is B's sister. C is B's mother. D is C's father. How is A related to D?", "options": ["Granddaughter", "Daughter", "Sister", "Niece"], "correct_answer": "Granddaughter", "explanation": "D→C(mother)→B(father)→A(sister). A is D's granddaughter.", "difficulty": "medium", "time_limit": 60, "companies": ["TCS"], "topic": "Blood Relations"},
    {"id": "APT-L-141", "category": "logical", "sub_category": "Blood Relations", "question": "Pointing to a photograph, Ram said 'She is the daughter of my grandfather's only son.' Who is in the photograph?", "options": ["Sister", "Daughter", "Mother", "Aunt"], "correct_answer": "Sister", "explanation": "Grandfather's only son = Ram's father. Daughter of Ram's father = Ram's sister.", "difficulty": "easy", "time_limit": 60, "companies": ["TCS"], "topic": "Blood Relations"},

    # ═══════════════════════════════════════════════════════════════════════════
    # LOGICAL — Puzzles (10 problems)
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "APT-L-160", "category": "logical", "sub_category": "Puzzles", "question": "A clock shows 3:15. What is the angle between the hour and minute hands?", "options": ["0°", "7.5°", "15°", "22.5°"], "correct_answer": "7.5°", "explanation": "Minute hand at 15 min = 90°. Hour hand at 3:15 = 90 + 15*0.5 = 97.5°. Angle = 7.5°.", "difficulty": "medium", "time_limit": 90, "companies": ["TCS", "Wipro"], "topic": "Puzzles"},
    {"id": "APT-L-161", "category": "logical", "sub_category": "Puzzles", "question": "If today is Monday, what day will it be after 100 days?", "options": ["Wednesday", "Tuesday", "Thursday", "Friday"], "correct_answer": "Wednesday", "explanation": "100 mod 7 = 2. Monday + 2 = Wednesday.", "difficulty": "easy", "time_limit": 60, "companies": ["TCS"], "topic": "Puzzles"},

    # ═══════════════════════════════════════════════════════════════════════════
    # LOGICAL — Syllogisms (10 problems)
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "APT-L-180", "category": "logical", "sub_category": "Syllogisms", "question": "Statement: No fish can fly. Some birds can fly. Conclusion: No fish is a bird.", "options": ["True", "False", "Cannot be determined", "Partially true"], "correct_answer": "False", "explanation": "Just because no fish can fly and some birds can fly doesn't mean no fish is a bird. Fish and birds are separate categories.", "difficulty": "medium", "time_limit": 30, "companies": ["TCS"], "topic": "Syllogisms"},
    {"id": "APT-L-181", "category": "logical", "sub_category": "Syllogisms", "question": "Statement: All managers are leaders. All leaders are thinkers. Conclusion: Some thinkers are managers.", "options": ["True", "False", "Cannot be determined", "Partially true"], "correct_answer": "True", "explanation": "All managers are leaders and all leaders are thinkers, so all managers are thinkers. Therefore some thinkers are managers.", "difficulty": "easy", "time_limit": 30, "companies": ["TCS"], "topic": "Syllogisms"},

    # ═══════════════════════════════════════════════════════════════════════════
    # VERBAL — More Synonyms (15 problems)
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "APT-V-100", "category": "verbal", "sub_category": "Synonyms", "question": "Choose the synonym of 'Ubiquitous':", "options": ["Rare", "Omnipresent", "Unique", "Scarce"], "correct_answer": "Omnipresent", "explanation": "Ubiquitous means present everywhere. Synonym: omnipresent.", "difficulty": "medium", "time_limit": 30, "companies": ["TCS", "Amazon"], "topic": "Synonyms"},
    {"id": "APT-V-101", "category": "verbal", "sub_category": "Synonyms", "question": "Choose the synonym of 'Mitigate':", "options": ["Aggravate", "Alleviate", "Intensify", "Worsen"], "correct_answer": "Alleviate", "explanation": "Mitigate means to make less severe. Synonym: alleviate.", "difficulty": "medium", "time_limit": 30, "companies": ["TCS"], "topic": "Synonyms"},
    {"id": "APT-V-102", "category": "verbal", "sub_category": "Synonyms", "question": "Choose the synonym of 'Resilient':", "options": ["Fragile", "Durable", "Weak", "Brittle"], "correct_answer": "Durable", "explanation": "Resilient means able to recover quickly. Synonym: durable.", "difficulty": "easy", "time_limit": 30, "companies": ["TCS"], "topic": "Synonyms"},
    {"id": "APT-V-103", "category": "verbal", "sub_category": "Synonyms", "question": "Choose the synonym of 'Meticulous':", "options": ["Careless", "Thorough", "Lazy", "Sloppy"], "correct_answer": "Thorough", "explanation": "Meticulous means showing great attention to detail. Synonym: thorough.", "difficulty": "easy", "time_limit": 30, "companies": ["TCS"], "topic": "Synonyms"},

    # ═══════════════════════════════════════════════════════════════════════════
    # VERBAL — More Antonyms (15 problems)
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "APT-V-120", "category": "verbal", "sub_category": "Antonyms", "question": "Choose the antonym of 'Lethargic':", "options": ["Energetic", "Lazy", "Tired", "Sluggish"], "correct_answer": "Energetic", "explanation": "Lethargic means lacking energy. Antonym: energetic.", "difficulty": "easy", "time_limit": 30, "companies": ["TCS"], "topic": "Antonyms"},
    {"id": "APT-V-121", "category": "verbal", "sub_category": "Antonyms", "question": "Choose the antonym of 'Transparent':", "options": ["Clear", "Opaque", "Visible", "Open"], "correct_answer": "Opaque", "explanation": "Transparent means see-through. Antonym: opaque.", "difficulty": "easy", "time_limit": 30, "companies": ["TCS"], "topic": "Antonyms"},
    {"id": "APT-V-122", "category": "verbal", "sub_category": "Antonyms", "question": "Choose the antonym of 'Enormous':", "options": ["Huge", "Tiny", "Large", "Gigantic"], "correct_answer": "Tiny", "explanation": "Enormous means very large. Antonym: tiny.", "difficulty": "easy", "time_limit": 30, "companies": ["TCS"], "topic": "Antonyms"},
    {"id": "APT-V-123", "category": "verbal", "sub_category": "Antonyms", "question": "Choose the antonym of 'Frugal':", "options": ["Thrifty", "Extravagant", "Economical", "Prudent"], "correct_answer": "Extravagant", "explanation": "Frugal means sparing. Antonym: extravagant.", "difficulty": "medium", "time_limit": 30, "companies": ["TCS"], "topic": "Antonyms"},

    # ═══════════════════════════════════════════════════════════════════════════
    # VERBAL — More Grammar (15 problems)
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "APT-V-140", "category": "verbal", "sub_category": "Grammar", "question": "Choose the correct article: 'He is ___ honest man.'", "options": ["a", "an", "the", "no article"], "correct_answer": "an", "explanation": "'Honest' starts with a vowel sound, so use 'an'.", "difficulty": "easy", "time_limit": 30, "companies": ["TCS"], "topic": "Grammar"},
    {"id": "APT-V-141", "category": "verbal", "sub_category": "Grammar", "question": "Fill in: 'If I ___ you, I would accept the offer.'", "options": ["was", "am", "were", "be"], "correct_answer": "were", "explanation": "Subjunctive mood: 'If I were you' is correct.", "difficulty": "easy", "time_limit": 30, "companies": ["TCS"], "topic": "Grammar"},
    {"id": "APT-V-142", "category": "verbal", "sub_category": "Grammar", "question": "Choose the correct preposition: 'He is allergic ___ dust.'", "options": ["to", "from", "with", "of"], "correct_answer": "to", "explanation": "'Allergic to' is the correct preposition.", "difficulty": "easy", "time_limit": 30, "companies": ["TCS"], "topic": "Grammar"},

    # ═══════════════════════════════════════════════════════════════════════════
    # VERBAL — Reading Comprehension (10 problems)
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "APT-V-160", "category": "verbal", "sub_category": "Reading Comprehension", "question": "Read: 'Artificial intelligence is transforming industries worldwide. From healthcare to finance, AI systems are automating tasks that once required human intervention. While this increases efficiency, it also raises concerns about job displacement.' What is the author's main concern?", "options": ["AI is too expensive", "Job displacement", "AI is unreliable", "Healthcare needs AI"], "correct_answer": "Job displacement", "explanation": "The passage explicitly mentions 'concerns about job displacement' as the main concern.", "difficulty": "easy", "time_limit": 60, "companies": ["TCS", "Wipro"], "topic": "Reading Comprehension"},
    {"id": "APT-V-161", "category": "verbal", "sub_category": "Reading Comprehension", "question": "Read: 'Remote work has become the new normal. Studies show that employees are 13% more productive when working from home. However, 67% of managers believe remote workers are more easily distracted.' What does the passage suggest about manager perception vs actual productivity?", "options": ["Managers are always right", "There's a disconnect between perception and data", "Remote work is bad", "Productivity doesn't matter"], "correct_answer": "There's a disconnect between perception and data", "explanation": "The passage contrasts data (13% more productive) with manager beliefs (easily distracted), suggesting a disconnect.", "difficulty": "medium", "time_limit": 60, "companies": ["TCS"], "topic": "Reading Comprehension"},
]
