"""
HLD Final Batch — Additional high-level design problems.
More distributed systems and large-scale applications.
"""

HLD_FINAL = [
    # More Social Media (20)
    {"id": "HLD-200", "title": "Design a Live Streaming Platform", "difficulty": "hard", "category": "hld", "subcategory": "Streaming", "statement": "Design a live streaming platform with real-time video and chat.", "requirements": ["Live video streaming", "Real-time chat", "Viewer management", "Recording", "Monetization"], "key_components": ["Ingest Server", "Transcoding", "CDN", "Chat Service", "WebSocket"], "estimated_users": "10M concurrent viewers", "companies": ["Twitch", "YouTube"], "hints": ["RTMP for ingest", "WebSocket for chat", "CDN for delivery"], "video_url": "https://www.youtube.com/results?search_query=live+streaming+system+design"},
    {"id": "HLD-201", "title": "Design a Podcast Platform", "difficulty": "medium", "category": "hld", "subcategory": "Streaming", "statement": "Design a podcast platform like Spotify for podcasts.", "requirements": ["Audio streaming", "Episode management", "Subscriptions", "Offline downloads", "Recommendations"], "key_components": ["Audio Service", "Episode Service", "Subscription Service", "CDN"], "estimated_users": "100M users", "companies": ["Spotify", "Apple"], "hints": ["Audio encoding/compression", "RSS feeds for podcasts", "Recommendation engine"], "video_url": "https://www.youtube.com/results?search_query=podcast+platform+system+design"},

    # More E-commerce (20)
    {"id": "HLD-210", "title": "Design an Auction Platform", "difficulty": "medium", "category": "hld", "subcategory": "E-commerce", "statement": "Design an auction platform like eBay auctions.", "requirements": ["Bid placement", "Real-time bidding", "Timer management", "Winner notification", "Payment processing"], "key_components": ["Bid Service", "Timer Service", "Notification Service", "Payment Service"], "estimated_users": "1M concurrent bidders", "companies": ["eBay"], "hints": ["WebSocket for real-time bids", "Redis for bid ranking", "Consider anti-sniping extensions"], "video_url": "https://www.youtube.com/results?search_query=auction+platform+system+design"},
    {"id": "HLD-211", "title": "Design a Freelancing Platform", "difficulty": "medium", "category": "hld", "subcategory": "E-commerce", "statement": "Design a freelancing platform like Upwork or Fiverr.", "requirements": ["Freelancer profiles", "Job postings", "Proposals", "Milestone tracking", "Payment escrow"], "key_components": ["Profile Service", "Job Service", "Proposal Service", "Payment Service", "Messaging"], "estimated_users": "50M users", "companies": ["Upwork", "Fiverr"], "hints": ["Escrow for payments", "Skill matching algorithm", "Review system"], "video_url": "https://www.youtube.com/results?search_query=freelancing+platform+system+design"},

    # More Infrastructure (25)
    {"id": "HLD-220", "title": "Design a Feature Flag System", "difficulty": "medium", "category": "hld", "subcategory": "Infrastructure", "statement": "Design a feature flag system for gradual rollouts.", "requirements": ["Create flags", "Toggle flags", "Percentage rollouts", "User targeting", "A/B testing"], "key_components": ["Flag Service", "Targeting Engine", "Analytics", "SDK"], "estimated_users": "10M flag evaluations/day", "companies": ["LaunchDarkly", "Split"], "hints": ["Use Redis for fast flag lookups", "Consider user segmentation", "Track flag usage analytics"], "video_url": "https://www.youtube.com/results?search_query=feature+flag+system+design"},
    {"id": "HLD-221", "title": "Design a Circuit Breaker", "difficulty": "medium", "category": "hld", "subcategory": "Infrastructure", "statement": "Design a circuit breaker pattern for fault tolerance.", "requirements": ["Detect failures", "Open circuit", "Half-open state", "Close circuit", "Metrics"], "key_components": ["Circuit Breaker", "Failure Counter", "Timer", "Metrics"], "estimated_users": "1M calls/sec", "companies": ["Netflix", "Amazon"], "hints": ["Three states: Closed, Open, Half-Open", "Configurable thresholds", "Consider Hystrix patterns"], "video_url": "https://www.youtube.com/results?search_query=circuit+breaker+system+design"},

    # More Data (20)
    {"id": "HLD-230", "title": "Design a Recommendation Engine", "difficulty": "hard", "category": "hld", "subcategory": "Data", "statement": "Design a recommendation engine for an e-commerce platform.", "requirements": ["Collaborative filtering", "Content-based filtering", "Real-time updates", "A/B testing", "Cold start handling"], "key_components": ["Feature Store", "ML Model", "Real-time Pipeline", "A/B Testing", "Analytics"], "estimated_users": "100M products, 1B users", "companies": ["Amazon", "Netflix"], "hints": ["Hybrid approach for best results", "Consider real-time vs batch processing", "Handle cold start with content-based"], "video_url": "https://www.youtube.com/results?search_query=recommendation+engine+system+design"},
    {"id": "HLD-231", "title": "Design a Fraud Detection System", "difficulty": "hard", "category": "hld", "subcategory": "Data", "statement": "Design a real-time fraud detection system.", "requirements": ["Real-time scoring", "Rule engine", "ML models", "Alert system", "Case management"], "key_components": ["Scoring Engine", "Rule Engine", "ML Pipeline", "Alert Service", "Case Manager"], "estimated_users": "1M transactions/sec", "companies": ["PayPal", "Stripe"], "hints": ["Real-time ML inference", "Feature engineering", "Consider explainability"], "video_url": "https://www.youtube.com/results?search_query=fraud+detection+system+design"},

    # More Misc (25)
    {"id": "HLD-240", "title": "Design a Code Review Platform", "difficulty": "medium", "category": "hld", "subcategory": "Misc", "statement": "Design a code review platform like GitHub Pull Requests.", "requirements": ["Create pull requests", "Review comments", "Merge strategies", "CI/CD integration", "Permissions"], "key_components": ["PR Service", "Review Service", "CI/CD Service", "Notification Service"], "estimated_users": "100M developers", "companies": ["GitHub", "GitLab"], "hints": ["Webhooks for CI/CD", "Real-time collaboration", "Consider merge conflict resolution"], "video_url": "https://www.youtube.com/results?search_query=code+review+platform+system+design"},
    {"id": "HLD-241", "title": "Design a Wiki Platform", "difficulty": "medium", "category": "hld", "subcategory": "Misc", "statement": "Design a wiki platform like Wikipedia.", "requirements": ["Create/edit pages", "Version history", "Search", "Permissions", "Collaboration"], "key_components": ["Page Service", "Version Control", "Search Index", "Permission Service"], "estimated_users": "1B pages", "companies": ["Wikipedia"], "hints": ["Version control for page history", "Full-text search with Elasticsearch", "Consider edit conflicts"], "video_url": "https://www.youtube.com/results?search_query=wiki+platform+system+design"},
    {"id": "HLD-242", "title": "Design a Real-Time Collaboration Tool", "difficulty": "hard", "category": "hld", "subcategory": "Misc", "statement": "Design a real-time collaboration tool like Google Docs.", "requirements": ["Real-time editing", "Conflict resolution", "Version history", "Comments", "Sharing"], "key_components": ["CRDT/OT Engine", "WebSocket", "Version Control", "Permission Service"], "estimated_users": "10M concurrent editors", "companies": ["Google", "Notion"], "hints": ["Use CRDT for conflict-free merging", "WebSocket for real-time sync", "Consider operational transform"], "video_url": "https://www.youtube.com/results?search_query=real+time+collaboration+system+design"},
]
