"""
High-Level Design (HLD) Problems — 200+ system architecture problems.
Covers scalability, distributed systems, and large-scale applications.
"""

HLD_PROBLEMS = [
    # ═══════════════════════════════════════════════════════════════════════════
    # SOCIAL MEDIA & COMMUNICATION (30 problems)
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "HLD-001", "title": "Design Twitter", "difficulty": "medium", "category": "hld", "subcategory": "Social Media", "statement": "Design a simplified Twitter where users can post tweets, follow/unfollow other users, and see their news feed (10 most recent tweets from followings).", "requirements": ["Post tweets", "Follow/unfollow users", "Get news feed (10 most recent)", "User profiles"], "key_components": ["API Gateway", "Tweet Service", "Feed Service", "User Service", "Cache", "Database"], "estimated_users": "300M users", "companies": ["Twitter", "Meta", "Google"], "hints": ["Use fan-out on write for news feed", "Cache hot feeds in Redis", "Consider denormalization for feed"], "video_url": "https://www.youtube.com/results?search_query=design+twitter+system+design"},
    {"id": "HLD-002", "title": "Design Instagram", "difficulty": "medium", "category": "hld", "subcategory": "Social Media", "statement": "Design Instagram's core features: photo sharing, following, news feed, and stories.", "requirements": ["Upload photos/videos", "Follow users", "News feed", "Stories (24hr expiry)", "Like/comment"], "key_components": ["Upload Service", "CDN", "Feed Service", "Notification Service"], "estimated_users": "2B users", "companies": ["Meta", "Instagram"], "hints": ["Use CDN for media delivery", "Implement feed ranking algorithm", "Stories expire after 24 hours"], "video_url": "https://www.youtube.com/results?search_query=design+instagram+system+design"},
    {"id": "HLD-003", "title": "Design WhatsApp/Messenger", "difficulty": "hard", "category": "hld", "subcategory": "Communication", "statement": "Design a messaging app supporting 1-on-1 and group chats with real-time delivery.", "requirements": ["Real-time messaging", "Group chats", "Message history", "Read receipts", "Media sharing", "End-to-end encryption"], "key_components": ["WebSocket Server", "Message Queue", "Database", "Push Notification", "File Storage"], "estimated_users": "2B users", "companies": ["Meta", "WhatsApp", "Google"], "hints": ["WebSocket for real-time", "Message queue for reliability", "Shard by conversation ID"], "video_url": "https://www.youtube.com/results?search_query=design+whatsapp+system+design"},
    {"id": "HLD-004", "title": "Design a Notification System", "difficulty": "medium", "category": "hld", "subcategory": "Infrastructure", "statement": "Design a notification system supporting push, SMS, and email with priority levels.", "requirements": ["Multi-channel delivery", "Priority levels", "Rate limiting", "Template management", "Delivery tracking"], "key_components": ["API Gateway", "Notification Service", "Message Queue", "Template Engine", "Analytics"], "estimated_users": "100M notifications/day", "companies": ["Amazon", "Google"], "hints": ["Use message queue for decoupling", "Implement rate limiting per user", "Track delivery status"], "video_url": "https://www.youtube.com/results?search_query=notification+system+design"},
    {"id": "HLD-005", "title": "Design a News Feed System", "difficulty": "hard", "category": "hld", "subcategory": "Social Media", "statement": "Design Facebook/Twitter's news feed that shows posts from friends/followers.", "requirements": ["Post creation", "Feed generation", "Fan-out on write vs read", "Real-time updates", "Content ranking"], "key_components": ["Fan-out Service", "Feed Cache", "Post Service", "Ranking Algorithm"], "estimated_users": "1B users, 500M DAU", "companies": ["Meta", "Twitter", "Google"], "hints": ["Hybrid fan-out: push for <10K followers", "Use Redis for feed cache", "Rank by engagement"], "video_url": "https://www.youtube.com/results?search_query=news+feed+system+design"},

    # ═══════════════════════════════════════════════════════════════════════════
    # E-COMMERCE & MARKETPLACE (25 problems)
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "HLD-010", "title": "Design Amazon E-commerce", "difficulty": "hard", "category": "hld", "subcategory": "E-commerce", "statement": "Design a full e-commerce platform like Amazon with product catalog, cart, checkout, and order management.", "requirements": ["Product catalog with search", "Shopping cart", "Payment processing", "Order management", "Inventory tracking", "Recommendations"], "key_components": ["Product Service", "Cart Service", "Order Service", "Payment Service", "Search Index", "Inventory Service"], "estimated_users": "300M products, 1M orders/day", "companies": ["Amazon", "Google"], "hints": ["Event-driven architecture for orders", "Elasticsearch for product search", "Reserve inventory during checkout"], "video_url": "https://www.youtube.com/results?search_query=amazon+system+design"},
    {"id": "HLD-011", "title": "Design a Food Delivery App", "difficulty": "medium", "category": "hld", "subcategory": "E-commerce", "statement": "Design Uber Eats / DoorDash with restaurant discovery, ordering, and delivery tracking.", "requirements": ["Restaurant discovery", "Menu browsing", "Order placement", "Real-time delivery tracking", "Payment processing"], "key_components": ["Discovery Service", "Order Service", "Delivery Service", "Payment Service", "Real-time Tracking"], "estimated_users": "10M orders/day", "companies": ["Uber", "DoorDash", "Amazon"], "hints": ["Geospatial indexing for restaurant discovery", "WebSocket for delivery tracking", "Consider surge pricing"], "video_url": "https://www.youtube.com/results?search_query=food+delivery+system+design"},
    {"id": "HLD-012", "title": "Design a Ride-Sharing Service", "difficulty": "hard", "category": "hld", "subcategory": "E-commerce", "statement": "Design Uber/Lyft with real-time matching, location tracking, and dynamic pricing.", "requirements": ["Real-time location", "Driver-rider matching", "Dynamic pricing", "Trip management", "Payment processing"], "key_components": ["Location Service", "Matching Service", "Pricing Engine", "Payment Service", "Notification Service"], "estimated_users": "10M rides/day", "companies": ["Uber", "Lyft", "Amazon"], "hints": ["Geospatial indexing (GeoHash)", "Surge pricing algorithm", "Consider driver incentives"], "video_url": "https://www.youtube.com/results?search_query=uber+system+design"},

    # ═══════════════════════════════════════════════════════════════════════════
    # STREAMING & MEDIA (20 problems)
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "HLD-020", "title": "Design YouTube", "difficulty": "hard", "category": "hld", "subcategory": "Streaming", "statement": "Design YouTube's video upload, streaming, and recommendation system.", "requirements": ["Video upload and transcoding", "Adaptive bitrate streaming", "Recommendations", "Comments/ratings", "Search"], "key_components": ["Upload Service", "Transcoding Pipeline", "CDN", "Recommendation Engine", "Search Index"], "estimated_users": "2B users, 500M videos", "companies": ["Google", "YouTube", "Netflix"], "hints": ["Pre-signed URLs for uploads", "HLS/DASH for adaptive streaming", "Collaborative filtering for recommendations"], "video_url": "https://www.youtube.com/results?search_query=youtube+system+design"},
    {"id": "HLD-021", "title": "Design Netflix", "difficulty": "hard", "category": "hld", "subcategory": "Streaming", "statement": "Design Netflix's video streaming platform with adaptive bitrate and global CDN.", "requirements": ["Video streaming", "Adaptive bitrate", "Content recommendations", "Multiple profiles", "Offline viewing"], "key_components": ["Streaming Service", "Transcoding Pipeline", "CDN", "Recommendation Engine", "Content Management"], "estimated_users": "200M subscribers", "companies": ["Netflix", "Amazon"], "hints": ["Use multiple encoding profiles", "CDN for global delivery", "ML for recommendations"], "video_url": "https://www.youtube.com/results?search_query=netflix+system+design"},
    {"id": "HLD-022", "title": "Design a Live Streaming Platform", "difficulty": "hard", "category": "hld", "subcategory": "Streaming", "statement": "Design a live streaming platform like Twitch with real-time video, chat, and viewer management.", "requirements": ["Live video streaming", "Real-time chat", "Viewer management", "Recording", "Monetization"], "key_components": ["Ingest Server", "Transcoding", "CDN", "Chat Service", "WebSocket"], "estimated_users": "10M concurrent viewers", "companies": ["Twitch", "YouTube"], "hints": ["Use RTMP for ingest", "WebSocket for chat", "CDN for delivery"], "video_url": "https://www.youtube.com/results?search_query=live+streaming+system+design"},

    # ═══════════════════════════════════════════════════════════════════════════
    # INFRASTRUCTURE & SYSTEMS (30 problems)
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "HLD-030", "title": "Design a URL Shortener", "difficulty": "medium", "category": "hld", "subcategory": "Infrastructure", "statement": "Design a URL shortening service like bit.ly with analytics.", "requirements": ["Shorten URLs", "Redirect short URLs", "Custom aliases", "Analytics", "Expiry"], "key_components": ["Web Server", "Cache", "Database", "Analytics Service"], "estimated_users": "100M URLs/day", "companies": ["Amazon", "Google"], "hints": ["Base62 encoding", "Redis cache for hot URLs", "Database sharding by hash"], "video_url": "https://www.youtube.com/results?search_query=url+shortener+system+design"},
    {"id": "HLD-031", "title": "Design a Rate Limiter", "difficulty": "medium", "category": "hld", "subcategory": "Infrastructure", "statement": "Design a distributed rate limiting system.", "requirements": ["Multiple algorithms", "Distributed counting", "Configurable limits", "Low latency"], "key_components": ["Redis", "Rate Limiter Middleware", "Configuration Store"], "estimated_users": "1B requests/day", "companies": ["Amazon", "Google"], "hints": ["Token Bucket algorithm", "Redis INCR + EXPIRE", "Consider race conditions"], "video_url": "https://www.youtube.com/results?search_query=rate+limiter+system+design"},
    {"id": "HLD-032", "title": "Design a Distributed Cache", "difficulty": "hard", "category": "hld", "subcategory": "Infrastructure", "statement": "Design a distributed caching system like Redis Cluster.", "requirements": ["Distributed across nodes", "Consistent hashing", "Replication", "Eviction policies", "Pub/Sub"], "key_components": ["Cache Nodes", "Hash Ring", "Replication Manager", "Client Library"], "estimated_users": "1M ops/sec", "companies": ["Amazon", "Google"], "hints": ["Consistent hashing for distribution", "Replication factor of 3", "LRU eviction"], "video_url": "https://www.youtube.com/results?search_query=distributed+cache+system+design"},
    {"id": "HLD-033", "title": "Design a Message Queue", "difficulty": "hard", "category": "hld", "subcategory": "Infrastructure", "statement": "Design a distributed message queue like Kafka or RabbitMQ.", "requirements": ["Publish-subscribe model", "Message ordering", "Durability", "Scalability", "Dead letter queue"], "key_components": ["Broker", "Topic/Partition", "Consumer Group", "Zookeeper"], "estimated_users": "10M messages/sec", "companies": ["Amazon", "LinkedIn", "Uber"], "hints": ["Log-structured storage", "Consumer groups for parallelism", "Replication for durability"], "video_url": "https://www.youtube.com/results?search_query=message+queue+system+design"},
    {"id": "HLD-034", "title": "Design a Load Balancer", "difficulty": "medium", "category": "hld", "subcategory": "Infrastructure", "statement": "Design a load balancer that distributes traffic across multiple servers.", "requirements": ["Traffic distribution", "Health checks", "Session affinity", "SSL termination", "High availability"], "key_components": ["Load Balancer", "Health Monitor", "Server Pool", "Configuration"], "estimated_users": "1M requests/sec", "companies": ["Amazon", "Google", "Cloudflare"], "hints": ["Round-robin, least connections, or IP hash", "Active health checks", "Sticky sessions for stateful apps"], "video_url": "https://www.youtube.com/results?search_query=load+balancer+system+design"},
    {"id": "HLD-035", "title": "Design a Search Autocomplete", "difficulty": "medium", "category": "hld", "subcategory": "Infrastructure", "statement": "Design Google's search autocomplete system.", "requirements": ["Real-time suggestions", "Top-K per prefix", "Update from analytics", "< 100ms latency"], "key_components": ["Trie", "Cache", "Analytics Service", "Database"], "estimated_users": "10B queries/day", "companies": ["Google", "Amazon"], "hints": ["Trie for prefix matching", "Cache hot prefixes", "Update trie from analytics"], "video_url": "https://www.youtube.com/results?search_query=search+autocomplete+system+design"},

    # ═══════════════════════════════════════════════════════════════════════════
    # DATA & ANALYTICS (25 problems)
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "HLD-040", "title": "Design a Web Crawler", "difficulty": "hard", "category": "hld", "subcategory": "Data", "statement": "Design a web crawler that can crawl billions of web pages.", "requirements": ["Crawl web pages", "Respect robots.txt", "Deduplication", "Distributed crawling", "Rate limiting"], "key_components": ["URL Frontier", "Fetcher", "Parser", "Deduplication Service", "Storage"], "estimated_users": "1B pages/day", "companies": ["Google", "Amazon"], "hints": ["BFS with priority queue", "Bloom filter for dedup", "Politeness delays"], "video_url": "https://www.youtube.com/results?search_query=web+crawler+system+design"},
    {"id": "HLD-041", "title": "Design a Search Engine", "difficulty": "hard", "category": "hld", "subcategory": "Data", "statement": "Design Google's search engine with crawling, indexing, and ranking.", "requirements": ["Crawl web pages", "Build inverted index", "Rank results", "Handle billions of queries"], "key_components": ["Web Crawler", "Indexer", "Ranking Algorithm", "Query Processor", "Cache"], "estimated_users": "10B queries/day", "companies": ["Google", "Microsoft"], "hints": ["Inverted index for text search", "PageRank for ranking", "Cache top queries"], "video_url": "https://www.youtube.com/results?search_query=search+engine+system+design"},

    # ═══════════════════════════════════════════════════════════════════════════
    # PAYMENT & FINANCE (20 problems)
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "HLD-050", "title": "Design a Payment System", "difficulty": "hard", "category": "hld", "subcategory": "Finance", "statement": "Design a payment processing system like Stripe.", "requirements": ["Payment processing", "Idempotency", "Refunds", "PCI compliance", "Fraud detection"], "key_components": ["Payment Gateway", "Fraud Detection", "Ledger", "Notification"], "estimated_users": "1M transactions/day", "companies": ["Amazon", "Stripe"], "hints": ["Idempotency keys prevent double charges", "Tokenization for PCI", "Two-phase commit for consistency"], "video_url": "https://www.youtube.com/results?search_query=payment+system+design"},

    # ═══════════════════════════════════════════════════════════════════════════
    # MISC & DOMAIN-SPECIFIC (40 problems)
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "HLD-060", "title": "Design a Parking Lot", "difficulty": "medium", "category": "hld", "subcategory": "Misc", "statement": "Design a parking lot system with multiple floors and vehicle types.", "requirements": ["Park vehicles", "Find parking spots", "Multiple floors", "Vehicle types", "Pricing"], "key_components": ["Parking Manager", "Floor Manager", "Spot Manager", "Payment Service"], "estimated_users": "1000 vehicles", "companies": ["Amazon", "Google"], "hints": ["Use matrix for spots", "BFS for finding nearest spot", "Consider different vehicle sizes"], "video_url": "https://www.youtube.com/results?search_query=parking+lot+system+design"},
    {"id": "HLD-061", "title": "Design a Chess Game", "difficulty": "hard", "category": "hld", "subcategory": "Misc", "statement": "Design an online chess game supporting multiplayer.", "requirements": ["Board representation", "Move validation", "Multiplayer", "Game state", "Undo/redo"], "key_components": ["Game Server", "Board State", "Move Validator", "WebSocket", "Database"], "estimated_users": "10M games/day", "companies": ["Amazon", "Google"], "hints": ["Bitboard for board representation", "WebSocket for real-time", "FEN for board state"], "video_url": "https://www.youtube.com/results?search_query=chess+game+system+design"},
    {"id": "HLD-062", "title": "Design a Ticket Booking System", "difficulty": "medium", "category": "hld", "subcategory": "E-commerce", "statement": "Design a ticket booking system like BookMyShow.", "requirements": ["Event browsing", "Seat selection", "Payment", "Flash sales", "Prevent double booking"], "key_components": ["Event Service", "Seat Service", "Booking Service", "Payment Service", "Queue Service"], "estimated_users": "10K concurrent", "companies": ["Amazon", "Microsoft"], "hints": ["Optimistic locking for seats", "Virtual waiting room for flash sales", "Seat lock timeout"], "video_url": "https://www.youtube.com/results?search_query=ticket+booking+system+design"},
    {"id": "HLD-063", "title": "Design a Real-Time Leaderboard", "difficulty": "medium", "category": "hld", "subcategory": "Gaming", "statement": "Design a real-time leaderboard for a gaming platform.", "requirements": ["Real-time score updates", "Top-K queries", "Range queries", "Persistence", "Millions of players"], "key_components": ["Score Service", "Redis Sorted Set", "WebSocket", "Database"], "estimated_users": "10M players", "companies": ["Amazon", "Google"], "hints": ["Redis Sorted Set (ZADD, ZRANGE)", "WebSocket for real-time", "Periodic snapshots"], "video_url": "https://www.youtube.com/results?search_query=leaderboard+system+design"},
    {"id": "HLD-064", "title": "Design a File Storage System", "difficulty": "hard", "category": "hld", "subcategory": "Infrastructure", "statement": "Design a distributed file storage system like Google Drive.", "requirements": ["Upload/download files", "Folder hierarchy", "Sharing permissions", "Versioning", "Sync across devices"], "key_components": ["File Service", "Metadata Service", "Storage (S3)", "Sync Service", "Permission Service"], "estimated_users": "1B files", "companies": ["Google", "Dropbox", "Amazon"], "hints": ["Chunk files for upload", "Use content-addressable storage", "Implement delta sync"], "video_url": "https://www.youtube.com/results?search_query=file+storage+system+design"},
]
