"""
HLD Problems Batch 2 — Additional high-level design problems.
More distributed systems and large-scale applications.
"""

HLD_BATCH2 = [
    # More Social Media (15)
    {"id": "HLD-070", "title": "Design TikTok", "difficulty": "medium", "category": "hld", "subcategory": "Social Media", "statement": "Design TikTok's short video platform with feed and recommendations.", "requirements": ["Video upload", "Short video feed", "Recommendations", "Like/comment/share", "Following"], "key_components": ["Upload Service", "Feed Service", "Recommendation Engine", "CDN"], "estimated_users": "1B users", "companies": ["ByteDance", "Meta"], "hints": ["ML for feed ranking", "CDN for video delivery", "Consider video compression"], "video_url": "https://www.youtube.com/results?search_query=tiktok+system+design"},
    {"id": "HLD-071", "title": "Design LinkedIn", "difficulty": "medium", "category": "hld", "subcategory": "Social Media", "statement": "Design LinkedIn's professional networking platform.", "requirements": ["Profiles", "Connection requests", "Job postings", "Feed", "Messaging"], "key_components": ["Profile Service", "Connection Service", "Job Service", "Feed Service", "Messaging"], "estimated_users": "900M users", "companies": ["LinkedIn", "Microsoft"], "hints": ["Graph model for connections", "Recommendation engine for jobs", "InMail for messaging"], "video_url": "https://www.youtube.com/results?search_query=linkedin+system+design"},

    # More E-commerce (15)
    {"id": "HLD-080", "title": "Design Uber Eats", "difficulty": "medium", "category": "hld", "subcategory": "E-commerce", "statement": "Design Uber Eats food delivery platform.", "requirements": ["Restaurant discovery", "Menu/ordering", "Real-time tracking", "Payment", "Reviews"], "key_components": ["Discovery Service", "Order Service", "Delivery Tracking", "Payment Service"], "estimated_users": "10M orders/day", "companies": ["Uber", "DoorDash"], "hints": ["Geospatial indexing", "WebSocket for tracking", "Dynamic pricing"], "video_url": "https://www.youtube.com/results?search_query=uber+eats+system+design"},

    # More Streaming (15)
    {"id": "HLD-090", "title": "Design Spotify", "difficulty": "medium", "category": "hld", "subcategory": "Streaming", "statement": "Design Spotify's music streaming platform.", "requirements": ["Music streaming", "Playlists", "Recommendations", "Offline mode", "Social features"], "key_components": ["Streaming Service", "Recommendation Engine", "CDN", "User Service"], "estimated_users": "500M users", "companies": ["Spotify"], "hints": ["Audio encoding/compression", "ML for recommendations", "Offline caching"], "video_url": "https://www.youtube.com/results?search_query=spotify+system+design"},

    # More Infrastructure (20)
    {"id": "HLD-100", "title": "Design a Distributed Lock", "difficulty": "hard", "category": "hld", "subcategory": "Infrastructure", "statement": "Design a distributed locking system like Redis Lock.", "requirements": ["Acquire/release locks", "Deadlock prevention", "Fault tolerance", "Expiration"], "key_components": ["Lock Manager", "Redis", "Heartbeat", "Recovery"], "estimated_users": "1M locks/sec", "companies": ["Amazon", "Google"], "hints": ["Use Redis SET with NX and PX", "Implement lock renewal", "Consider Redlock algorithm"], "video_url": "https://www.youtube.com/results?search_query=distributed+lock+system+design"},
    {"id": "HLD-101", "title": "Design a Job Scheduler", "difficulty": "medium", "category": "hld", "subcategory": "Infrastructure", "statement": "Design a distributed job scheduling system.", "requirements": ["Schedule jobs", "Cron expressions", "Retry logic", "Monitoring", "Distributed execution"], "key_components": ["Scheduler", "Worker Pool", "Job Queue", "Database", "Monitoring"], "estimated_users": "10M jobs/day", "companies": ["Amazon", "Google"], "hints": ["Use priority queue", "Partition by time range", "Dead letter queue for failures"], "video_url": "https://www.youtube.com/results?search_query=job+scheduler+system+design"},

    # More Data (15)
    {"id": "HLD-110", "title": "Design a Data Pipeline", "difficulty": "hard", "category": "hld", "subcategory": "Data", "statement": "Design a real-time data pipeline for analytics.", "requirements": ["Data ingestion", "Transformation", "Storage", "Querying", "Real-time processing"], "key_components": ["Data Ingestion", "Stream Processing", "Data Lake", "Analytics Engine"], "estimated_users": "1TB data/day", "companies": ["Amazon", "Google", "Netflix"], "hints": ["Kafka for streaming", "Spark for processing", "S3 for storage"], "video_url": "https://www.youtube.com/results?search_query=data+pipeline+system+design"},

    # More Finance (10)
    {"id": "HLD-120", "title": "Design a Stock Trading Platform", "difficulty": "hard", "category": "hld", "subcategory": "Finance", "statement": "Design a stock trading platform with real-time price updates.", "requirements": ["Real-time prices", "Order matching", "Portfolio management", "Trade history", "Charts"], "key_components": ["Price Feed", "Order Book", "Matching Engine", "Portfolio Service", "Chart Service"], "estimated_users": "1M concurrent traders", "companies": ["Goldman Sachs", "Bloomberg"], "hints": ["WebSocket for real-time prices", "Priority queue for order matching", "Event sourcing for trade history"], "video_url": "https://www.youtube.com/results?search_query=stock+trading+system+design"},

    # More Misc (25)
    {"id": "HLD-130", "title": "Design a Weather App", "difficulty": "medium", "category": "hld", "subcategory": "Misc", "statement": "Design a weather forecasting application.", "requirements": ["Current weather", "Forecasts", "Location-based", "Alerts", "Historical data"], "key_components": ["Weather Service", "Location Service", "Forecast Engine", "Notification Service"], "estimated_users": "100M users", "companies": ["Google", "Apple"], "hints": ["Integrate weather APIs", "Cache forecasts", "Push notifications for alerts"], "video_url": "https://www.youtube.com/results?search_query=weather+app+system+design"},
    {"id": "HLD-131", "title": "Design a Maps Application", "difficulty": "hard", "category": "hld", "subcategory": "Misc", "statement": "Design Google Maps with navigation and traffic.", "requirements": ["Map rendering", "Navigation", "Traffic data", "Points of interest", "Offline maps"], "key_components": ["Map Service", "Navigation Service", "Traffic Service", "POI Service", "CDN"], "estimated_users": "1B users", "companies": ["Google", "Apple"], "hints": ["Tile-based map rendering", "A* for navigation", "Real-time traffic from GPS"], "video_url": "https://www.youtube.com/results?search_query=google+maps+system+design"},
    {"id": "HLD-132", "title": "Design a Collaboration Tool", "difficulty": "hard", "category": "hld", "subcategory": "Misc", "statement": "Design a real-time collaboration tool like Google Docs.", "requirements": ["Real-time editing", "Conflict resolution", "Version history", "Comments", "Sharing"], "key_components": ["CRDT/OT Engine", "WebSocket", "Version Control", "Permission Service"], "estimated_users": "10M concurrent editors", "companies": ["Google", "Notion"], "hints": ["Use CRDT or Operational Transform", "WebSocket for real-time sync", "Vector clocks for ordering"], "video_url": "https://www.youtube.com/results?search_query=google+docs+system+design"},
]
