"""
HLD Extra Batch — Additional high-level design problems.
More distributed systems and large-scale applications.
"""

HLD_EXTRA = [
    # More Social Media (15)
    {"id": "HLD-140", "title": "Design Facebook Marketplace", "difficulty": "medium", "category": "hld", "subcategory": "Social Media", "statement": "Design Facebook's marketplace for buying and selling items.", "requirements": ["List items", "Search/browse", "Messaging", "Location-based", "Reviews"], "key_components": ["Item Service", "Search Service", "Messaging Service", "Payment Service"], "estimated_users": "100M users", "companies": ["Meta", "Facebook"], "hints": ["Geospatial indexing for location", "Real-time messaging", "Trust scoring"], "video_url": "https://www.youtube.com/results?search_query=facebook+marketplace+system+design"},
    {"id": "HLD-141", "title": "Design Discord", "difficulty": "medium", "category": "hld", "subcategory": "Social Media", "statement": "Design Discord's voice and text chat platform.", "requirements": ["Text channels", "Voice channels", "Server management", "Bots", "File sharing"], "key_components": ["WebSocket Server", "Voice Service", "File Storage", "Bot Service"], "estimated_users": "200M users", "companies": ["Discord"], "hints": ["WebRTC for voice", "WebSocket for text", "Consider channel permissions"], "video_url": "https://www.youtube.com/results?search_query=discord+system+design"},

    # More E-commerce (15)
    {"id": "HLD-150", "title": "Design Airbnb", "difficulty": "hard", "category": "hld", "subcategory": "E-commerce", "statement": "Design Airbnb's booking platform with listings, search, and reviews.", "requirements": ["Property listings", "Search with filters", "Booking system", "Reviews/ratings", "Payment"], "key_components": ["Search Service", "Booking Service", "Payment Service", "Review Service", "CDN"], "estimated_users": "150M users", "companies": ["Airbnb"], "hints": ["Geospatial search", "Dynamic pricing", "Trust scoring"], "video_url": "https://www.youtube.com/results?search_query=airbnb+system+design"},

    # More Streaming (15)
    {"id": "HLD-160", "title": "Design Twitch", "difficulty": "hard", "category": "hld", "subcategory": "Streaming", "statement": "Design Twitch's live streaming platform.", "requirements": ["Live video streaming", "Chat system", "Emotes/bits", "VOD storage", "Recommendations"], "key_components": ["Ingest Server", "Transcoding", "CDN", "Chat Service", "VOD Storage"], "estimated_users": "30M concurrent", "companies": ["Twitch", "Amazon"], "hints": ["RTMP for ingest", "WebRTC for low-latency", "Consider monetization"], "video_url": "https://www.youtube.com/results?search_query=twitch+system+design"},

    # More Infrastructure (20)
    {"id": "HLD-170", "title": "Design a Distributed Configuration Service", "difficulty": "hard", "category": "hld", "subcategory": "Infrastructure", "statement": "Design a distributed configuration service like Spring Cloud Config.", "requirements": ["Store configurations", "Version control", "Hot reload", "Encryption", "Audit logging"], "key_components": ["Config Server", "Config Store", "Notification Service", "Encryption Service"], "estimated_users": "10K services", "companies": ["Netflix", "Amazon"], "hints": ["Use Git for version control", "Pub/Sub for hot reload", "Consider encryption at rest"], "video_url": "https://www.youtube.com/results?search_query=distributed+configuration+system+design"},
    {"id": "HLD-171", "title": "Design a Service Mesh", "difficulty": "hard", "category": "hld", "subcategory": "Infrastructure", "statement": "Design a service mesh for microservices communication.", "requirements": ["Service discovery", "Load balancing", "Circuit breaker", "Tracing", "Security"], "key_components": ["Sidecar Proxy", "Control Plane", "Data Plane", "Certificate Manager"], "estimated_users": "10K services", "companies": ["Istio", "Linkerd"], "hints": ["Sidecar pattern", "mTLS for security", "Consider Envoy proxy"], "video_url": "https://www.youtube.com/results?search_query=service+mesh+system+design"},

    # More Data (15)
    {"id": "HLD-180", "title": "Design a Real-Time Analytics Dashboard", "difficulty": "medium", "category": "hld", "subcategory": "Data", "statement": "Design a real-time analytics dashboard for monitoring.", "requirements": ["Real-time metrics", "Historical data", "Alerts", "Custom dashboards", "Export"], "key_components": ["Metrics Collector", "Time-Series DB", "Query Engine", "Alert Manager", "Dashboard UI"], "estimated_users": "10M metrics/sec", "companies": ["Datadog", "Grafana"], "hints": ["InfluxDB for time-series", "Grafana for visualization", "Consider downsampling"], "video_url": "https://www.youtube.com/results?search_query=analytics+dashboard+system+design"},

    # More Misc (20)
    {"id": "HLD-190", "title": "Design a Recipe Platform", "difficulty": "medium", "category": "hld", "subcategory": "Misc", "statement": "Design a recipe sharing platform like AllRecipes.", "requirements": ["Recipe browsing", "Search/filter", "User ratings", "Meal planning", "Grocery lists"], "key_components": ["Recipe Service", "Search Service", "User Service", "Recommendation Engine"], "estimated_users": "50M users", "companies": ["AllRecipes", "Epicurious"], "hints": ["Content-based filtering", "Ingredient matching", "Consider nutrition data"], "video_url": "https://www.youtube.com/results?search_query=recipe+platform+system+design"},
    {"id": "HLD-191", "title": "Design a Fitness Tracking App", "difficulty": "medium", "category": "hld", "subcategory": "Misc", "statement": "Design a fitness tracking app like Strava or Fitbit.", "requirements": ["Activity tracking", "GPS routes", "Social features", "Analytics", "Wearable sync"], "key_components": ["Tracking Service", "GPS Service", "Analytics Engine", "Social Service", "Wearable API"], "estimated_users": "50M users", "companies": ["Fitbit", "Strava"], "hints": ["GPS data compression", "Real-time sync", "Consider battery optimization"], "video_url": "https://www.youtube.com/results?search_query=fitness+tracking+system+design"},
    {"id": "HLD-192", "title": "Design a Learning Management System", "difficulty": "medium", "category": "hld", "subcategory": "Misc", "statement": "Design an LMS like Coursera or Udemy.", "requirements": ["Course management", "Video streaming", "Quizzes", "Progress tracking", "Certificates"], "key_components": ["Course Service", "Video Service", "Quiz Service", "Progress Service", "Certificate Service"], "estimated_users": "100M users", "companies": ["Coursera", "Udemy"], "hints": ["DRM for video content", "Adaptive learning paths", "Consider offline access"], "video_url": "https://www.youtube.com/results?search_query=learning+management+system+design"},
    {"id": "HLD-193", "title": "Design a Job Portal", "difficulty": "medium", "category": "hld", "subcategory": "Misc", "statement": "Design a job portal like LinkedIn Jobs or Indeed.", "requirements": ["Job listings", "Resume parsing", "Job matching", "Application tracking", "Notifications"], "key_components": ["Job Service", "Resume Parser", "Matching Engine", "Notification Service"], "estimated_users": "50M users", "companies": ["LinkedIn", "Indeed"], "hints": ["NLP for resume parsing", "ML for job matching", "Consider application status tracking"], "video_url": "https://www.youtube.com/results?search_query=job+portal+system+design"},
]
