"""
LLD Final Batch 2 — Additional low-level design problems to reach 200+.
More OOP, data structures, and algorithm design problems.
"""

LLD_FINAL2 = [
    # More Data Structures (15)
    {"id": "LLD-290", "title": "Design a Hash Table with Chaining", "difficulty": "medium", "category": "lld", "subcategory": "Data Structures", "statement": "Design a hash table using separate chaining for collision resolution.", "requirements": ["Insert/Delete/Search", "Handle collisions", "Dynamic resizing"], "key_classes": ["HashTable", "Entry", "Bucket"], "methods": ["put(key, val)", "get(key)", "remove(key)"], "complexity": {"average": "O(1)", "worst": "O(n)"}},
    {"id": "LLD-291", "title": "Design a Hash Table with Open Addressing", "difficulty": "medium", "category": "lld", "subcategory": "Data Structures", "statement": "Design a hash table using open addressing (linear/quadratic probing).", "requirements": ["Insert/Delete/Search", "Handle collisions", "Dynamic resizing"], "key_classes": ["HashTable", "Entry"], "methods": ["put(key, val)", "get(key)", "remove(key)"], "complexity": {"average": "O(1)", "worst": "O(n)"}},
    {"id": "LLD-292", "title": "Design a Circular Doubly Linked List", "difficulty": "medium", "category": "lld", "subcategory": "Data Structures", "statement": "Design a circular doubly linked list.", "requirements": ["Insert/Delete", "Traverse both directions", "Handle empty list"], "key_classes": ["CDNode", "CircularDLL"], "methods": ["insert(val)", "delete(val)", "traverse()"], "complexity": {"insert": "O(1)", "delete": "O(n)"}},
    {"id": "LLD-293", "title": "Design a Min Heap", "difficulty": "medium", "category": "lld", "subcategory": "Data Structures", "statement": "Design a min-heap with insert, extractMin, and peek operations.", "requirements": ["Insert element", "Extract minimum", "Peek minimum", "Heapify", "All O(log n)"], "key_classes": ["MinHeap"], "methods": ["insert(val)", "extractMin()", "peek()", "heapify()"], "complexity": {"insert": "O(log n)", "extractMin": "O(log n)"}},
    {"id": "LLD-294", "title": "Design a Max Heap", "difficulty": "medium", "category": "lld", "subcategory": "Data Structures", "statement": "Design a max-heap with insert, extractMax, and peek operations.", "requirements": ["Insert element", "Extract maximum", "Peek maximum", "Heapify", "All O(log n)"], "key_classes": ["MaxHeap"], "methods": ["insert(val)", "extractMax()", "peek()", "heapify()"], "complexity": {"insert": "O(log n)", "extractMax": "O(log n)"}},

    # More Design Patterns (15)
    {"id": "LLD-300", "title": "Implement Interpreter Pattern", "difficulty": "hard", "category": "lld", "subcategory": "Design Patterns", "statement": "Implement an interpreter pattern for evaluating expressions.", "requirements": ["Parse expressions", "Evaluate expressions", "Support operators", "Extensible"], "key_classes": ["Expression", "TerminalExpression", "OrExpression", "AndExpression"], "methods": ["interpret(context)"], "patterns": ["Interpreter"], "complexity": {"interpret": "O(n)"}},
    {"id": "LLD-301", "title": "Implement Visitor Pattern", "difficulty": "medium", "category": "lld", "subcategory": "Design Patterns", "statement": "Implement a visitor pattern for operations on object structures.", "requirements": ["Add operations without modifying classes", "Multiple operations", "Traverse structure"], "key_classes": ["Visitor", "Element", "ConcreteElement"], "methods": ["visit(element)"], "patterns": ["Visitor"], "complexity": {"visit": "O(n)"}},
    {"id": "LLD-302", "title": "Implement Object Pool Pattern", "difficulty": "medium", "category": "lld", "subcategory": "Design Patterns", "statement": "Implement an object pool pattern for expensive object creation.", "requirements": ["Reuse objects", "Pool management", "Thread safety", "Configurable size"], "key_classes": ["ObjectPool", "Poolable"], "methods": ["acquire()", "release(obj)", "size()"], "patterns": ["Object Pool"], "complexity": {"acquire": "O(1)"}},

    # More OOP Design (15)
    {"id": "LLD-310", "title": "Design a Survey System", "difficulty": "medium", "category": "lld", "subcategory": "OOP Design", "statement": "Design a survey creation and response system.", "requirements": ["Create surveys", "Add questions", "Collect responses", "Analyze results", "Export data"], "key_classes": ["Survey", "Question", "Response", "Analytics"], "methods": ["createSurvey()", "addQuestion(survey, question)", "submitResponse(response)", "analyzeResults(survey)"], "complexity": {"analyze": "O(n)"}},
    {"id": "LLD-311", "title": "Design a Calendar System", "difficulty": "medium", "category": "lld", "subcategory": "OOP Design", "statement": "Design a calendar system for scheduling events.", "requirements": ["Add events", "Check availability", "Recurring events", "Reminders", "Multiple calendars"], "key_classes": ["Calendar", "Event", "Reminder"], "methods": ["addEvent(event)", "checkAvailability(date)", "getEvents(date)"], "complexity": {"addEvent": "O(log n)", "checkAvailability": "O(1)"}},
    {"id": "LLD-312", "title": "Design a Quiz Application", "difficulty": "medium", "category": "lld", "subcategory": "OOP Design", "statement": "Design a quiz application with scoring and timing.", "requirements": ["Create quizzes", "Timer per question", "Score tracking", "Leaderboard", "Multiple categories"], "key_classes": ["Quiz", "Question", "Answer", "Score"], "methods": ["createQuiz(questions)", "submitAnswer(answer)", "getScore()", "getLeaderboard()"], "complexity": {"submitAnswer": "O(1)"}},
    {"id": "LLD-313", "title": "Design a Recipe Sharing App", "difficulty": "medium", "category": "lld", "subcategory": "OOP Design", "statement": "Design a recipe sharing application.", "requirements": ["Create recipes", "Rate recipes", "Save favorites", "Search by ingredient", "Meal planning"], "key_classes": ["Recipe", "Ingredient", "User", "Rating"], "methods": ["addRecipe(recipe)", "rateRecipe(recipe, rating)", "searchByIngredient(ingredient)"], "complexity": {"search": "O(n)"}},
    {"id": "LLD-314", "title": "Design a Expense Tracker", "difficulty": "easy", "category": "lld", "subcategory": "OOP Design", "statement": "Design an expense tracking application.", "requirements": ["Add expenses", "Categorize expenses", "Generate reports", "Budget limits"], "key_classes": ["ExpenseTracker", "Expense", "Category", "Report"], "methods": ["addExpense(expense)", "getReport(dateRange)", "setBudget(category, limit)"], "complexity": {"addExpense": "O(1)", "getReport": "O(n)"}},

    # More Algorithm Design (15)
    {"id": "LLD-320", "title": "Design a Randomized Queue", "difficulty": "medium", "category": "lld", "subcategory": "Algorithm Design", "statement": "Design a queue that returns elements in random order.", "requirements": ["Enqueue/Dequeue", "Random dequeue", "Iterator support"], "key_classes": ["RandomizedQueue"], "methods": ["enqueue(item)", "dequeue()", "sample()", "iterator()"], "complexity": {"enqueue": "O(1)", "dequeue": "O(n)"}},
    {"id": "LLD-321", "title": "Design a Deque", "difficulty": "medium", "category": "lld", "subcategory": "Algorithm Design", "statement": "Design a double-ended queue.", "requirements": ["Add/remove from both ends", "Peek front/rear", "O(1) operations"], "key_classes": ["Deque"], "methods": ["addFront(item)", "addRear(item)", "removeFront()", "removeRear()", "peekFront()", "peekRear()"], "complexity": {"all": "O(1)"}},
    {"id": "LLD-322", "title": "Design a Monotonic Queue", "difficulty": "medium", "category": "lld", "subcategory": "Algorithm Design", "statement": "Design a monotonic queue for sliding window problems.", "requirements": ["Maintain sorted order", "Push/Pop in O(1) amortized", "Get max/min"], "key_classes": ["MonotonicQueue"], "methods": ["push(val)", "pop(val)", "max()"], "complexity": {"all": "O(1) amortized"}},
    {"id": "LLD-323", "title": "Design a Trie with Delete", "difficulty": "medium", "category": "lld", "subcategory": "Algorithm Design", "statement": "Design a trie that supports insert, search, startsWith, and delete.", "requirements": ["Insert word", "Search word", "Check prefix", "Delete word"], "key_classes": ["TrieNode", "Trie"], "methods": ["insert(word)", "search(word)", "startsWith(prefix)", "delete(word)"], "complexity": {"all": "O(m)"}},
    {"id": "LLD-324", "title": "Design a Word Search Board", "difficulty": "medium", "category": "lld", "subcategory": "Algorithm Design", "statement": "Design a word search board for finding words in a 2D grid.", "requirements": ["Search for words", "Handle all directions", "Reuse cells"], "key_classes": ["WordSearch", "Board"], "methods": ["search(word)", "exist(word)"], "complexity": {"search": "O(m*n*4^L)"}},

    # More Concurrency (15)
    {"id": "LLD-330", "title": "Implement a Delay Queue", "difficulty": "medium", "category": "lld", "subcategory": "Concurrency", "statement": "Implement a delay queue that processes items after a specified delay.", "requirements": ["Add items with delay", "Process when ready", "Thread-safe", "Priority by time"], "key_classes": ["DelayQueue", "DelayElement"], "methods": ["put(item, delay)", "take()"], "complexity": {"put": "O(log n)", "take": "O(log n)"}},
    {"id": "LLD-331", "title": "Implement a Priority Blocking Queue", "difficulty": "medium", "category": "lld", "subcategory": "Concurrency", "statement": "Implement a thread-safe priority queue.", "requirements": ["Thread-safe operations", "Priority ordering", "Blocking when empty"], "key_classes": ["PriorityBlockingQueue"], "methods": ["put(item)", "take()", "peek()"], "complexity": {"put": "O(log n)", "take": "O(log n)"}},
    {"id": "LLD-332", "title": "Implement a Concurrent Skip List", "difficulty": "hard", "category": "lld", "subcategory": "Concurrency", "statement": "Design a concurrent skip list for thread-safe operations.", "requirements": ["Thread-safe insert/delete/search", "Concurrent access", "Lock-free where possible"], "key_classes": ["ConcurrentSkipList"], "methods": ["put(key, val)", "get(key)", "remove(key)"], "complexity": {"all": "O(log n)"}},
    {"id": "LLD-333", "title": "Implement a Work Stealing Queue", "difficulty": "hard", "category": "lld", "subcategory": "Concurrency", "statement": "Design a work stealing queue for thread pool task distribution.", "requirements": ["Push/Pop from both ends", "Work stealing between threads", "Load balancing"], "key_classes": ["WorkStealingQueue"], "methods": ["push(item)", "pop()", "steal()"], "complexity": {"push": "O(1)", "pop": "O(1)", "steal": "O(1)"}},
    {"id": "LLD-334", "title": "Implement a Fork-Join Pool", "difficulty": "hard", "category": "lld", "subcategory": "Concurrency", "statement": "Design a fork-join pool for parallel divide-and-conquer tasks.", "requirements": ["Fork tasks", "Join results", "Work stealing", "Recursive decomposition"], "key_classes": ["ForkJoinPool", "ForkJoinTask"], "methods": ["invoke(task)", "execute(task)"], "complexity": {"invoke": "O(n/p)"}},

    # More API Design (15)
    {"id": "LLD-340", "title": "Design API for Content Management System", "difficulty": "medium", "category": "lld", "subcategory": "API Design", "statement": "Design REST APIs for a CMS.", "requirements": ["CRUD for content", "Media management", "Versioning", "Publishing workflow"], "key_endpoints": ["POST /content", "PUT /content/:id", "POST /media/upload", "PUT /content/:id/publish"], "complexity": {"CRUD": "O(1)"}},
    {"id": "LLD-341", "title": "Design API for Survey Platform", "difficulty": "medium", "category": "lld", "subcategory": "API Design", "statement": "Design APIs for a survey platform.", "requirements": ["Create surveys", "Collect responses", "Analytics", "Export"], "key_endpoints": ["POST /surveys", "POST /surveys/:id/responses", "GET /surveys/:id/analytics", "GET /surveys/:id/export"], "complexity": {"analytics": "O(n)"}},
    {"id": "LLD-342", "title": "Design API for Real-Time Chat", "difficulty": "hard", "category": "lld", "subcategory": "API Design", "statement": "Design APIs for a real-time chat system.", "requirements": ["Send messages", "Get messages", "WebSocket for real-time", "File sharing"], "key_endpoints": ["POST /messages", "GET /conversations/:id/messages", "WebSocket /chat/:id", "POST /files/upload"], "complexity": {"sendMessage": "O(1)"}},
    {"id": "LLD-343", "title": "Design API for E-commerce Platform", "difficulty": "hard", "category": "lld", "subcategory": "API Design", "statement": "Design comprehensive APIs for an e-commerce platform.", "requirements": ["Products", "Cart", "Orders", "Payments", "Reviews", "Search"], "key_endpoints": ["GET /products", "POST /cart", "POST /orders", "POST /payments", "POST /reviews", "GET /search"], "complexity": {"search": "O(log n)"}},
    {"id": "LLD-344", "title": "Design API for Social Network", "difficulty": "hard", "category": "lld", "subcategory": "API Design", "statement": "Design APIs for a social networking platform.", "requirements": ["Profiles", "Posts", "Follow/Unfollow", "Feed", "Notifications"], "key_endpoints": ["GET /profiles/:id", "POST /posts", "POST /follow/:id", "GET /feed/:id", "GET /notifications"], "complexity": {"feed": "O(followers)"}},

    # More Database Design (15)
    {"id": "LLD-350", "title": "Design Database for Project Management", "difficulty": "medium", "category": "lld", "subcategory": "Database Design", "statement": "Design the database schema for a project management system.", "requirements": ["Projects", "Tasks", "Users", "Assignments", "Deadlines"], "key_tables": ["projects", "tasks", "users", "assignments", "comments"], "relationships": ["projects has many tasks", "tasks has many assignments"]},
    {"id": "LLD-351", "title": "Design Database for Event Management", "difficulty": "medium", "category": "lld", "subcategory": "Database Design", "statement": "Design the database schema for an event management system.", "requirements": ["Events", "Venues", "Tickets", "Attendees", "Payments"], "key_tables": ["events", "venues", "tickets", "attendees", "payments"], "relationships": ["events has many tickets", "attendees has many tickets"]},
    {"id": "LLD-352", "title": "Design Database for Fitness App", "difficulty": "medium", "category": "lld", "subcategory": "Database Design", "statement": "Design the database schema for a fitness tracking app.", "requirements": ["Users", "Workouts", "Exercises", "Progress", "Goals"], "key_tables": ["users", "workouts", "exercises", "progress", "goals"], "relationships": ["users has many workouts", "workouts has many exercises"]},
    {"id": "LLD-353", "title": "Design Database for Quiz Platform", "difficulty": "medium", "category": "lld", "subcategory": "Database Design", "statement": "Design the database schema for a quiz platform.", "requirements": ["Quizzes", "Questions", "Answers", "Users", "Scores"], "key_tables": ["quizzes", "questions", "answers", "users", "scores"], "relationships": ["quizzes has many questions", "questions has many answers"]},
    {"id": "LLD-354", "title": "Design Database for Booking System", "difficulty": "medium", "category": "lld", "subcategory": "Database Design", "statement": "Design the database schema for a general booking system.", "requirements": ["Resources", "Bookings", "Users", "Time Slots", "Payments"], "key_tables": ["resources", "bookings", "users", "time_slots", "payments"], "relationships": ["resources has many bookings", "users has many bookings"]},
]
