"""
LLD Problems Batch 2 — Additional low-level design problems.
More OOP, data structures, and algorithm design problems.
"""

LLD_BATCH2 = [
    # More Data Structures (20)
    {"id": "LLD-070", "title": "Design a Hash Map", "difficulty": "medium", "category": "lld", "subcategory": "Data Structures", "statement": "Design a hash map with put, get, and remove operations.", "requirements": ["Put key-value pair", "Get value by key", "Remove key", "Handle collisions", "Resize when needed"], "key_classes": ["HashMap", "Entry"], "methods": ["put(key, val)", "get(key)", "remove(key)"], "complexity": {"average": "O(1)", "worst": "O(n)"}},
    {"id": "LLD-071", "title": "Design a Doubly Linked List", "difficulty": "medium", "category": "lld", "subcategory": "Data Structures", "statement": "Design a doubly linked list with insert, delete, and search.", "requirements": ["Insert at head/tail", "Delete by value", "Search", "Traverse forward/backward"], "key_classes": ["DNode", "DoublyLinkedList"], "methods": ["insert(val)", "delete(val)", "search(val)", "traverse()"], "complexity": {"insert": "O(1) head", "delete": "O(n)"}},
    {"id": "LLD-072", "title": "Design a Circular Queue", "difficulty": "medium", "category": "lld", "subcategory": "Data Structures", "statement": "Design a circular queue with fixed size.", "requirements": ["Enqueue/Dequeue in O(1)", "Check if full/empty", "Peek front/rear"], "key_classes": ["CircularQueue"], "methods": ["enqueue(val)", "dequeue()", "peek()", "isFull()", "isEmpty()"], "complexity": {"all": "O(1)"}},
    {"id": "LLD-073", "title": "Design an Iterator for Binary Tree", "difficulty": "medium", "category": "lld", "subcategory": "Data Structures", "statement": "Design an iterator for in-order traversal of a BST.", "requirements": ["next() returns next element", "hasNext() checks if more elements", "O(1) amortized next()", "O(h) space"], "key_classes": ["BSTIterator"], "methods": ["next()", "hasNext()"], "complexity": {"next": "O(1) amortized", "hasNext": "O(1)"}},
    {"id": "LLD-074", "title": "Design a Priority Queue", "difficulty": "medium", "category": "lld", "subcategory": "Data Structures", "statement": "Design a priority queue (max-heap based).", "requirements": ["Insert with priority", "Extract max", "Peek max", "Decrease key"], "key_classes": ["PriorityQueue"], "methods": ["insert(val, priority)", "extractMax()", "peek()", "decreaseKey(val, newPriority)"], "complexity": {"insert": "O(log n)", "extractMax": "O(log n)"}},

    # More Design Patterns (20)
    {"id": "LLD-080", "title": "Implement Adapter Pattern", "difficulty": "medium", "category": "lld", "subcategory": "Design Patterns", "statement": "Implement an adapter pattern to convert one interface to another.", "requirements": ["Convert interface A to B", "No modification to original classes", "Transparent to client"], "key_classes": ["Target", "Adapter", "Adaptee"], "methods": ["request()"], "patterns": ["Adapter"], "complexity": {"request": "O(1)"}},
    {"id": "LLD-081", "title": "Implement Proxy Pattern", "difficulty": "medium", "category": "lld", "subcategory": "Design Patterns", "statement": "Implement a proxy pattern for lazy loading or access control.", "requirements": ["Control access to real object", "Lazy initialization", "Logging/caching"], "key_classes": ["Subject", "Proxy", "RealSubject"], "methods": ["request()"], "patterns": ["Proxy"], "complexity": {"request": "O(1)"}},
    {"id": "LLD-082", "title": "Implement Composite Pattern", "difficulty": "medium", "category": "lld", "subcategory": "Design Patterns", "statement": "Implement a composite pattern for tree structures.", "requirements": ["Treat individual and composite objects uniformly", "Add/remove children", "Perform operations on tree"], "key_classes": ["Component", "Leaf", "Composite"], "methods": ["operation()", "add(child)", "remove(child)"], "patterns": ["Composite"], "complexity": {"operation": "O(n)"}},

    # More OOP Design (20)
    {"id": "LLD-090", "title": "Design a ATM Machine", "difficulty": "medium", "category": "lld", "subcategory": "OOP Design", "statement": "Design an ATM machine system.", "requirements": ["Authenticate user", "Check balance", "Withdraw/Deposit", "Multiple accounts", "Transaction history"], "key_classes": ["ATM", "Card", "Account", "Transaction"], "methods": ["authenticate(card, pin)", "checkBalance()", "withdraw(amount)", "deposit(amount)"], "complexity": {"all": "O(1)"}},
    {"id": "LLD-091", "title": "Design a Chess Game", "difficulty": "hard", "category": "lld", "subcategory": "OOP Design", "statement": "Design the object model for a chess game.", "requirements": ["Board representation", "Piece classes", "Move validation", "Game state", "Player turns"], "key_classes": ["Board", "Piece", "King", "Queen", "Rook", "Bishop", "Knight", "Pawn"], "methods": ["move(from, to)", "isValidMove()", "isCheck()", "isCheckmate()"], "complexity": {"move": "O(1)"}},
    {"id": "LLD-092", "title": "Design a Car Rental System", "difficulty": "medium", "category": "lld", "subcategory": "OOP Design", "statement": "Design a car rental system.", "requirements": ["Search available cars", "Book/return cars", "Pricing", "Customer management", "Vehicle types"], "key_classes": ["RentalSystem", "Vehicle", "Customer", "Reservation"], "methods": ["searchVehicles(date)", "bookVehicle(vehicle, customer)", "returnVehicle(reservation)"], "complexity": {"search": "O(n)"}},
    {"id": "LLD-093", "title": "Design a Movie Ticket Booking", "difficulty": "medium", "category": "lld", "subcategory": "OOP Design", "statement": "Design a movie ticket booking system.", "requirements": ["Show listings", "Seat selection", "Booking", "Payment", "Multiple screens"], "key_classes": ["Cinema", "Screen", "Seat", "Booking", "Show"], "methods": ["getShows(movie)", "selectSeat(seat)", "bookTicket()"], "complexity": {"selectSeat": "O(1)"}},
    {"id": "LLD-094", "title": "Design a Traffic Light Controller", "difficulty": "medium", "category": "lld", "subcategory": "OOP Design", "statement": "Design a traffic light controller system.", "requirements": ["Cycle through colors", "Timer management", "Emergency override", "Multiple intersections"], "key_classes": ["TrafficLight", "Intersection", "Timer"], "methods": ["changeLight()", "startCycle()", "emergencyStop()"], "complexity": {"changeLight": "O(1)"}},

    # More Algorithm Design (20)
    {"id": "LLD-100", "title": "Design an Autocomplete System", "difficulty": "medium", "category": "lld", "subcategory": "Algorithm Design", "statement": "Design an autocomplete system that returns top K suggestions.", "requirements": ["Add sentences", "Search by prefix", "Return top K results", "Rank by frequency"], "key_classes": ["AutocompleteSystem", "TrieNode"], "methods": ["input(char)", "search(prefix)"], "complexity": {"search": "O(p + k)"}},
    {"id": "LLD-101", "title": "Design a Word Dictionary", "difficulty": "medium", "category": "lld", "subcategory": "Algorithm Design", "statement": "Design a dictionary that supports wildcard matching with '.' character.", "requirements": ["Add word", "Search word with wildcards", "Support '.' as any character"], "key_classes": ["WordDictionary", "TrieNode"], "methods": ["addWord(word)", "search(word)"], "complexity": {"search": "O(26^m)"}},
    {"id": "LLD-102", "title": "Design a Min Stack", "difficulty": "medium", "category": "lld", "subcategory": "Algorithm Design", "statement": "Design a stack that supports push, pop, top, and retrieving the minimum element in O(1).", "requirements": ["Push/Pop/Top in O(1)", "GetMin in O(1)", "Handle negative numbers"], "key_classes": ["MinStack"], "methods": ["push(val)", "pop()", "top()", "getMin()"], "complexity": {"all": "O(1)"}},
    {"id": "LLD-103", "title": "Design a Task Scheduler", "difficulty": "medium", "category": "lld", "subcategory": "Algorithm Design", "statement": "Design a task scheduler that executes tasks with cooldown periods.", "requirements": ["Schedule tasks", "Execute with cooldown", "Handle priorities", "Pause/resume"], "key_classes": ["TaskScheduler", "Task", "Worker"], "methods": ["schedule(task, cooldown)", "execute()", "pause()", "resume()"], "complexity": {"schedule": "O(log n)", "execute": "O(1)"}},

    # More Concurrency (20)
    {"id": "LLD-110", "title": "Implement Blocking Queue", "difficulty": "medium", "category": "lld", "subcategory": "Concurrency", "statement": "Implement a blocking queue that blocks when full or empty.", "requirements": ["Blocking put when full", "Blocking get when empty", "Thread-safe", "Support timeout"], "key_classes": ["BlockingQueue"], "methods": ["put(item, timeout)", "get(timeout)"], "complexity": {"all": "O(1)"}},
    {"id": "LLD-111", "title": "Implement a Semaphore", "difficulty": "medium", "category": "lld", "subcategory": "Concurrency", "statement": "Implement a counting semaphore for resource management.", "requirements": ["Acquire/Release permits", "Fair/unfair scheduling", "Support timeout"], "key_classes": ["Semaphore"], "methods": ["acquire(timeout)", "release()"], "complexity": {"all": "O(1)"}},

    # More API Design (20)
    {"id": "LLD-120", "title": "Design API for Ride-Sharing", "difficulty": "hard", "category": "lld", "subcategory": "API Design", "statement": "Design REST APIs for a ride-sharing platform.", "requirements": ["Request ride", "Track driver", "Complete ride", "Rate driver", "Payment"], "key_endpoints": ["POST /rides", "GET /rides/:id", "PUT /rides/:id/complete", "POST /rides/:id/rate"], "complexity": {"all": "O(1)"}},
    {"id": "LLD-121", "title": "Design API for File Sharing", "difficulty": "medium", "category": "lld", "subcategory": "API Design", "statement": "Design APIs for a file sharing platform.", "requirements": ["Upload files", "Download files", "Share with users", "Folder management"], "key_endpoints": ["POST /files/upload", "GET /files/:id/download", "POST /files/:id/share", "GET /folders/:id"], "complexity": {"upload": "O(size)", "download": "O(1)"}},

    # More Database Design (20)
    {"id": "LLD-130", "title": "Design Database for Hospital", "difficulty": "medium", "category": "lld", "subcategory": "Database Design", "statement": "Design the database schema for a hospital management system.", "requirements": ["Patients", "Doctors", "Appointments", "Medical records", "Billing"], "key_tables": ["patients", "doctors", "appointments", "medical_records", "billing"], "relationships": ["patients has many appointments", "doctors has many appointments"]},
    {"id": "LLD-131", "title": "Design Database for Banking", "difficulty": "hard", "category": "lld", "subcategory": "Database Design", "statement": "Design the database schema for a banking system.", "requirements": ["Accounts", "Transactions", "Customers", "Cards", "Loans"], "key_tables": ["accounts", "transactions", "customers", "cards", "loans"], "relationships": ["customers has many accounts", "accounts has many transactions"]},

    # More Algorithm Design (20)
    {"id": "LLD-140", "title": "Design a LFU Cache", "difficulty": "hard", "category": "lld", "subcategory": "Algorithm Design", "statement": "Design an LFU cache with O(1) operations.", "requirements": ["Get/Put in O(1)", "Evict least frequently used", "Handle frequency ties"], "key_classes": ["LFUCache"], "methods": ["get(key)", "put(key, value)"], "complexity": {"all": "O(1)"}},
    {"id": "LLD-141", "title": "Design a Data Stream Median", "difficulty": "hard", "category": "lld", "subcategory": "Algorithm Design", "statement": "Design a data structure that supports adding numbers and finding the median.", "requirements": ["Add number in O(log n)", "Get median in O(1)", "Handle stream of numbers"], "key_classes": ["MedianFinder"], "methods": ["addNum(num)", "findMedian()"], "complexity": {"addNum": "O(log n)", "findMedian": "O(1)"}},
    {"id": "LLD-142", "title": "Design a Random Pick with Weight", "difficulty": "medium", "category": "lld", "subcategory": "Algorithm Design", "statement": "Design a system to pick random index based on weights.", "requirements": ["Initialize with weights", "Pick random index proportional to weight"], "key_classes": ["Solution"], "methods": ["pickIndex()"], "complexity": {"pickIndex": "O(log n)"}},
]
