"""
Low-Level Design (LLD) Problems — 200+ object-oriented design problems.
Covers design patterns, class design, and API design.
"""

LLD_PROBLEMS = [
    # ═══════════════════════════════════════════════════════════════════════════
    # DATA STRUCTURES & ALGORITHMS DESIGN (30 problems)
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "LLD-001", "title": "Design a Linked List", "difficulty": "easy", "category": "lld", "subcategory": "Data Structures", "statement": "Design a singly linked list with insert, delete, and search operations.", "requirements": ["Insert at head/tail/position", "Delete by value/position", "Search by value", "Get size", "Reverse"], "key_classes": ["Node", "LinkedList"], "methods": ["insert(val)", "delete(val)", "search(val)", "reverse()", "size()"], "complexity": {"insert": "O(1) head, O(n) tail", "delete": "O(n)", "search": "O(n)"}},
    {"id": "LLD-002", "title": "Design a Stack", "difficulty": "easy", "category": "lld", "subcategory": "Data Structures", "statement": "Design a stack with push, pop, top, and getMin operations.", "requirements": ["Push element", "Pop element", "Get top element", "Get minimum element", "All O(1)"], "key_classes": ["Stack", "MinStack"], "methods": ["push(val)", "pop()", "top()", "getMin()"], "complexity": {"all": "O(1)"}},
    {"id": "LLD-003", "title": "Design a Queue", "difficulty": "easy", "category": "lld", "subcategory": "Data Structures", "statement": "Design a queue with enqueue, dequeue, and peek operations.", "requirements": ["Enqueue element", "Dequeue element", "Peek front", "Check empty", "Get size"], "key_classes": ["Queue"], "methods": ["enqueue(val)", "dequeue()", "peek()", "isEmpty()"], "complexity": {"all": "O(1)"}},
    {"id": "LLD-004", "title": "Design an LRU Cache", "difficulty": "medium", "category": "lld", "subcategory": "Data Structures", "statement": "Design an LRU cache with O(1) get and put operations.", "requirements": ["Get(key) returns value or -1", "Put(key, value) inserts/updates", "Evicts least recently used when full", "All O(1)"], "key_classes": ["LRUCache", "Node"], "methods": ["get(key)", "put(key, value)"], "complexity": {"all": "O(1)"}},
    {"id": "LLD-005", "title": "Design a Trie (Prefix Tree)", "difficulty": "medium", "category": "lld", "subcategory": "Data Structures", "statement": "Design a trie with insert, search, and startsWith operations.", "requirements": ["Insert word", "Search exact word", "Check prefix exists", "Delete word"], "key_classes": ["TrieNode", "Trie"], "methods": ["insert(word)", "search(word)", "startsWith(prefix)", "delete(word)"], "complexity": {"all": "O(m) where m = word length"}},
    {"id": "LLD-006", "title": "Design a Binary Search Tree", "difficulty": "medium", "category": "lld", "subcategory": "Data Structures", "statement": "Design a BST with insert, delete, search, and inorder traversal.", "requirements": ["Insert node", "Delete node", "Search value", "Inorder traversal", "Find min/max"], "key_classes": ["TreeNode", "BST"], "methods": ["insert(val)", "delete(val)", "search(val)", "inorder()", "findMin()"], "complexity": {"average": "O(log n)", "worst": "O(n)"}},
    {"id": "LLD-007", "title": "Design a Min Heap", "difficulty": "medium", "category": "lld", "subcategory": "Data Structures", "statement": "Design a min-heap with insert, extractMin, and peek operations.", "requirements": ["Insert element", "Extract minimum", "Peek minimum", "Heapify", "All O(log n)"], "key_classes": ["MinHeap"], "methods": ["insert(val)", "extractMin()", "peek()", "heapify()"], "complexity": {"insert": "O(log n)", "extractMin": "O(log n)"}},
    {"id": "LLD-008", "title": "Design a Graph", "difficulty": "medium", "category": "lld", "subcategory": "Data Structures", "statement": "Design a graph with BFS, DFS, and shortest path operations.", "requirements": ["Add vertex/edge", "BFS traversal", "DFS traversal", "Shortest path", "Cycle detection"], "key_classes": ["Graph", "Vertex", "Edge"], "methods": ["addVertex(v)", "addEdge(v1,v2)", "bfs(start)", "dfs(start)", "shortestPath(s,d)"], "complexity": {"bfs/dfs": "O(V+E)", "shortestPath": "O(V²)"}},

    # ═══════════════════════════════════════════════════════════════════════════
    # DESIGN PATTERNS (30 problems)
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "LLD-010", "title": "Implement Singleton Pattern", "difficulty": "easy", "category": "lld", "subcategory": "Design Patterns", "statement": "Implement a thread-safe singleton pattern.", "requirements": ["Single instance", "Thread-safe", "Lazy initialization", "Global access"], "key_classes": ["Singleton"], "methods": ["getInstance()"], "patterns": ["Singleton"], "complexity": {"getInstance": "O(1)"}},
    {"id": "LLD-011", "title": "Implement Factory Pattern", "difficulty": "medium", "category": "lld", "subcategory": "Design Patterns", "statement": "Implement a factory pattern for creating different types of objects.", "requirements": ["Create objects without specifying class", "Support multiple types", "Easy to add new types"], "key_classes": ["Factory", "Product", "ConcreteProduct"], "methods": ["create(type)"], "patterns": ["Factory"], "complexity": {"create": "O(1)"}},
    {"id": "LLD-012", "title": "Implement Observer Pattern", "difficulty": "medium", "category": "lld", "subcategory": "Design Patterns", "statement": "Implement an observer pattern for event notification.", "requirements": ["Subscribe to events", "Unsubscribe", "Notify all observers", "Support multiple event types"], "key_classes": ["Subject", "Observer", "ConcreteObserver"], "methods": ["subscribe(event, observer)", "unsubscribe(event, observer)", "notify(event)"], "patterns": ["Observer"], "complexity": {"notify": "O(n)"}},
    {"id": "LLD-013", "title": "Implement Strategy Pattern", "difficulty": "medium", "category": "lld", "subcategory": "Design Patterns", "statement": "Implement a strategy pattern for interchangeable algorithms.", "requirements": ["Define algorithm interface", "Support multiple strategies", "Switch strategies at runtime"], "key_classes": ["Strategy", "ConcreteStrategy", "Context"], "methods": ["setStrategy(strategy)", "executeStrategy()"], "patterns": ["Strategy"], "complexity": {"execute": "O(1)"}},
    {"id": "LLD-014", "title": "Implement Decorator Pattern", "difficulty": "medium", "category": "lld", "subcategory": "Design Patterns", "statement": "Implement a decorator pattern for adding behavior dynamically.", "requirements": ["Wrap objects dynamically", "Add behavior without modifying original", "Stack decorators"], "key_classes": ["Component", "ConcreteComponent", "Decorator"], "methods": ["operation()"], "patterns": ["Decorator"], "complexity": {"operation": "O(1)"}},
    {"id": "LLD-015", "title": "Implement Command Pattern", "difficulty": "medium", "category": "lld", "subcategory": "Design Patterns", "statement": "Implement a command pattern for undo/redo functionality.", "requirements": ["Encapsulate operations", "Support undo/redo", "Queue commands", "Macro commands"], "key_classes": ["Command", "ConcreteCommand", "Invoker", "Receiver"], "methods": ["execute()", "undo()", "redo()"], "patterns": ["Command"], "complexity": {"execute": "O(1)"}},

    # ═══════════════════════════════════════════════════════════════════════════
    # OOP DESIGN (30 problems)
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "LLD-020", "title": "Design a Vending Machine", "difficulty": "medium", "category": "lld", "subcategory": "OOP Design", "statement": "Design a vending machine that dispenses products.", "requirements": ["Select product", "Insert coins", "Dispense product", "Return change", "Inventory management"], "key_classes": ["VendingMachine", "Product", "Coin", "Slot"], "methods": ["selectProduct(id)", "insertCoin(coin)", "dispense()", "getChange()"], "complexity": {"all": "O(1)"}},
    {"id": "LLD-021", "title": "Design an Elevator System", "difficulty": "hard", "category": "lld", "subcategory": "OOP Design", "statement": "Design an elevator system for a multi-floor building.", "requirements": ["Multiple elevators", "Floor requests", "Direction tracking", "Priority handling", "Emergency mode"], "key_classes": ["ElevatorSystem", "Elevator", "Floor", "Request"], "methods": ["requestElevator(floor, direction)", "getElevator(floor)"], "complexity": {"request": "O(log n)"}},
    {"id": "LLD-022", "title": "Design a Library Management System", "difficulty": "medium", "category": "lld", "subcategory": "OOP Design", "statement": "Design a library system with book management and borrowing.", "requirements": ["Add/remove books", "Borrow/return books", "Search books", "Member management", "Fine calculation"], "key_classes": ["Library", "Book", "Member", "Loan"], "methods": ["addBook(book)", "borrowBook(member, book)", "returnBook(member, book)"], "complexity": {"borrow": "O(1)", "search": "O(n)"}},
    {"id": "LLD-023", "title": "Design a Hotel Booking System", "difficulty": "medium", "category": "lld", "subcategory": "OOP Design", "statement": "Design a hotel booking system with room management.", "requirements": ["Search available rooms", "Book rooms", "Cancel bookings", "Room types", "Pricing"], "key_classes": ["Hotel", "Room", "Booking", "Guest"], "methods": ["searchRooms(date, type)", "bookRoom(room, guest, dates)", "cancelBooking(id)"], "complexity": {"search": "O(n)"}},
    {"id": "LLD-024", "title": "Design a Snake and Ladder Game", "difficulty": "medium", "category": "lld", "subcategory": "OOP Design", "statement": "Design the Snake and Ladder board game.", "requirements": ["Board with snakes/ladders", "Dice rolling", "Player movement", "Win condition", "Multiple players"], "key_classes": ["Game", "Board", "Player", "Cell"], "methods": ["rollDice()", "movePlayer(player)", "checkWin(player)"], "complexity": {"move": "O(1)"}},
    {"id": "LLD-025", "title": "Design a Tic-Tac-Toe Game", "difficulty": "easy", "category": "lld", "subcategory": "OOP Design", "statement": "Design a Tic-Tac-Toe game.", "requirements": ["Make moves", "Check winner", "Check draw", "Reset game", "Multiple players"], "key_classes": ["Game", "Board", "Player"], "methods": ["makeMove(player, row, col)", "checkWinner()", "isDraw()", "reset()"], "complexity": {"move": "O(1)"}},

    # ═══════════════════════════════════════════════════════════════════════════
    # API DESIGN (20 problems)
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "LLD-030", "title": "Design REST API for Blog Platform", "difficulty": "medium", "category": "lld", "subcategory": "API Design", "statement": "Design RESTful APIs for a blog platform.", "requirements": ["CRUD for posts", "User authentication", "Comments", "Likes", "Pagination"], "key_endpoints": ["GET /posts", "POST /posts", "GET /posts/:id", "PUT /posts/:id", "DELETE /posts/:id", "POST /posts/:id/comments"], "complexity": {"CRUD": "O(1)", "search": "O(n)"}},
    {"id": "LLD-031", "title": "Design API for Social Network", "difficulty": "hard", "category": "lld", "subcategory": "API Design", "statement": "Design APIs for a social networking platform.", "requirements": ["User profiles", "Posts", "Follow/unfollow", "News feed", "Notifications"], "key_endpoints": ["POST /users", "GET /users/:id", "POST /posts", "POST /users/:id/follow", "GET /feed/:userId"], "complexity": {"feed": "O(followers)"}},

    # ═══════════════════════════════════════════════════════════════════════════
    # DATABASE DESIGN (20 problems)
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "LLD-040", "title": "Design Database for E-commerce", "difficulty": "medium", "category": "lld", "subcategory": "Database Design", "statement": "Design the database schema for an e-commerce platform.", "requirements": ["Users table", "Products table", "Orders table", "Order items", "Payments", "Reviews"], "key_tables": ["users", "products", "orders", "order_items", "payments", "reviews"], "relationships": ["users has many orders", "orders has many order_items", "products has many reviews"]},
    {"id": "LLD-041", "title": "Design Database for Social Network", "difficulty": "hard", "category": "lld", "subcategory": "Database Design", "statement": "Design the database schema for a social network.", "requirements": ["Users", "Posts", "Friendships", "Likes", "Comments", "Messages"], "key_tables": ["users", "posts", "friendships", "likes", "comments", "messages"], "relationships": ["users has many posts", "users has many friendships", "posts has many comments"]},

    # ═══════════════════════════════════════════════════════════════════════════
    # ALGORITHM DESIGN (20 problems)
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "LLD-050", "title": "Design a Randomized Set", "difficulty": "medium", "category": "lld", "subcategory": "Algorithm Design", "statement": "Design a set that supports insert, remove, and getRandom in O(1).", "requirements": ["Insert element", "Remove element", "Get random element", "All O(1)"], "key_classes": ["RandomizedSet"], "methods": ["insert(val)", "remove(val)", "getRandom()"], "complexity": {"all": "O(1)"}},
    {"id": "LLD-051", "title": "Design a Parking System", "difficulty": "easy", "category": "lld", "subcategory": "Algorithm Design", "statement": "Design a parking system for a car park with limited slots.", "requirements": ["Add car", "Remove car", "Check availability", "Get count"], "key_classes": ["ParkingSystem"], "methods": ["addCar(carType)", "removeCar(carType)", "getCount(carType)"], "complexity": {"all": "O(1)"}},
    {"id": "LLD-052", "title": "Design a Snapshot Array", "difficulty": "medium", "category": "lld", "subcategory": "Algorithm Design", "statement": "Design a data structure that stores snapshots of an array and can retrieve values at any snapshot.", "requirements": ["Set value at index", "Take snapshot", "Get value at index in snapshot"], "key_classes": ["SnapshotArray"], "methods": ["set(index, val)", "snap()", "get(index, snap_id)"], "complexity": {"set": "O(1)", "snap": "O(1)", "get": "O(log n)"}},
    {"id": "LLD-053", "title": "Design a Stream of Characters", "difficulty": "medium", "category": "lld", "subcategory": "Algorithm Design", "statement": "Design a data structure that checks if a suffix of the stream matches any word in a dictionary.", "requirements": ["Add character to stream", "Check if any word matches suffix"], "key_classes": ["StreamChecker"], "methods": ["append(c)"], "complexity": {"append": "O(m)"}},

    # ═══════════════════════════════════════════════════════════════════════════
    # concurrency & THREADING (20 problems)
    # ═══════════════════════════════════════════════════════════════════════════
    {"id": "LLD-060", "title": "Design a Thread Pool", "difficulty": "hard", "category": "lld", "subcategory": "Concurrency", "statement": "Design a thread pool that manages a fixed number of threads.", "requirements": ["Execute tasks", "Queue management", "Thread reuse", "Graceful shutdown", "Exception handling"], "key_classes": ["ThreadPool", "Worker", "Task"], "methods": ["submit(task)", "shutdown()", "getActiveCount()"], "complexity": {"submit": "O(1)"}},
    {"id": "LLD-061", "title": "Design a Producer-Consumer Queue", "difficulty": "medium", "category": "lld", "subcategory": "Concurrency", "statement": "Design a thread-safe producer-consumer queue.", "requirements": ["Thread-safe enqueue/dequeue", "Blocking when empty/full", "Support multiple producers/consumers"], "key_classes": ["BoundedQueue"], "methods": ["put(item)", "get()"], "complexity": {"all": "O(1)"}},
    {"id": "LLD-062", "title": "Design a Read-Write Lock", "difficulty": "medium", "category": "lld", "subcategory": "Concurrency", "statement": "Design a read-write lock that allows multiple readers or one writer.", "requirements": ["Multiple concurrent readers", "Exclusive writer", "No starvation", "Fair scheduling"], "key_classes": ["ReadWriteLock"], "methods": ["readLock()", "writeLock()", "unlock()"], "complexity": {"read": "O(1)", "write": "O(1)"}},
]
