"""
LLD Extra Batch — Additional low-level design problems to reach 200+.
More OOP, data structures, and algorithm design problems.
"""

LLD_EXTRA = [
    # More Data Structures (20)
    {"id": "LLD-220", "title": "Design a Fenwick Tree", "difficulty": "hard", "category": "lld", "subcategory": "Data Structures", "statement": "Design a Fenwick tree (Binary Indexed Tree) for range queries.", "requirements": ["Point update", "Range sum query", "O(log n) operations"], "key_classes": ["FenwickTree"], "methods": ["update(i, delta)", "query(i)"], "complexity": {"all": "O(log n)"}},
    {"id": "LLD-221", "title": "Design a Segment Tree", "difficulty": "hard", "category": "lld", "subcategory": "Data Structures", "statement": "Design a segment tree for range queries and updates.", "requirements": ["Range query", "Point update", "Range update"], "key_classes": ["SegmentTree"], "methods": ["query(l, r)", "update(i, val)"], "complexity": {"query": "O(log n)", "update": "O(log n)"}},
    {"id": "LLD-222", "title": "Design a Treap", "difficulty": "hard", "category": "lld", "subcategory": "Data Structures", "statement": "Design a treap (tree + heap) for balanced BST operations.", "requirements": ["Insert/Delete/Search", "Expected O(log n)", "Random priorities"], "key_classes": ["TreapNode", "Treap"], "methods": ["insert(key)", "delete(key)", "search(key)"], "complexity": {"all": "O(log n) expected"}},
    {"id": "LLD-223", "title": "Design a AVL Tree", "difficulty": "hard", "category": "lld", "subcategory": "Data Structures", "statement": "Design an AVL tree with self-balancing rotations.", "requirements": ["Insert/Delete/Search", "Self-balancing", "O(log n) guaranteed"], "key_classes": ["AVLNode", "AVLTree"], "methods": ["insert(key)", "delete(key)", "search(key)"], "complexity": {"all": "O(log n)"}},
    {"id": "LLD-224", "title": "Design a Splay Tree", "difficulty": "hard", "category": "lld", "subcategory": "Data Structures", "statement": "Design a splay tree with amortized O(log n) operations.", "requirements": ["Splay operation", "Insert/Delete/Search", "Amortized O(log n)"], "key_classes": ["SplayNode", "SplayTree"], "methods": ["insert(key)", "delete(key)", "search(key)"], "complexity": {"amortized": "O(log n)"}},

    # More Design Patterns (15)
    {"id": "LLD-230", "title": "Implement Abstract Factory Pattern", "difficulty": "medium", "category": "lld", "subcategory": "Design Patterns", "statement": "Implement an abstract factory pattern for creating families of related objects.", "requirements": ["Create families of objects", "No specification of concrete classes", "Consistent object creation"], "key_classes": ["AbstractFactory", "ConcreteFactory", "AbstractProduct"], "methods": ["createProductA()", "createProductB()"], "patterns": ["Abstract Factory"], "complexity": {"create": "O(1)"}},
    {"id": "LLD-231", "title": "Implement Prototype Pattern", "difficulty": "medium", "category": "lld", "subcategory": "Design Patterns", "statement": "Implement a prototype pattern for cloning objects.", "requirements": ["Clone objects", "Deep copy support", "Registry of prototypes"], "key_classes": ["Prototype", "PrototypeRegistry"], "methods": ["clone()", "register(name, prototype)"], "patterns": ["Prototype"], "complexity": {"clone": "O(n)"}},
    {"id": "LLD-232", "title": "Implement Template Method Pattern", "difficulty": "medium", "category": "lld", "subcategory": "Design Patterns", "statement": "Implement a template method pattern for algorithm skeletons.", "requirements": ["Define algorithm skeleton", "Override specific steps", "Maintain structure"], "key_classes": ["TemplateMethod", "ConcreteClass"], "methods": ["templateMethod()"], "patterns": ["Template Method"], "complexity": {"templateMethod": "O(n)"}},
    {"id": "LLD-233", "title": "Implement Null Object Pattern", "difficulty": "easy", "category": "lld", "subcategory": "Design Patterns", "statement": "Implement a null object pattern to avoid null checks.", "requirements": ["Provide default behavior", "Eliminate null checks", "Consistent interface"], "key_classes": ["Object", "NullObject"], "methods": ["operation()"], "patterns": ["Null Object"], "complexity": {"operation": "O(1)"}},
    {"id": "LLD-234", "title": "Implement Memento Pattern", "difficulty": "medium", "category": "lld", "subcategory": "Design Patterns", "statement": "Implement a memento pattern for state restoration.", "requirements": ["Save state", "Restore state", "Encapsulate state"], "key_classes": ["Originator", "Memento", "Caretaker"], "methods": ["save()", "restore(memento)"], "patterns": ["Memento"], "complexity": {"save": "O(n)", "restore": "O(n)"}},

    # More OOP Design (15)
    {"id": "LLD-240", "title": "Design a Taxi Booking System", "difficulty": "medium", "category": "lld", "subcategory": "OOP Design", "statement": "Design a taxi booking system.", "requirements": ["Book taxi", "Track location", "Calculate fare", "Driver management", "Ride history"], "key_classes": ["TaxiService", "Taxi", "Rider", "Ride"], "methods": ["bookTaxi(rider, pickup, drop)", "trackRide(rideId)", "calculateFare(distance)"], "complexity": {"book": "O(log n)"}},
    {"id": "LLD-241", "title": "Design a Chat Application", "difficulty": "hard", "category": "lld", "subcategory": "OOP Design", "statement": "Design the backend for a chat application.", "requirements": ["1-on-1 chat", "Group chat", "Message history", "Online status", "Read receipts"], "key_classes": ["ChatService", "Message", "Conversation", "User"], "methods": ["sendMessage(conversationId, content)", "getMessages(conversationId)", "markRead(messageId)"], "complexity": {"sendMessage": "O(1)"}},
    {"id": "LLD-242", "title": "Design a Movie Booking System", "difficulty": "medium", "category": "lld", "subcategory": "OOP Design", "statement": "Design a movie ticket booking system.", "requirements": ["Movie listings", "Theater management", "Seat selection", "Booking", "Payment"], "key_classes": ["MovieService", "Theater", "Show", "Seat", "Booking"], "methods": ["getShows(movie)", "selectSeats(show, seats)", "bookTicket(booking)"], "complexity": {"selectSeats": "O(1)"}},
    {"id": "LLD-243", "title": "Design a File System", "difficulty": "medium", "category": "lld", "subcategory": "OOP Design", "statement": "Design an in-memory file system.", "requirements": ["Create files/directories", "List contents", "Navigate paths", "File operations"], "key_classes": ["FileSystem", "File", "Directory"], "methods": ["ls(path)", "mkdir(path)", "addContentToFile(path, content)", "readContentFromFile(path)"], "complexity": {"ls": "O(n)"}},
    {"id": "LLD-244", "title": "Design a Music Player", "difficulty": "medium", "category": "lld", "subcategory": "OOP Design", "statement": "Design a music player with playlist management.", "requirements": ["Play/Pause/Stop", "Next/Previous", "Playlist management", "Shuffle/Repeat", "Queue"], "key_classes": ["MusicPlayer", "Song", "Playlist", "Queue"], "methods": ["play(song)", "pause()", "next()", "addToPlaylist(song)"], "complexity": {"play": "O(1)"}},

    # More Algorithm Design (15)
    {"id": "LLD-250", "title": "Design a Bloom Filter", "difficulty": "medium", "category": "lld", "subcategory": "Algorithm Design", "statement": "Design a probabilistic data structure for membership queries.", "requirements": ["Add element", "Check membership", "Low false positive rate", "Space efficient"], "key_classes": ["BloomFilter"], "methods": ["add(item)", "mightContain(item)"], "complexity": {"all": "O(k) where k = number of hash functions"}},
    {"id": "LLD-251", "title": "Design a Count-Min Sketch", "difficulty": "medium", "category": "lld", "subcategory": "Algorithm Design", "statement": "Design a probabilistic data structure for frequency estimation.", "requirements": ["Count frequency", "Space efficient", "Approximate counts"], "key_classes": ["CountMinSketch"], "methods": ["add(item)", "count(item)"], "complexity": {"all": "O(k)"}},
    {"id": "LLD-252", "title": "Design a Consistent Hashing", "difficulty": "hard", "category": "lld", "subcategory": "Algorithm Design", "statement": "Design a consistent hashing ring for distributed systems.", "requirements": ["Distribute keys evenly", "Minimize rehashing", "Virtual nodes"], "key_classes": ["ConsistentHash"], "methods": ["addNode(node)", "removeNode(node)", "getNode(key)"], "complexity": {"getNode": "O(log n)"}},
    {"id": "LLD-253", "title": "Design a Rate Limiter", "difficulty": "medium", "category": "lld", "subcategory": "Algorithm Design", "statement": "Design a rate limiter with multiple algorithms.", "requirements": ["Token bucket", "Sliding window", "Fixed window", "Distributed"], "key_classes": ["RateLimiter", "TokenBucket", "SlidingWindow"], "methods": ["allow(key)", "getUsage(key)"], "complexity": {"allow": "O(1)"}},
    {"id": "LLD-254", "title": "Design a LRU Cache", "difficulty": "medium", "category": "lld", "subcategory": "Algorithm Design", "statement": "Design an LRU cache with O(1) operations.", "requirements": ["Get/Put in O(1)", "Evict LRU", "Handle collisions"], "key_classes": ["LRUCache"], "methods": ["get(key)", "put(key, value)"], "complexity": {"all": "O(1)"}},

    # More Concurrency (15)
    {"id": "LLD-260", "title": "Implement a Future/Promise", "difficulty": "medium", "category": "lld", "subcategory": "Concurrency", "statement": "Implement a future/promise for asynchronous computation.", "requirements": ["Execute async task", "Get result when ready", "Chain operations"], "key_classes": ["Future", "Promise"], "methods": ["get(timeout)", "then(callback)"], "complexity": {"get": "O(1)"}},
    {"id": "LLD-261", "title": "Implement a Countdown Latch", "difficulty": "medium", "category": "lld", "subcategory": "Concurrency", "statement": "Implement a countdown latch for synchronizing threads.", "requirements": ["Count down", "Wait for count to reach zero", "Reset count"], "key_classes": ["CountDownLatch"], "methods": ["countDown()", "await(timeout)"], "complexity": {"countDown": "O(1)", "await": "O(1)"}},
    {"id": "LLD-262", "title": "Implement a Cyclic Barrier", "difficulty": "medium", "category": "lld", "subcategory": "Concurrency", "statement": "Implement a cyclic barrier for synchronizing threads.", "requirements": ["Wait for all threads", "Reset after all arrive", "Support timeout"], "key_classes": ["CyclicBarrier"], "methods": ["await(timeout)"], "complexity": {"await": "O(1)"}},
    {"id": "LLD-263", "title": "Implement a Phaser", "difficulty": "hard", "category": "lld", "subcategory": "Concurrency", "statement": "Implement a phaser for flexible thread synchronization.", "requirements": ["Phase-based synchronization", "Dynamic party registration", "Timeout support"], "key_classes": ["Phaser"], "methods": ["arrive()", "awaitAdvance(phase)"], "complexity": {"arrive": "O(1)"}},
    {"id": "LLD-264", "title": "Implement a StampedLock", "difficulty": "hard", "category": "lld", "subcategory": "Concurrency", "statement": "Implement a stamped lock for read-write scenarios.", "requirements": ["Optimistic read", "Read lock", "Write lock", "Better than ReentrantReadWriteLock"], "key_classes": ["StampedLock"], "methods": ["tryOptimisticRead()", "readLock()", "writeLock()"], "complexity": {"all": "O(1)"}},

    # More API Design (15)
    {"id": "LLD-270", "title": "Design API for Task Management", "difficulty": "medium", "category": "lld", "subcategory": "API Design", "statement": "Design REST APIs for a task management system.", "requirements": ["Create/Update/Delete tasks", "Assign to users", "Track status", "Comments"], "key_endpoints": ["POST /tasks", "PUT /tasks/:id", "DELETE /tasks/:id", "POST /tasks/:id/comments"], "complexity": {"CRUD": "O(1)"}},
    {"id": "LLD-271", "title": "Design API for Notification System", "difficulty": "medium", "category": "lld", "subcategory": "API Design", "statement": "Design APIs for a notification system.", "requirements": ["Send notifications", "Get notifications", "Mark as read", "Preferences"], "key_endpoints": ["POST /notifications", "GET /notifications", "PUT /notifications/:id/read", "PUT /preferences"], "complexity": {"send": "O(1)", "get": "O(log n)"}},
    {"id": "LLD-272", "title": "Design API for Analytics Dashboard", "difficulty": "hard", "category": "lld", "subcategory": "API Design", "statement": "Design APIs for an analytics dashboard.", "requirements": ["Get metrics", "Time range queries", "Aggregations", "Real-time updates"], "key_endpoints": ["GET /metrics", "GET /metrics/:name", "GET /metrics/:name/range", "WebSocket /metrics/live"], "complexity": {"query": "O(log n)"}},
    {"id": "LLD-273", "title": "Design API for Search Engine", "difficulty": "hard", "category": "lld", "subcategory": "API Design", "statement": "Design APIs for a search engine.", "requirements": ["Index documents", "Search queries", "Autocomplete", "Ranking"], "key_endpoints": ["POST /documents", "GET /search", "GET /autocomplete", "GET /suggest"], "complexity": {"search": "O(log n)"}},
    {"id": "LLD-274", "title": "Design API for Payment Gateway", "difficulty": "hard", "category": "lld", "subcategory": "API Design", "statement": "Design APIs for a payment gateway.", "requirements": ["Process payments", "Refunds", "Webhooks", "Idempotency"], "key_endpoints": ["POST /payments", "POST /payments/:id/refund", "POST /webhooks", "GET /payments/:id"], "complexity": {"process": "O(1)"}},

    # More Database Design (15)
    {"id": "LLD-280", "title": "Design Database for Ride-Sharing", "difficulty": "hard", "category": "lld", "subcategory": "Database Design", "statement": "Design the database schema for a ride-sharing platform.", "requirements": ["Users", "Drivers", "Rides", "Payments", "Locations"], "key_tables": ["users", "drivers", "rides", "payments", "locations"], "relationships": ["users has many rides", "drivers has many rides", "rides has one payment"]},
    {"id": "LLD-281", "title": "Design Database for Food Delivery", "difficulty": "medium", "category": "lld", "subcategory": "Database Design", "statement": "Design the database schema for a food delivery platform.", "requirements": ["Restaurants", "Menu Items", "Orders", "Deliveries", "Customers"], "key_tables": ["restaurants", "menu_items", "orders", "deliveries", "customers"], "relationships": ["restaurants has many menu_items", "orders has one delivery"]},
    {"id": "LLD-282", "title": "Design Database for Learning Platform", "difficulty": "medium", "category": "lld", "subcategory": "Database Design", "statement": "Design the database schema for an online learning platform.", "requirements": ["Courses", "Lessons", "Students", "Enrollments", "Progress"], "key_tables": ["courses", "lessons", "students", "enrollments", "progress"], "relationships": ["courses has many lessons", "students has many enrollments"]},
    {"id": "LLD-283", "title": "Design Database for Social Media", "difficulty": "hard", "category": "lld", "subcategory": "Database Design", "statement": "Design the database schema for a social media platform.", "requirements": ["Users", "Posts", "Comments", "Likes", "Follows"], "key_tables": ["users", "posts", "comments", "likes", "follows"], "relationships": ["users has many posts", "posts has many comments", "users has many follows"]},
    {"id": "LLD-284", "title": "Design Database for E-commerce", "difficulty": "medium", "category": "lld", "subcategory": "Database Design", "statement": "Design the database schema for an e-commerce platform.", "requirements": ["Products", "Orders", "Customers", "Payments", "Reviews"], "key_tables": ["products", "orders", "customers", "payments", "reviews"], "relationships": ["customers has many orders", "products has many reviews"]},
]
