"""Additional handcrafted LeetCode-style questions for PlacementPro.

This module is loaded by `app.services.question_store` and extends the
question bank with a clean, high-signal batch of canonical problems.
"""
from __future__ import annotations

from datetime import datetime, timezone

STAMP = datetime.now(timezone.utc)


def _question(
    slug: str,
    title: str,
    statement: str,
    topic: str,
    sub_topic: str,
    difficulty: str,
    companies: list[str],
    role: list[str],
    examples: list[dict],
    testcases: list[dict],
    approach: str,
    code: str,
    hints: list[str],
    acceptance_rate: float,
    submissions: int,
    xp_points: int,
    frequency: int,
) -> dict:
    return {
        "type": "coding",
        "id": slug,
        "question": title,
        "question_title": title,
        "description": statement,
        "difficulty": difficulty,
        "topic": topic,
        "sub_topic": sub_topic,
        "companies": companies,
        "role": role,
        "examples": examples,
        "testcases": testcases,
        "solution": {
            "code": code,
            "language": "python",
            "time_complexity": "See approach",
            "space_complexity": "See approach",
            "optimal": True,
        },
        "hints": hints,
        "xp_points": xp_points,
        "frequency": frequency,
        "frequency_score": float(frequency),
        "acceptance_rate": acceptance_rate,
        "total_submissions": submissions,
        "upvotes": max(20, int(submissions * acceptance_rate / 1000)),
        "downvotes": max(1, int(submissions * (1 - acceptance_rate) / 20000)),
        "views": submissions * 2,
        "uploaded_by": "system",
        "created_at": STAMP,
        "updated_at": STAMP,
        "is_hidden": False,
        "dsa_guide": {
            "approach": approach,
            "data_structures": [],
            "patterns": [],
            "tips": hints,
        },
    }


questions = [
    _question(
        "extra-two-sum",
        "Two Sum",
        "Given an array of integers, return the indices of the two numbers that add up to the target. Solve it in linear time if possible.",
        "Arrays",
        "Hash Map",
        "easy",
        ["Google", "Amazon", "Microsoft"],
        ["SDE", "SDE Intern", "Backend Developer"],
        [{"input": "nums = [2,7,11,15], target = 9", "output": "[0,1]"}],
        [{"input": "[2,7,11,15]\\n9", "expected": "[0,1]"}, {"input": "[3,2,4]\\n6", "expected": "[1,2]"}],
        "Use a hash map to store seen values and their indices while scanning once from left to right.",
        "def twoSum(nums, target):\n    seen = {}\n    for i, n in enumerate(nums):\n        need = target - n\n        if need in seen:\n            return [seen[need], i]\n        seen[n] = i",
        ["Store the complement, not the current value.", "Return as soon as the pair is found."],
        0.74,
        2400000,
        80,
        95,
    ),
    _question(
        "extra-product-except-self",
        "Product of Array Except Self",
        "Return an array where each position contains the product of all numbers except the one at that position, without using division.",
        "Arrays",
        "Prefix/Suffix",
        "medium",
        ["Google", "Amazon", "Meta"],
        ["SDE", "Software Engineer", "Full Stack Developer"],
        [{"input": "nums = [1,2,3,4]", "output": "[24,12,8,6]"}],
        [{"input": "[1,2,3,4]", "expected": "[24,12,8,6]"}, {"input": "[-1,1,0,-3,3]", "expected": "[0,0,9,0,0]"}],
        "Build prefix products in one pass and multiply them by suffix products in a reverse pass.",
        "def productExceptSelf(nums):\n    ans = [1] * len(nums)\n    pref = 1\n    for i in range(len(nums)):\n        ans[i] = pref\n        pref *= nums[i]\n    suf = 1\n    for i in range(len(nums) - 1, -1, -1):\n        ans[i] *= suf\n        suf *= nums[i]\n    return ans",
        ["Use two passes, not nested loops.", "The current index should never include itself in the product."],
        0.63,
        1800000,
        100,
        88,
    ),
    _question(
        "extra-maximum-subarray",
        "Maximum Subarray",
        "Find the contiguous subarray with the largest sum.",
        "Arrays",
        "Kadane",
        "medium",
        ["Google", "Amazon", "Microsoft", "Adobe"],
        ["SDE", "Backend Developer"],
        [{"input": "nums = [-2,1,-3,4,-1,2,1,-5,4]", "output": "6"}],
        [{"input": "[-2,1,-3,4,-1,2,1,-5,4]", "expected": "6"}, {"input": "[1]", "expected": "1"}],
        "Keep a running best sum ending at the current index and reset when it becomes worse than starting fresh.",
        "def maxSubArray(nums):\n    best = cur = nums[0]\n    for n in nums[1:]:\n        cur = max(n, cur + n)\n        best = max(best, cur)\n    return best",
        ["This is the classic Kadane pattern.", "A negative running sum should be discarded."],
        0.71,
        2200000,
        90,
        92,
    ),
    _question(
        "extra-merge-intervals",
        "Merge Intervals",
        "Given a collection of intervals, merge all overlapping intervals and return the condensed set.",
        "Arrays",
        "Intervals",
        "medium",
        ["Google", "Amazon", "Microsoft", "Uber"],
        ["SDE", "Backend Developer", "Software Engineer"],
        [{"input": "[[1,3],[2,6],[8,10],[15,18]]", "output": "[[1,6],[8,10],[15,18]]"}],
        [{"input": "[[1,3],[2,6],[8,10],[15,18]]", "expected": "[[1,6],[8,10],[15,18]]"}, {"input": "[[1,4],[4,5]]", "expected": "[[1,5]]"}],
        "Sort by start time, then keep extending the current interval while overlaps continue.",
        "def merge(intervals):\n    intervals.sort()\n    out = []\n    for s, e in intervals:\n        if not out or out[-1][1] < s:\n            out.append([s, e])\n        else:\n            out[-1][1] = max(out[-1][1], e)\n    return out",
        ["Sorting first makes the merge step linear.", "Touching intervals should also merge."],
        0.66,
        1500000,
        95,
        84,
    ),
    _question(
        "extra-rotate-array",
        "Rotate Array",
        "Rotate an array to the right by k steps in place.",
        "Arrays",
        "In-place Manipulation",
        "medium",
        ["Apple", "Amazon", "Microsoft"],
        ["SDE", "Full Stack Developer"],
        [{"input": "nums = [1,2,3,4,5,6,7], k = 3", "output": "[5,6,7,1,2,3,4]"}],
        [{"input": "[1,2,3,4,5,6,7]\\n3", "expected": "[5,6,7,1,2,3,4]"}, {"input": "[-1,-100,3,99]\\n2", "expected": "[3,99,-1,-100]"}],
        "Reverse the full array, then reverse the first k elements and the remaining suffix.",
        "def rotate(nums, k):\n    k %= len(nums)\n    nums.reverse()\n    nums[:k] = reversed(nums[:k])\n    nums[k:] = reversed(nums[k:])\n    return nums",
        ["Normalize k with modulo.", "In-place rotation should avoid extra arrays."],
        0.69,
        1300000,
        85,
        77,
    ),
    _question(
        "extra-valid-anagram",
        "Valid Anagram",
        "Return true if two strings contain the same characters with the same frequencies.",
        "Strings",
        "Frequency Count",
        "easy",
        ["Google", "Amazon", "Microsoft"],
        ["SDE", "SDE Intern"],
        [{"input": "s = 'anagram', t = 'nagaram'", "output": "true"}],
        [{"input": "anagram\\nnagaram", "expected": "true"}, {"input": "rat\\ncar", "expected": "false"}],
        "Count characters in one string and decrement with the other, or compare sorted strings for the simplest version.",
        "def isAnagram(s, t):\n    if len(s) != len(t):\n        return False\n    counts = {}\n    for ch in s:\n        counts[ch] = counts.get(ch, 0) + 1\n    for ch in t:\n        if ch not in counts:\n            return False\n        counts[ch] -= 1\n        if counts[ch] == 0:\n            del counts[ch]\n    return not counts",
        ["Length mismatch is an instant fail.", "This is a frequency map problem."],
        0.77,
        2600000,
        70,
        90,
    ),
    _question(
        "extra-longest-palindrome",
        "Longest Palindromic Substring",
        "Find the longest substring that reads the same forwards and backwards.",
        "Strings",
        "Two Pointers",
        "medium",
        ["Google", "Amazon", "Meta", "Apple"],
        ["SDE", "Software Engineer"],
        [{"input": "s = 'babad'", "output": "'bab' or 'aba'"}],
        [{"input": "babad", "expected": "bab_or_aba"}, {"input": "cbbd", "expected": "bb"}],
        "Expand around each possible center and keep the longest span found.",
        "def longestPalindrome(s):\n    best = (0, 0)\n    def expand(l, r):\n        while l >= 0 and r < len(s) and s[l] == s[r]:\n            l -= 1\n            r += 1\n        return l + 1, r - 1\n    for i in range(len(s)):\n        for l, r in ((i, i), (i, i + 1)):\n            a, b = expand(l, r)\n            if b - a > best[1] - best[0]:\n                best = (a, b)\n    return s[best[0]:best[1] + 1]",
        ["Every palindrome has a center.", "Check both odd and even centers."],
        0.58,
        1100000,
        110,
        76,
    ),
    _question(
        "extra-group-anagrams",
        "Group Anagrams",
        "Group strings that are anagrams of each other.",
        "Strings",
        "Hash Map",
        "medium",
        ["Google", "Amazon", "LinkedIn"],
        ["SDE", "Full Stack Developer"],
        [{"input": "['eat','tea','tan','ate','nat','bat']", "output": "[['eat','tea','ate'],['tan','nat'],['bat']]"}],
        [{"input": "['eat','tea','tan','ate','nat','bat']", "expected": "grouped"}, {"input": "['']", "expected": "[['']]"}],
        "Use a sorted string or frequency signature as the hash key for each group.",
        "def groupAnagrams(strs):\n    groups = {}\n    for s in strs:\n        key = ''.join(sorted(s))\n        groups.setdefault(key, []).append(s)\n    return list(groups.values())",
        ["Equal letters in different order should land in the same bucket.", "A canonical key makes grouping easy."],
        0.64,
        1400000,
        90,
        80,
    ),
    _question(
        "extra-min-window-substring",
        "Minimum Window Substring",
        "Find the smallest substring of s that contains every character of t.",
        "Strings",
        "Sliding Window",
        "hard",
        ["Google", "Amazon", "Meta", "Netflix"],
        ["SDE", "Backend Developer"],
        [{"input": "s = 'ADOBECODEBANC', t = 'ABC'", "output": "'BANC'"}],
        [{"input": "ADOBECODEBANC\\nABC", "expected": "BANC"}, {"input": "a\\na", "expected": "a"}],
        "Expand the right edge until the window is valid, then shrink from the left to minimize it.",
        "def minWindow(s, t):\n    if not t or not s:\n        return ''\n    need = {}\n    for ch in t:\n        need[ch] = need.get(ch, 0) + 1\n    have = {}\n    need_count = len(need)\n    formed = 0\n    l = 0\n    ans = (float('inf'), None, None)\n    for r, ch in enumerate(s):\n        have[ch] = have.get(ch, 0) + 1\n        if ch in need and have[ch] == need[ch]:\n            formed += 1\n        while formed == need_count:\n            if r - l + 1 < ans[0]:\n                ans = (r - l + 1, l, r)\n            have[s[l]] -= 1\n            if s[l] in need and have[s[l]] < need[s[l]]:\n                formed -= 1\n            l += 1\n    return '' if ans[1] is None else s[ans[1]:ans[2] + 1]",
        ["Track how many required characters are satisfied.", "Shrink only while the window still covers t."],
        0.43,
        900000,
        140,
        70,
    ),
    _question(
        "extra-valid-parentheses",
        "Valid Parentheses",
        "Determine if the input string of brackets is valid.",
        "Stack",
        "Monotonic Stack",
        "easy",
        ["Amazon", "Google", "Microsoft"],
        ["SDE Intern", "SDE"],
        [{"input": "'()[]{}'", "output": "true"}],
        [{"input": "()[]{}", "expected": "true"}, {"input": "(]", "expected": "false"}],
        "Push opening brackets onto a stack and match each closing bracket against the last opening bracket.",
        "def isValid(s):\n    stack = []\n    pairs = {')': '(', ']': '[', '}': '{'}\n    for ch in s:\n        if ch in pairs:\n            if not stack or stack.pop() != pairs[ch]:\n                return False\n        else:\n            stack.append(ch)\n    return not stack",
        ["A stack is the natural fit for nested structure.", "Close with the most recent open bracket."],
        0.80,
        3000000,
        65,
        98,
    ),
    _question(
        "extra-daily-temperatures",
        "Daily Temperatures",
        "For each day, return how many days you must wait until a warmer temperature appears.",
        "Stack",
        "Monotonic Stack",
        "medium",
        ["Amazon", "Google", "Apple"],
        ["SDE", "Backend Developer"],
        [{"input": "temps = [73,74,75,71,69,72,76,73]", "output": "[1,1,4,2,1,1,0,0]"}],
        [{"input": "[73,74,75,71,69,72,76,73]", "expected": "[1,1,4,2,1,1,0,0]"}],
        "Maintain a decreasing stack of indices; when a warmer day arrives, resolve all colder days on top.",
        "def dailyTemperatures(temperatures):\n    ans = [0] * len(temperatures)\n    stack = []\n    for i, t in enumerate(temperatures):\n        while stack and temperatures[stack[-1]] < t:\n            j = stack.pop()\n            ans[j] = i - j\n        stack.append(i)\n    return ans",
        ["Store indices, not temperatures.", "The stack should stay monotonic decreasing."],
        0.61,
        1200000,
        90,
        83,
    ),
    _question(
        "extra-top-k-frequent",
        "Top K Frequent Elements",
        "Return the k most frequent elements in the array.",
        "Heap",
        "Priority Queue",
        "medium",
        ["Google", "Amazon", "Meta", "Uber"],
        ["SDE", "Software Engineer"],
        [{"input": "nums = [1,1,1,2,2,3], k = 2", "output": "[1,2]"}],
        [{"input": "[1,1,1,2,2,3]\\n2", "expected": "[1,2]"}, {"input": "[1]\\n1", "expected": "[1]"}],
        "Count frequencies first, then use a heap or bucket sort to pull the top k entries.",
        "def topKFrequent(nums, k):\n    freq = {}\n    for n in nums:\n        freq[n] = freq.get(n, 0) + 1\n    buckets = [[] for _ in range(len(nums) + 1)]\n    for n, c in freq.items():\n        buckets[c].append(n)\n    out = []\n    for c in range(len(buckets) - 1, 0, -1):\n        for n in buckets[c]:\n            out.append(n)\n            if len(out) == k:\n                return out",
        ["Buckets make this linear.", "You only need to scan from the highest frequency down."],
        0.62,
        1000000,
        85,
        81,
    ),
    _question(
        "extra-reverse-linked-list",
        "Reverse Linked List",
        "Reverse a singly linked list iteratively.",
        "Linked Lists",
        "Pointer Reversal",
        "easy",
        ["Google", "Amazon", "Microsoft"],
        ["SDE Intern", "SDE"],
        [{"input": "1->2->3->4->5", "output": "5->4->3->2->1"}],
        [{"input": "1->2->3->4->5", "expected": "5->4->3->2->1"}],
        "Walk the list once while rewiring next pointers using prev, current, and next references.",
        "def reverseList(head):\n    prev = None\n    while head:\n        nxt = head.next\n        head.next = prev\n        prev = head\n        head = nxt\n    return prev",
        ["Three pointers are enough.", "Do not lose the rest of the chain when rewiring."],
        0.83,
        1700000,
        75,
        89,
    ),
    _question(
        "extra-merge-two-lists",
        "Merge Two Sorted Lists",
        "Merge two sorted linked lists into one sorted list.",
        "Linked Lists",
        "Merge",
        "easy",
        ["Amazon", "Microsoft", "Apple"],
        ["SDE Intern", "SDE"],
        [{"input": "l1 = [1,2,4], l2 = [1,3,4]", "output": "[1,1,2,3,4,4]"}],
        [{"input": "[1,2,4]\\n[1,3,4]", "expected": "[1,1,2,3,4,4]"}],
        "Use a dummy head and repeatedly append the smaller front node from either list.",
        "def mergeTwoLists(l1, l2):\n    dummy = cur = type('Node', (), {})()\n    dummy.next = None\n    while l1 and l2:\n        if l1.val < l2.val:\n            cur.next, l1 = l1, l1.next\n        else:\n            cur.next, l2 = l2, l2.next\n        cur = cur.next\n    cur.next = l1 or l2\n    return dummy.next",
        ["A dummy node keeps the head logic simple.", "Append the leftover tail at the end."],
        0.81,
        1600000,
        70,
        86,
    ),
    _question(
        "extra-linked-list-cycle",
        "Linked List Cycle",
        "Detect whether a linked list contains a cycle.",
        "Linked Lists",
        "Cycle Detection",
        "easy",
        ["Google", "Amazon", "Meta"],
        ["SDE", "Backend Developer"],
        [{"input": "head = [3,2,0,-4] with tail connected to node 1", "output": "true"}],
        [{"input": "cycle", "expected": "true"}, {"input": "no cycle", "expected": "false"}],
        "Use Floyd's tortoise and hare pointers to detect a meeting point in O(1) space.",
        "def hasCycle(head):\n    slow = fast = head\n    while fast and fast.next:\n        slow = slow.next\n        fast = fast.next.next\n        if slow is fast:\n            return True\n    return False",
        ["Fast pointer should move twice as quickly.", "If they meet, a cycle exists."],
        0.79,
        1500000,
        75,
        87,
    ),
    _question(
        "extra-remove-nth-node",
        "Remove Nth Node From End of List",
        "Remove the nth node from the end of a linked list in one pass.",
        "Linked Lists",
        "Two Pointers",
        "medium",
        ["Amazon", "Microsoft", "Uber"],
        ["SDE", "Backend Developer"],
        [{"input": "head = [1,2,3,4,5], n = 2", "output": "[1,2,3,5]"}],
        [{"input": "[1,2,3,4,5]\\n2", "expected": "[1,2,3,5]"}, {"input": "[1]\\n1", "expected": "[]"}],
        "Advance a fast pointer n steps, then move both pointers together until the fast pointer reaches the end.",
        "def removeNthFromEnd(head, n):\n    dummy = type('Node', (), {})()\n    dummy.next = head\n    slow = fast = dummy\n    for _ in range(n):\n        fast = fast.next\n    while fast.next:\n        slow = slow.next\n        fast = fast.next\n    slow.next = slow.next.next\n    return dummy.next",
        ["A dummy head avoids edge-case handling.", "The distance between pointers is the key."],
        0.67,
        1100000,
        95,
        78,
    ),
    _question(
        "extra-invert-binary-tree",
        "Invert Binary Tree",
        "Swap every left and right child in the tree.",
        "Trees",
        "DFS",
        "easy",
        ["Google", "Amazon", "Microsoft"],
        ["SDE", "SDE Intern"],
        [{"input": "root = [4,2,7,1,3,6,9]", "output": "[4,7,2,9,6,3,1]"}],
        [{"input": "[4,2,7,1,3,6,9]", "expected": "mirrored_tree"}],
        "Recursively invert the subtrees and then swap the child pointers at each node.",
        "def invertTree(root):\n    if not root:\n        return None\n    root.left, root.right = invertTree(root.right), invertTree(root.left)\n    return root",
        ["The tree structure mirrors itself.", "Post-order or pre-order both work."],
        0.85,
        1900000,
        80,
        91,
    ),
    _question(
        "extra-diameter-tree",
        "Diameter of Binary Tree",
        "Return the length of the longest path between any two nodes in the tree.",
        "Trees",
        "DFS",
        "easy",
        ["Google", "Amazon", "Meta"],
        ["SDE", "Software Engineer"],
        [{"input": "root = [1,2,3,4,5]", "output": "3"}],
        [{"input": "[1,2,3,4,5]", "expected": "3"}],
        "Compute the height of each subtree and update the best path length using left height plus right height.",
        "def diameterOfBinaryTree(root):\n    best = 0\n    def depth(node):\n        nonlocal best\n        if not node:\n            return 0\n        l = depth(node.left)\n        r = depth(node.right)\n        best = max(best, l + r)\n        return 1 + max(l, r)\n    depth(root)\n    return best",
        ["The answer is not necessarily through the root.", "Track the max sum of left and right depths."],
        0.73,
        1300000,
        90,
        84,
    ),
    _question(
        "extra-lca-binary-tree",
        "Lowest Common Ancestor of a Binary Tree",
        "Find the lowest node that has both target nodes in its subtree.",
        "Trees",
        "LCA",
        "medium",
        ["Google", "Amazon", "Microsoft", "Meta"],
        ["SDE", "Backend Developer"],
        [{"input": "root = [3,5,1,6,2,0,8,null,null,7,4], p = 5, q = 1", "output": "3"}],
        [{"input": "LCA sample", "expected": "3"}],
        "Recurse left and right; if both sides return a node, the current node is the LCA.",
        "def lowestCommonAncestor(root, p, q):\n    if not root or root is p or root is q:\n        return root\n    left = lowestCommonAncestor(root.left, p, q)\n    right = lowestCommonAncestor(root.right, p, q)\n    if left and right:\n        return root\n    return left or right",
        ["Return the node itself when you hit either target.", "A split between left and right marks the answer."],
        0.59,
        1000000,
        120,
        72,
    ),
    _question(
        "extra-level-order",
        "Binary Tree Level Order Traversal",
        "Return the node values level by level from top to bottom.",
        "Trees",
        "BFS",
        "medium",
        ["Google", "Amazon", "Apple"],
        ["SDE", "SDE Intern"],
        [{"input": "root = [3,9,20,null,null,15,7]", "output": "[[3],[9,20],[15,7]]"}],
        [{"input": "[3,9,20,null,null,15,7]", "expected": "[[3],[9,20],[15,7]]"}],
        "Use a queue and process nodes in batches, one level at a time.",
        "def levelOrder(root):\n    if not root:\n        return []\n    from collections import deque\n    q = deque([root])\n    ans = []\n    while q:\n        level = []\n        for _ in range(len(q)):\n            node = q.popleft()\n            level.append(node.val)\n            if node.left:\n                q.append(node.left)\n            if node.right:\n                q.append(node.right)\n        ans.append(level)\n    return ans",
        ["Process one level at a time.", "A queue naturally models breadth-first traversal."],
        0.76,
        1400000,
        85,
        82,
    ),
    _question(
        "extra-balanced-tree",
        "Balanced Binary Tree",
        "Determine whether the tree is height-balanced.",
        "Trees",
        "DFS",
        "easy",
        ["Google", "Amazon", "Microsoft"],
        ["SDE Intern", "SDE"],
        [{"input": "root = [3,9,20,null,null,15,7]", "output": "true"}],
        [{"input": "[3,9,20,null,null,15,7]", "expected": "true"}, {"input": "[1,2,2,3,3,null,null,4,4]", "expected": "false"}],
        "Return subtree heights bottom-up and signal failure early when any height difference exceeds 1.",
        "def isBalanced(root):\n    def height(node):\n        if not node:\n            return 0\n        l = height(node.left)\n        if l == -1:\n            return -1\n        r = height(node.right)\n        if r == -1 or abs(l - r) > 1:\n            return -1\n        return 1 + max(l, r)\n    return height(root) != -1",
        ["Bottom-up height checking avoids repeated work.", "Early exit when imbalance is found."],
        0.78,
        1200000,
        75,
        85,
    ),
    _question(
        "extra-number-of-islands",
        "Number of Islands",
        "Count how many connected groups of land cells appear in the grid.",
        "Graphs",
        "Grid DFS",
        "medium",
        ["Google", "Amazon", "Meta", "Uber"],
        ["SDE", "Backend Developer"],
        [{"input": "grid = [['1','1','0'],['0','1','0'],['1','0','1']]", "output": "3"}],
        [{"input": "sample grid", "expected": "3"}],
        "Flood-fill each unvisited land cell with DFS or BFS and count how many times you start a new traversal.",
        "def numIslands(grid):\n    if not grid:\n        return 0\n    rows, cols = len(grid), len(grid[0])\n    seen = set()\n    def dfs(r, c):\n        if r < 0 or c < 0 or r >= rows or c >= cols:\n            return\n        if grid[r][c] == '0' or (r, c) in seen:\n            return\n        seen.add((r, c))\n        dfs(r + 1, c); dfs(r - 1, c); dfs(r, c + 1); dfs(r, c - 1)\n    islands = 0\n    for r in range(rows):\n        for c in range(cols):\n            if grid[r][c] == '1' and (r, c) not in seen:\n                islands += 1\n                dfs(r, c)\n    return islands",
        ["Each island is one connected component.", "Mark visited cells so you never count them twice."],
        0.65,
        1500000,
        100,
        80,
    ),
    _question(
        "extra-clone-graph",
        "Clone Graph",
        "Create a deep copy of an undirected graph starting from a given node.",
        "Graphs",
        "DFS/BFS",
        "medium",
        ["Google", "Meta", "Amazon"],
        ["SDE", "Software Engineer"],
        [{"input": "graph = 1--2, 1--4, 2--3, 3--4", "output": "deep copy"}],
        [{"input": "sample graph", "expected": "deep copy"}],
        "Use a hash map from original nodes to cloned nodes while traversing with DFS or BFS.",
        "def cloneGraph(node):\n    if not node:\n        return None\n    clones = {}\n    def dfs(n):\n        if n in clones:\n            return clones[n]\n        copy = type('Node', (), {})()\n        copy.val = n.val\n        copy.neighbors = []\n        clones[n] = copy\n        for nei in n.neighbors:\n            copy.neighbors.append(dfs(nei))\n        return copy\n    return dfs(node)",
        ["The clone map prevents infinite recursion on cycles.", "Clone neighbors recursively or iteratively."],
        0.57,
        900000,
        130,
        68,
    ),
    _question(
        "extra-course-schedule",
        "Course Schedule",
        "Determine if all courses can be finished given prerequisite pairs.",
        "Graphs",
        "Topological Sort",
        "medium",
        ["Google", "Amazon", "LinkedIn", "Microsoft"],
        ["SDE", "Backend Developer"],
        [{"input": "numCourses = 2, prerequisites = [[1,0]]", "output": "true"}],
        [{"input": "2 [[1,0]]", "expected": "true"}, {"input": "2 [[1,0],[0,1]]", "expected": "false"}],
        "Detect cycles using topological sorting or DFS with three-color marking.",
        "def canFinish(numCourses, prerequisites):\n    from collections import defaultdict, deque\n    graph = defaultdict(list)\n    indeg = [0] * numCourses\n    for a, b in prerequisites:\n        graph[b].append(a)\n        indeg[a] += 1\n    q = deque([i for i in range(numCourses) if indeg[i] == 0])\n    seen = 0\n    while q:\n        node = q.popleft()\n        seen += 1\n        for nei in graph[node]:\n            indeg[nei] -= 1\n            if indeg[nei] == 0:\n                q.append(nei)\n    return seen == numCourses",
        ["A cycle means impossible scheduling.", "Kahn's algorithm is the cleanest approach."],
        0.62,
        1000000,
        100,
        73,
    ),
    _question(
        "extra-pacific-atlantic",
        "Pacific Atlantic Water Flow",
        "Find cells from which water can flow to both the Pacific and Atlantic oceans.",
        "Graphs",
        "Reverse DFS",
        "medium",
        ["Google", "Amazon", "Meta"],
        ["SDE", "Software Engineer"],
        [{"input": "heights grid", "output": "list of coordinates"}],
        [{"input": "sample grid", "expected": "coordinates"}],
        "Run reverse traversals from each ocean boundary and intersect the reachable cells.",
        "def pacificAtlantic(heights):\n    rows, cols = len(heights), len(heights[0])\n    def reach(starts):\n        seen = set(starts)\n        stack = list(starts)\n        while stack:\n            r, c = stack.pop()\n            for nr, nc in ((r+1,c), (r-1,c), (r,c+1), (r,c-1)):\n                if 0 <= nr < rows and 0 <= nc < cols and (nr, nc) not in seen and heights[nr][nc] >= heights[r][c]:\n                    seen.add((nr, nc))\n                    stack.append((nr, nc))\n        return seen\n    pac = reach([(0, c) for c in range(cols)] + [(r, 0) for r in range(rows)])\n    atl = reach([(rows - 1, c) for c in range(cols)] + [(r, cols - 1) for r in range(rows)])\n    return [[r, c] for r, c in pac & atl]",
        ["Work backwards from the oceans.", "Intersect the cells reachable from each side."],
        0.49,
        800000,
        130,
        64,
    ),
    _question(
        "extra-network-delay",
        "Network Delay Time",
        "Given directed weighted edges, compute how long it takes for a signal to reach all nodes.",
        "Graphs",
        "Shortest Path",
        "medium",
        ["Google", "Amazon", "Uber", "Netflix"],
        ["SDE", "Backend Developer"],
        [{"input": "times = [[2,1,1],[2,3,1],[3,4,1]], n = 4, k = 2", "output": "2"}],
        [{"input": "sample", "expected": "2"}],
        "Use Dijkstra's algorithm with a min-heap to expand the next closest node first.",
        "def networkDelayTime(times, n, k):\n    import heapq\n    from collections import defaultdict\n    graph = defaultdict(list)\n    for u, v, w in times:\n        graph[u].append((v, w))\n    pq = [(0, k)]\n    dist = {}\n    while pq:\n        d, node = heapq.heappop(pq)\n        if node in dist:\n            continue\n        dist[node] = d\n        for nei, w in graph[node]:\n            if nei not in dist:\n                heapq.heappush(pq, (d + w, nei))\n    return max(dist.values()) if len(dist) == n else -1",
        ["Dijkstra handles positive weights.", "The farthest settled node determines the answer."],
        0.54,
        700000,
        120,
        61,
    ),
    _question(
        "extra-climbing-stairs",
        "Climbing Stairs",
        "Count the number of distinct ways to climb n stairs when you can take 1 or 2 steps.",
        "Dynamic Programming",
        "1D DP",
        "easy",
        ["Amazon", "Google", "Microsoft"],
        ["SDE Intern", "SDE"],
        [{"input": "n = 3", "output": "3"}],
        [{"input": "3", "expected": "3"}, {"input": "5", "expected": "8"}],
        "The count at step i is the sum of counts for the previous two steps.",
        "def climbStairs(n):\n    a, b = 1, 1\n    for _ in range(n):\n        a, b = b, a + b\n    return a",
        ["This is Fibonacci in disguise.", "Use rolling variables for O(1) space."],
        0.84,
        2800000,
        70,
        93,
    ),
    _question(
        "extra-house-robber",
        "House Robber",
        "Maximize the amount of money stolen without robbing adjacent houses.",
        "Dynamic Programming",
        "Linear DP",
        "medium",
        ["Google", "Amazon", "Meta"],
        ["SDE", "Backend Developer"],
        [{"input": "nums = [1,2,3,1]", "output": "4"}],
        [{"input": "[1,2,3,1]", "expected": "4"}, {"input": "[2,7,9,3,1]", "expected": "12"}],
        "At each house, choose between robbing it plus the best up to i-2 or skipping it and keeping the best up to i-1.",
        "def rob(nums):\n    prev2 = prev1 = 0\n    for n in nums:\n        prev2, prev1 = prev1, max(prev1, prev2 + n)\n    return prev1",
        ["Adjacent houses cannot both be taken.", "This is a two-state rolling DP."],
        0.72,
        1700000,
        95,
        86,
    ),
    _question(
        "extra-coin-change",
        "Coin Change",
        "Return the minimum number of coins needed to make up the target amount, or -1 if it is impossible.",
        "Dynamic Programming",
        "Unbounded Knapsack",
        "medium",
        ["Google", "Amazon", "Microsoft", "Uber"],
        ["SDE", "Software Engineer"],
        [{"input": "coins = [1,2,5], amount = 11", "output": "3"}],
        [{"input": "[1,2,5]\\n11", "expected": "3"}, {"input": "[2]\\n3", "expected": "-1"}],
        "Use bottom-up DP where dp[x] stores the minimum coins needed to form amount x.",
        "def coinChange(coins, amount):\n    dp = [amount + 1] * (amount + 1)\n    dp[0] = 0\n    for a in range(1, amount + 1):\n        for c in coins:\n            if a - c >= 0:\n                dp[a] = min(dp[a], dp[a - c] + 1)\n    return -1 if dp[amount] > amount else dp[amount]",
        ["Initialize with an impossible large value.", "This is a classic unbounded knapsack DP."],
        0.52,
        900000,
        120,
        74,
    ),
    _question(
        "extra-lis",
        "Longest Increasing Subsequence",
        "Return the length of the longest strictly increasing subsequence.",
        "Dynamic Programming",
        "Patience Sorting",
        "medium",
        ["Google", "Amazon", "Meta", "Apple"],
        ["SDE", "Backend Developer"],
        [{"input": "nums = [10,9,2,5,3,7,101,18]", "output": "4"}],
        [{"input": "[10,9,2,5,3,7,101,18]", "expected": "4"}, {"input": "[0,1,0,3,2,3]", "expected": "4"}],
        "Track the smallest possible tail for subsequences of every length using a binary-searchable list.",
        "def lengthOfLIS(nums):\n    tails = []\n    import bisect\n    for n in nums:\n        i = bisect.bisect_left(tails, n)\n        if i == len(tails):\n            tails.append(n)\n        else:\n            tails[i] = n\n    return len(tails)",
        ["Binary search keeps the solution fast.", "The tails list is not the subsequence itself."],
        0.46,
        850000,
        130,
        67,
    ),
]
