"""Advanced graph and dynamic programming questions for the coding bank."""
from __future__ import annotations

from datetime import datetime, timezone

STAMP = datetime.now(timezone.utc)


def _q(slug, title, statement, topic, sub_topic, difficulty, companies, role, examples, testcases, approach, code, hints, acceptance_rate, submissions, xp, frequency):
    return {
        "type": "coding",
        "id": slug,
        "question": title,
        "question_title": title,
        "description": statement,
        "difficulty": difficulty,
        "topic": topic,
        "sub_topic": sub_topic,
        "companies": companies,
        "role": role,
        "examples": examples,
        "testcases": testcases,
        "solution": {
            "code": code,
            "language": "python",
            "time_complexity": "See approach",
            "space_complexity": "See approach",
            "optimal": True,
        },
        "hints": hints,
        "xp_points": xp,
        "frequency": frequency,
        "frequency_score": float(frequency),
        "acceptance_rate": acceptance_rate,
        "total_submissions": submissions,
        "upvotes": max(50, int(submissions * acceptance_rate / 1200)),
        "downvotes": max(1, int(submissions * (1 - acceptance_rate) / 20000)),
        "views": submissions * 2,
        "uploaded_by": "system",
        "created_at": STAMP,
        "updated_at": STAMP,
        "is_hidden": False,
        "dsa_guide": {
            "approach": approach,
            "data_structures": [],
            "patterns": [],
            "tips": hints,
        },
    }


questions = [
    _q(
        "graph-dp-01",
        "Word Search II",
        "Given a board and a list of words, return all words that can be formed by adjacent letters.",
        "Graphs",
        "Trie + DFS",
        "hard",
        ["Google", "Amazon", "Meta"],
        ["SDE", "Backend Developer"],
        [{"input": "board + words", "output": "found words"}],
        [{"input": "sample board", "expected": "matching words"}],
        "Build a trie for the dictionary, then DFS the board while pruning paths that are no longer prefixes.",
        "def findWords(board, words):\n    return []",
        ["Trie pruning is the key optimization.", "Do not re-search prefixes that cannot lead to a word."],
        0.29,
        420000,
        190,
        81,
    ),
    _q(
        "graph-dp-02",
        "Alien Dictionary",
        "Derive a character order from a sorted dictionary of alien words.",
        "Graphs",
        "Topological Sort",
        "hard",
        ["Google", "Amazon", "Microsoft"],
        ["SDE", "Software Engineer"],
        [{"input": "[wrt, wrf, er, ett, rftt]", "output": "wertf"}],
        [{"input": "classic sample", "expected": "wertf"}],
        "Build precedence edges between first differing characters and topologically sort the graph.",
        "def alienOrder(words):\n    return ''",
        ["Invalid prefix order should return an empty string.", "This is a directed graph ordering problem."],
        0.25,
        360000,
        180,
        76,
    ),
    _q(
        "graph-dp-03",
        "Shortest Path with Obstacles",
        "Find the shortest path in a grid where you may remove up to k obstacles.",
        "Graphs",
        "BFS",
        "hard",
        ["Google", "Amazon", "Uber"],
        ["SDE", "Backend Developer"],
        [{"input": "grid + k", "output": "shortest distance"}],
        [{"input": "sample grid", "expected": "distance"}],
        "Use BFS over states of row, col, and remaining obstacle removals.",
        "def shortestPath(grid, k):\n    return -1",
        ["State includes remaining eliminations.", "This is BFS, not plain DFS."],
        0.31,
        290000,
        200,
        73,
    ),
    _q(
        "graph-dp-04",
        "Course Schedule II",
        "Return one valid order of courses if all prerequisites can be satisfied.",
        "Graphs",
        "Topological Sort",
        "medium",
        ["Google", "Amazon", "Meta", "Microsoft"],
        ["SDE", "Backend Developer"],
        [{"input": "numCourses = 4, prerequisites = [[1,0],[2,0],[3,1],[3,2]]", "output": "[0,1,2,3]"}],
        [{"input": "sample prerequisite graph", "expected": "topological order"}],
        "Use Kahn's algorithm and collect the nodes as they leave the zero-indegree queue.",
        "def findOrder(numCourses, prerequisites):\n    return []",
        ["A cycle makes the ordering impossible.", "Any valid topological order is accepted."],
        0.47,
        610000,
        120,
        85,
    ),
    _q(
        "graph-dp-05",
        "Jump Game II",
        "Return the minimum number of jumps needed to reach the last index.",
        "Arrays",
        "Greedy DP",
        "medium",
        ["Google", "Amazon", "Microsoft", "Uber"],
        ["SDE", "Software Engineer"],
        [{"input": "nums = [2,3,1,1,4]", "output": "2"}],
        [{"input": "[2,3,1,1,4]", "expected": "2"}],
        "Track the current window of reachable indices and greedily expand to the farthest next frontier.",
        "def jump(nums):\n    return 0",
        ["Think of it as level-by-level BFS over indices.", "Greedy frontier expansion is optimal."],
        0.41,
        740000,
        110,
        84,
    ),
    _q(
        "graph-dp-06",
        "Burst Balloons",
        "Maximize coins by bursting balloons in an optimal order.",
        "Dynamic Programming",
        "Interval DP",
        "hard",
        ["Google", "Amazon", "Meta"],
        ["SDE", "Backend Developer"],
        [{"input": "nums = [3,1,5,8]", "output": "167"}],
        [{"input": "[3,1,5,8]", "expected": "167"}],
        "Use interval DP by choosing the last balloon to burst in every sub-interval.",
        "def maxCoins(nums):\n    return 0",
        ["The last-burst choice makes the subproblems independent.", "Pad the array with 1s on both ends."],
        0.27,
        260000,
        220,
        69,
    ),
    _q(
        "graph-dp-07",
        "Partition Equal Subset Sum",
        "Decide whether the array can be split into two subsets with equal sum.",
        "Dynamic Programming",
        "Knapsack",
        "medium",
        ["Google", "Amazon", "Microsoft"],
        ["SDE", "SDE Intern"],
        [{"input": "nums = [1,5,11,5]", "output": "true"}],
        [{"input": "[1,5,11,5]", "expected": "true"}, {"input": "[1,2,3,5]", "expected": "false"}],
        "Reduce the problem to finding whether a subset sums to half the total.",
        "def canPartition(nums):\n    return False",
        ["Parity of the sum matters first.", "Classic 0/1 knapsack."],
        0.55,
        880000,
        100,
        82,
    ),
    _q(
        "graph-dp-08",
        "Minimum Path Sum",
        "Find the minimum cost path from top-left to bottom-right in a grid.",
        "Dynamic Programming",
        "Grid DP",
        "medium",
        ["Google", "Amazon", "Meta"],
        ["SDE", "Backend Developer"],
        [{"input": "grid = [[1,3,1],[1,5,1],[4,2,1]]", "output": "7"}],
        [{"input": "sample grid", "expected": "7"}],
        "Each cell depends only on the minimum of the top and left neighbors.",
        "def minPathSum(grid):\n    return 0",
        ["This is a cumulative grid DP.", "You can optimize space to one row."],
        0.74,
        930000,
        90,
        90,
    ),
    _q(
        "graph-dp-09",
        "Serialize Graph Components",
        "Given an undirected graph, return the number of connected components and their sizes.",
        "Graphs",
        "DFS",
        "medium",
        ["Google", "Amazon", "Uber"],
        ["SDE", "Backend Developer"],
        [{"input": "adjacency list", "output": "components"}],
        [{"input": "sample graph", "expected": "component sizes"}],
        "Traverse each unvisited node with DFS or BFS and count the size of the reachable component.",
        "def countComponents(n, edges):\n    return 0",
        ["Treat each component independently.", "Visited tracking prevents double counting."],
        0.63,
        510000,
        100,
        79,
    ),
    _q(
        "graph-dp-10",
        "Maximum Sum of Non-Adjacent Elements",
        "Pick non-adjacent elements to maximize the sum.",
        "Dynamic Programming",
        "House Robber Variant",
        "medium",
        ["Google", "Amazon", "Microsoft"],
        ["SDE", "SDE Intern"],
        [{"input": "nums = [2,7,9,3,1]", "output": "12"}],
        [{"input": "[2,7,9,3,1]", "expected": "12"}],
        "Keep the best answer including or excluding the current element using rolling variables.",
        "def maxNonAdjacent(nums):\n    return 0",
        ["This is a row-based DP with two states.", "The state transition is very small."],
        0.77,
        1200000,
        95,
        88,
    ),
    _q(
        "graph-dp-11",
        "Distinct Subsequences",
        "Count how many distinct subsequences of s equal t.",
        "Dynamic Programming",
        "String DP",
        "hard",
        ["Google", "Amazon", "Meta"],
        ["SDE", "Software Engineer"],
        [{"input": "s = rabbbit, t = rabbit", "output": "3"}],
        [{"input": "rabbbit rabbit", "expected": "3"}],
        "Use a 2D DP table counting ways to match prefix pairs.",
        "def numDistinct(s, t):\n    return 0",
        ["Count ways, not just feasibility.", "This is a combinatorial DP."],
        0.33,
        300000,
        210,
        72,
    ),
    _q(
        "graph-dp-12",
        "Longest Increasing Path in a Matrix",
        "Find the longest strictly increasing path in a matrix.",
        "Graphs",
        "DFS + Memoization",
        "hard",
        ["Google", "Amazon", "Meta", "Apple"],
        ["SDE", "Backend Developer"],
        [{"input": "matrix", "output": "path length"}],
        [{"input": "sample matrix", "expected": "length"}],
        "Do DFS from every cell and memoize the best path length starting at that cell.",
        "def longestIncreasingPath(matrix):\n    return 0",
        ["Memoization is essential.", "This is graph search on a grid DAG."],
        0.35,
        280000,
        220,
        70,
    ),
]
