"""Seed 8 learning modules for PlacementPro."""
from datetime import datetime, timezone
from bson import ObjectId
from app.database import learning_modules_collection, get_db

MODULES = [
    {
        "question_id": "two-sum",
        "title": "Two Sum — The Hash Map Approach",
        "description": "Learn how to solve the classic Two Sum problem using hash maps for O(n) efficiency.",
        "difficulty": "beginner",
        "estimated_time_minutes": 15,
        "topic": "arrays",
        "xp_reward": 50,
        "badge_reward": "Hash Map Hero",
        "company_tags": ["Amazon", "Google", "Meta", "Microsoft"],
        "steps": [
            {
                "step_number": 1,
                "type": "theory",
                "title": "Why Hash Maps?",
                "content": "<p>The Two Sum problem asks you to find two numbers in an array that add up to a target. A brute-force approach checks every pair, giving O(n²) time. A <strong>hash map</strong> (dictionary in Python, Map in JavaScript) lets us do this in <strong>O(n)</strong> time by trading space for speed.</p><p>Key insight: As we iterate through the array, we can store each number's complement (target - num) and check if the current number is a complement we've already seen.</p>",
                "code_snippet": null,
                "language": null,
                "is_unlocked": true,
                "is_required": true,
                "order": 1,
            },
            {
                "step_number": 2,
                "type": "example",
                "title": "Walkthrough with Example",
                "content": "<p><strong>Input:</strong> nums = [2, 7, 11, 15], target = 9</p><p><strong>Step-by-step:</strong></p><ol><li>Start with empty hash map: {}</li><li>Index 0, num=2: complement = 9-2 = 7. 7 not in map. Store {2: 0}</li><li>Index 1, num=7: complement = 9-7 = 2. 2 IS in map at index 0! Return [0, 1]</li></ol><p>We found the answer in just 2 steps instead of checking all 6 pairs.</p>",
                "code_snippet": null,
                "language": null,
                "is_unlocked": false,
                "is_required": true,
                "order": 2,
            },
            {
                "step_number": 3,
                "type": "example",
                "title": "Code Example — Python",
                "content": "<p>Here's the clean, efficient solution using a single-pass hash map:</p>",
                "code_snippet": "def two_sum(nums, target):\n    seen = {}\n    for i, num in enumerate(nums):\n        complement = target - num\n        if complement in seen:\n            return [seen[complement], i]\n        seen[num] = i\n    return []",
                "language": "python",
                "is_unlocked": false,
                "is_required": true,
                "order": 3,
            },
            {
                "step_number": 4,
                "type": "try_it",
                "title": "Try It Yourself",
                "content": "<p>Now write your own <code>two_sum</code> function. Remember: use a dictionary to track numbers you've seen and their indices.</p><p><strong>Template:</strong></p>",
                "code_snippet": "def two_sum(nums, target):\n    # Your code here\n    pass",
                "language": "python",
                "is_unlocked": false,
                "is_required": true,
                "order": 4,
            },
            {
                "step_number": 5,
                "type": "hint",
                "title": "Common Mistakes",
                "content": "<ul><li><strong>Don't use nested loops</strong> — O(n²) will time out on large inputs</li><li><strong>Don't sort first</strong> — you need original indices</li><li><strong>Check before inserting</strong> — if you insert before checking, you might use the same element twice</li><li><strong>Edge case:</strong> What if no solution exists? Return an empty list</li></ul>",
                "code_snippet": null,
                "language": null,
                "is_unlocked": false,
                "is_required": false,
                "order": 5,
            },
            {
                "step_number": 6,
                "type": "solution",
                "title": "Solution & Review",
                "content": "<p><strong>Time Complexity:</strong> O(n) — single pass through the array</p><p><strong>Space Complexity:</strong> O(n) — hash map stores up to n elements</p><p>This pattern applies to many problems: <strong>Two Sum, Three Sum (extension), Four Sum, and any 'find pairs that sum to target'</strong> problems.</p><p>The hash map approach is one of the most fundamental techniques in array problems. Master it and you'll solve a huge class of interview questions efficiently.</p>",
                "code_snippet": "def two_sum(nums, target):\n    seen = {}\n    for i, num in enumerate(nums):\n        complement = target - num\n        if complement in seen:\n            return [seen[complement], i]\n        seen[num] = i\n    return []",
                "language": "python",
                "is_unlocked": false,
                "is_required": true,
                "order": 6,
            },
        ],
        "created_at": datetime.now(timezone.utc),
    },
    {
        "question_id": "valid-parentheses",
        "title": "Valid Parentheses — Stack Thinking",
        "description": "Master the stack data structure by solving the Valid Parentheses problem.",
        "difficulty": "intermediate",
        "estimated_time_minutes": 20,
        "topic": "strings",
        "xp_reward": 75,
        "badge_reward": "Stack Master",
        "company_tags": ["Amazon", "Google", "Meta", "Apple", "Microsoft"],
        "steps": [
            {
                "step_number": 1,
                "type": "theory",
                "title": "What is a Stack?",
                "content": "<p>A <strong>stack</strong> is a Last-In-First-Out (LIFO) data structure. Think of a stack of plates — you add and remove from the top only.</p><p>In Python, use a <code>list</code> as a stack with <code>.append()</code> and <code>.pop()</code>. In JavaScript, use an <code>array</code> with <code>.push()</code> and <code>.pop()</code>.</p><p>The key insight for Valid Parentheses: when we see an <strong>opening bracket</strong>, we push it. When we see a <strong>closing bracket</strong>, we check if it matches the most recent opening bracket (top of stack). If not, it's invalid.</p>",
                "code_snippet": null,
                "language": null,
                "is_unlocked": true,
                "is_required": true,
                "order": 1,
            },
            {
                "step_number": 2,
                "type": "example",
                "title": "Walkthrough",
                "content": "<p><strong>Input:</strong> s = \"()[]{}\"</p><p><strong>Process:</strong></p><ol><li>'(' → push '(' → stack: ['(']</li><li>')' → top is '(' → match! pop → stack: []</li><li>'[' → push '[' → stack: ['[']</li><li']' → top is '[' → match! pop → stack: []</li><li>'{' → push '{' → stack: ['{']</li><li>'}' → top is '{' → match! pop → stack: []</li></ol><p>Stack is empty at the end → valid! Return true.</p><p><strong>Input:</strong> s = \"(]\"</p><ol><li>'(' → push → stack: ['(']</li><li>']' → top is '(' → mismatch! → invalid → return false</li></ol>",
                "code_snippet": null,
                "language": null,
                "is_unlocked": false,
                "is_required": true,
                "order": 2,
            },
            {
                "step_number": 3,
                "type": "example",
                "title": "Code Example — Python",
                "content": "<p>The complete solution using a stack and a bracket mapping:</p>",
                "code_snippet": "def is_valid(s):\n    stack = []\n    mapping = {')': '(', ']': '[', '}': '{'}\n    for char in s:\n        if char in mapping:\n            top = stack.pop() if stack else '#'\n            if mapping[char] != top:\n                return False\n        else:\n            stack.append(char)\n    return not stack",
                "language": "python",
                "is_unlocked": false,
                "is_required": true,
                "order": 3,
            },
            {
                "step_number": 4,
                "type": "try_it",
                "title": "Try It Yourself",
                "content": "<p>Implement <code>is_valid</code> using a stack. Use a dictionary to map closing brackets to their matching opening brackets.</p>",
                "code_snippet": "def is_valid(s):\n    # Your code here\n    pass",
                "language": "python",
                "is_unlocked": false,
                "is_required": true,
                "order": 4,
            },
            {
                "step_number": 5,
                "type": "hint",
                "title": "Common Mistakes",
                "content": "<ul><li><strong>Forgetting to check if stack is empty</strong> before popping — this causes an IndexError</li><li><strong>Using the wrong mapping</strong> — map closing → opening, not opening → closing</li><li><strong>Not checking the final stack state</strong> — \"((((\" has no mismatches but has unclosed brackets</li></ul>",
                "code_snippet": null,
                "language": null,
                "is_unlocked": false,
                "is_required": false,
                "order": 5,
            },
            {
                "step_number": 6,
                "type": "solution",
                "title": "Solution & Review",
                "content": "<p><strong>Time Complexity:</strong> O(n) — single pass</p><p><strong>Space Complexity:</strong> O(n) — stack can grow up to n</p><p>The stack pattern applies to many problems: <strong>expression evaluation, bracket matching, undo/redo systems, function call stacks</strong>. This is a foundational data structure technique.</p>",
                "code_snippet": "def is_valid(s):\n    stack = []\n    mapping = {')': '(', ']': '[', '}': '{'}\n    for char in s:\n        if char in mapping:\n            top = stack.pop() if stack else '#'\n            if mapping[char] != top:\n                return False\n        else:\n            stack.append(char)\n    return not stack",
                "language": "python",
                "is_unlocked": false,
                "is_required": true,
                "order": 6,
            },
        ],
        "created_at": datetime.now(timezone.utc),
    },
    {
        "question_id": "binary-search",
        "title": "Binary Search — Divide and Conquer",
        "description": "Learn the fundamental binary search algorithm and its many variations.",
        "difficulty": "beginner",
        "estimated_time_minutes": 15,
        "topic": "search",
        "xp_reward": 50,
        "badge_reward": "Search Specialist",
        "company_tags": ["Amazon", "Google", "Meta", "TikTok", "Uber"],
        "steps": [
            {
                "step_number": 1,
                "type": "theory",
                "title": "The Power of Halving",
                "content": "<p><strong>Binary search</strong> is one of the most important algorithms in computer science. It works on <strong>sorted arrays</strong> by repeatedly dividing the search space in half.</p><p>Instead of checking each element one by one (O(n)), binary search achieves <strong>O(log n)</strong> — for a million elements, that's about 20 comparisons instead of 1,000,000!</p><p>The key invariant: maintain a search window [left, right] and shrink it by half each iteration.</p>",
                "code_snippet": null,
                "language": null,
                "is_unlocked": true,
                "is_required": true,
                "order": 1,
            },
            {
                "step_number": 2,
                "type": "example",
                "title": "Walkthrough",
                "content": "<p><strong>Search for 7 in [1, 3, 5, 7, 9, 11]:</strong></p><ol><li>left=0, right=5, mid=2 → nums[2]=5 → 5<7 → left=3</li><li>left=3, right=5, mid=4 → nums[4]=9 → 9>7 → right=3</li><li>left=3, right=3, mid=3 → nums[3]=7 → found! Return 3</li></ol><p>Only 3 steps instead of up to 6 with linear search.</p>",
                "code_snippet": null,
                "language": null,
                "is_unlocked": false,
                "is_required": true,
                "order": 2,
            },
            {
                "step_number": 3,
                "type": "example",
                "title": "Code Example — Python",
                "content": "<p>Standard binary search implementation:</p>",
                "code_snippet": "def binary_search(nums, target):\n    left, right = 0, len(nums) - 1\n    while left <= right:\n        mid = (left + right) // 2\n        if nums[mid] == target:\n            return mid\n        elif nums[mid] < target:\n            left = mid + 1\n        else:\n            right = mid - 1\n    return -1",
                "language": "python",
                "is_unlocked": false,
                "is_required": true,
                "order": 3,
            },
            {
                "step_number": 4,
                "type": "try_it",
                "title": "Try It Yourself",
                "content": "<p>Implement <code>binary_search</code>. Pay attention to the loop condition (<code>left &lt;= right</code>) and the update rules.</p>",
                "code_snippet": "def binary_search(nums, target):\n    # Your code here\n    pass",
                "language": "python",
                "is_unlocked": false,
                "is_required": true,
                "order": 4,
            },
            {
                "step_number": 5,
                "type": "hint",
                "title": "Common Mistakes",
                "content": "<ul><li><strong>Off-by-one errors</strong> — using <code>left &lt; right</code> instead of <code>left &lt;= right</code></li><li><strong>Integer overflow</strong> in mid calculation: use <code>mid = left + (right - left) // 2</code> in other languages</li><li><strong>Infinite loops</strong> — forgetting to update left/right</li><li><strong>Wrong update direction</strong> — when nums[mid] < target, move left up, not right</li></ul>",
                "code_snippet": null,
                "language": null,
                "is_unlocked": false,
                "is_required": false,
                "order": 5,
            },
            {
                "step_number": 6,
                "type": "solution",
                "title": "Solution & Review",
                "content": "<p><strong>Time Complexity:</strong> O(log n)</p><p><strong>Space Complexity:</strong> O(1)</p><p>Binary search variations you'll be asked about:</p><ul><li><strong>Find first/last occurrence</strong> — don't return on match, keep searching</li><li><strong>Search in rotated sorted array</strong> — determine which half is sorted</li><li><strong>Find peak element</strong> — compare mid with neighbors</li><li><strong>Binary search on answer space</strong> — use the algorithm on the SOLUTION, not the array</li></ul>",
                "code_snippet": "def binary_search(nums, target):\n    left, right = 0, len(nums) - 1\n    while left <= right:\n        mid = (left + right) // 2\n        if nums[mid] == target:\n            return mid\n        elif nums[mid] < target:\n            left = mid + 1\n        else:\n            right = mid - 1\n    return -1",
                "language": "python",
                "is_unlocked": false,
                "is_required": true,
                "order": 6,
            },
        ],
        "created_at": datetime.now(timezone.utc),
    },
    {
        "question_id": "reverse-linked-list",
        "title": "Reverse Linked List — Pointer Magic",
        "description": "Master in-place linked list reversal using the three-pointer technique.",
        "difficulty": "beginner",
        "estimated_time_minutes": 15,
        "topic": "linked-lists",
        "xp_reward": 50,
        "badge_reward": "Pointer Maestro",
        "company_tags": ["Amazon", "Google", "Microsoft", "Apple"],
        "steps": [
            {
                "step_number": 1,
                "type": "theory",
                "title": "The Three-Pointer Technique",
                "content": "<p>To reverse a linked list in-place, you need to change each node's <code>next</code> pointer to point to its <strong>previous</strong> node instead of its next node.</p><p>The challenge: you can't go backwards in a singly linked list. The solution: use <strong>three pointers</strong> to track the previous, current, and next nodes simultaneously.</p>",
                "code_snippet": null,
                "language": null,
                "is_unlocked": true,
                "is_required": true,
                "order": 1,
            },
            {
                "step_number": 2,
                "type": "example",
                "title": "Step-by-Step Walkthrough",
                "content": "<p><strong>Input:</strong> 1 → 2 → 3 → 4 → None</p><p><strong>Goal:</strong> None ← 1 ← 2 ← 3 ← 4</p><p><strong>Each iteration:</strong></p><ol><li><strong>Save next:</strong> next_node = current.next</li><li><strong>Reverse pointer:</strong> current.next = prev</li><li><strong>Advance prev:</strong> prev = current</li><li><strong>Advance current:</strong> current = next_node</li></ol><p>After 4 iterations, prev points to the new head (node 4).</p>",
                "code_snippet": null,
                "language": null,
                "is_unlocked": false,
                "is_required": true,
                "order": 2,
            },
            {
                "step_number": 3,
                "type": "example",
                "title": "Code Example — Python",
                "content": "<p>Clean iterative reversal:</p>",
                "code_snippet": "class ListNode:\n    def __init__(self, val=0, next=None):\n        self.val = val\n        self.next = next\n\ndef reverse_list(head):\n    prev = None\n    current = head\n    while current:\n        next_node = current.next\n        current.next = prev\n        prev = current\n        current = next_node\n    return prev",
                "language": "python",
                "is_unlocked": false,
                "is_required": true,
                "order": 3,
            },
            {
                "step_number": 4,
                "type": "try_it",
                "title": "Try It Yourself",
                "content": "<p>Implement <code>reverse_list</code>. Remember: save next before overwriting current.next!</p>",
                "code_snippet": "class ListNode:\n    def __init__(self, val=0, next=None):\n        self.val = val\n        self.next = next\n\ndef reverse_list(head):\n    # Your code here\n    pass",
                "language": "python",
                "is_unlocked": false,
                "is_required": true,
                "order": 4,
            },
            {
                "step_number": 5,
                "type": "hint",
                "title": "Common Mistakes",
                "content": "<ul><li><strong>Losing the reference to the rest of the list</strong> — always save next_node BEFORE changing current.next</li><li><strong>Forgetting to return prev</strong> — not head or current</li><li><strong>Not handling empty list</strong> — the while loop handles this naturally, but be aware</li><li><strong>Confusing iterative with recursive</strong> — iterative is preferred for O(1) space</li></ul>",
                "code_snippet": null,
                "language": null,
                "is_unlocked": false,
                "is_required": false,
                "order": 5,
            },
            {
                "step_number": 6,
                "type": "solution",
                "title": "Solution & Review",
                "content": "<p><strong>Time Complexity:</strong> O(n)</p><p><strong>Space Complexity:</strong> O(1) — in-place!</p><p>Linked list reversal is a fundamental operation used in many problems: <strong>palindrome checking, reordering lists, reversing sublists, LRU cache implementation</strong>. The three-pointer pattern is essential for all linked list manipulation.</p>",
                "code_snippet": "class ListNode:\n    def __init__(self, val=0, next=None):\n        self.val = val\n        self.next = next\n\ndef reverse_list(head):\n    prev = None\n    current = head\n    while current:\n        next_node = current.next\n        current.next = prev\n        prev = current\n        current = next_node\n    return prev",
                "language": "python",
                "is_unlocked": false,
                "is_required": true,
                "order": 6,
            },
        ],
        "created_at": datetime.now(timezone.utc),
    },
    {
        "question_id": "merge-sort",
        "title": "Merge Sort — The Divide Strategy",
        "description": "Understand the divide-and-conquer paradigm through merge sort.",
        "difficulty": "intermediate",
        "estimated_time_minutes": 25,
        "topic": "sorting",
        "xp_reward": 100,
        "badge_reward": "Divide & Conquer",
        "company_tags": ["Google", "Amazon", "Meta", "Microsoft", "Apple"],
        "steps": [
            {
                "step_number": 1,
                "type": "theory",
                "title": "Divide and Conquer",
                "content": "<p><strong>Merge Sort</strong> follows the divide-and-conquer paradigm with three steps:</p><ol><li><strong>Divide:</strong> Split the array into two halves</li><li><strong>Conquer:</strong> Recursively sort each half</li><li><strong>Combine:</strong> Merge the two sorted halves into one sorted array</li></ol><p>The merge step is where the magic happens — two sorted arrays can be merged in O(n) time using a two-pointer technique.</p><p><strong>Time:</strong> O(n log n) always — best, average, and worst case</p><p><strong>Space:</strong> O(n) for the temporary arrays</p>",
                "code_snippet": null,
                "language": null,
                "is_unlocked": true,
                "is_required": true,
                "order": 1,
            },
            {
                "step_number": 2,
                "type": "example",
                "title": "Walkthrough",
                "content": "<p><strong>Sorting [38, 27, 43, 3, 9, 82, 10]:</strong></p><ol><li>Split: [38, 27, 43, 3] | [9, 82, 10]</li><li>Split: [38, 27] | [43, 3] | [9, 82] | [10]</li><li>Split: [38] | [27] | [43] | [3] | [9] | [82] | [10]</li><li>Merge: [27, 38] | [3, 43] | [9, 82] | [10]</li><li>Merge: [3, 27, 38, 43] | [9, 10, 82]</li><li>Merge: [3, 9, 10, 27, 38, 43, 82]</li></ol>",
                "code_snippet": null,
                "language": null,
                "is_unlocked": false,
                "is_required": true,
                "order": 2,
            },
            {
                "step_number": 3,
                "type": "example",
                "title": "Code Example — Python",
                "content": "<p>Complete merge sort implementation:</p>",
                "code_snippet": "def merge_sort(arr):\n    if len(arr) <= 1:\n        return arr\n    mid = len(arr) // 2\n    left = merge_sort(arr[:mid])\n    right = merge_sort(arr[mid:])\n    return merge(left, right)\n\ndef merge(left, right):\n    result = []\n    i = j = 0\n    while i < len(left) and j < len(right):\n        if left[i] <= right[j]:\n            result.append(left[i])\n            i += 1\n        else:\n            result.append(right[j])\n            j += 1\n    result.extend(left[i:])\n    result.extend(right[j:])\n    return result",
                "language": "python",
                "is_unlocked": false,
                "is_required": true,
                "order": 3,
            },
            {
                "step_number": 4,
                "type": "try_it",
                "title": "Try It Yourself",
                "content": "<p>Implement <code>merge_sort</code> and its helper <code>merge</code> function.</p>",
                "code_snippet": "def merge_sort(arr):\n    # Your code here\n    pass\n\ndef merge(left, right):\n    # Your code here\n    pass",
                "language": "python",
                "is_unlocked": false,
                "is_required": true,
                "order": 4,
            },
            {
                "step_number": 5,
                "type": "hint",
                "title": "Common Mistakes",
                "content": "<ul><li><strong>Forgetting base case</strong> — arrays of length 0 or 1 are already sorted</li><li><strong>Off-by-one in mid</strong> — <code>len(arr) // 2</code> works for both even and odd lengths</li><li><strong>Not handling remaining elements</strong> in merge — always use extend at the end</li><li><strong>Creating new arrays at every level</strong> — this is normal for merge sort, but be aware of the O(n) space cost</li></ul>",
                "code_snippet": null,
                "language": null,
                "is_unlocked": false,
                "is_required": false,
                "order": 5,
            },
            {
                "step_number": 6,
                "type": "solution",
                "title": "Solution & Review",
                "content": "<p><strong>Time Complexity:</strong> O(n log n) — guaranteed, every case</p><p><strong>Space Complexity:</strong> O(n) — temporary arrays during merge</p><p><strong>Stability:</strong> Merge sort is stable (preserves relative order of equal elements)</p><p>Merge sort is the go-to when you need guaranteed O(n log n) performance. It's also the basis for <strong>counting inversions, external sorting (large files), and sorting linked lists</strong>.</p>",
                "code_snippet": "def merge_sort(arr):\n    if len(arr) <= 1:\n        return arr\n    mid = len(arr) // 2\n    left = merge_sort(arr[:mid])\n    right = merge_sort(arr[mid:])\n    return merge(left, right)\n\ndef merge(left, right):\n    result = []\n    i = j = 0\n    while i < len(left) and j < len(right):\n        if left[i] <= right[j]:\n            result.append(left[i])\n            i += 1\n        else:\n            result.append(right[j])\n            j += 1\n    result.extend(left[i:])\n    result.extend(right[j:])\n    return result",
                "language": "python",
                "is_unlocked": false,
                "is_required": true,
                "order": 6,
            },
        ],
        "created_at": datetime.now(timezone.utc),
    },
    {
        "question_id": "climbing-stairs",
        "title": "Climbing Stairs — DP Foundation",
        "description": "Discover dynamic programming through the classic climbing stairs problem.",
        "difficulty": "beginner",
        "estimated_time_minutes": 20,
        "topic": "dynamic-programming",
        "xp_reward": 75,
        "badge_reward": "DP Explorer",
        "company_tags": ["Amazon", "Google", "Facebook", "Microsoft", "Uber"],
        "steps": [
            {
                "step_number": 1,
                "type": "theory",
                "title": "Why Dynamic Programming?",
                "content": "<p><strong>Dynamic Programming (DP)</strong> solves complex problems by breaking them into overlapping subproblems and storing their solutions to avoid redundant computation.</p><p>The climbing stairs problem: You can climb 1 or 2 steps at a time. How many distinct ways to reach the top (n steps)?</p><p>The recurrence relation: <code>ways(n) = ways(n-1) + ways(n-2)</code></p><p>Why? From step n-1 you take 1 step, or from n-2 you take 2 steps. This is the <strong>Fibonacci sequence</strong>!</p>",
                "code_snippet": null,
                "language": null,
                "is_unlocked": true,
                "is_required": true,
                "order": 1,
            },
            {
                "step_number": 2,
                "type": "example",
                "title": "Walkthrough",
                "content": "<p><strong>n = 4:</strong></p><ol><li>ways(1) = 1 (only [1])</li><li>ways(2) = 2 ([1,1], [2])</li><li>ways(3) = ways(2) + ways(1) = 2 + 1 = 3 ([1,1,1],[2,1],[1,2])</li><li>ways(4) = ways(3) + ways(2) = 3 + 2 = 5</li></ol>",
                "code_snippet": null,
                "language": null,
                "is_unlocked": false,
                "is_required": true,
                "order": 2,
            },
            {
                "step_number": 3,
                "type": "example",
                "title": "Code Example — Python",
                "content": "<p>Bottom-up DP with O(1) space (just like Fibonacci):</p>",
                "code_snippet": "def climb_stairs(n):\n    if n <= 2:\n        return n\n    prev2 = 1\n    prev1 = 2\n    for i in range(3, n + 1):\n        current = prev1 + prev2\n        prev2 = prev1\n        prev1 = current\n    return prev1",
                "language": "python",
                "is_unlocked": false,
                "is_required": true,
                "order": 3,
            },
            {
                "step_number": 4,
                "type": "try_it",
                "title": "Try It Yourself",
                "content": "<p>Implement <code>climb_stairs</code> using the space-optimized bottom-up approach (no array needed — just two variables).</p>",
                "code_snippet": "def climb_stairs(n):\n    # Your code here\n    pass",
                "language": "python",
                "is_unlocked": false,
                "is_required": true,
                "order": 4,
            },
            {
                "step_number": 5,
                "type": "hint",
                "title": "Common Mistakes",
                "content": "<ul><li><strong>Using recursion without memoization</strong> — O(2^n) will time out for large n</li><li><strong>Off-by-one at the base case</strong> — ways(1)=1, ways(2)=2</li><li><strong>Using an array when O(1) space is sufficient</strong> — only keep the last two values</li></ul>",
                "code_snippet": null,
                "language": null,
                "is_unlocked": false,
                "is_required": false,
                "order": 5,
            },
            {
                "step_number": 6,
                "type": "solution",
                "title": "Solution & Review",
                "content": "<p><strong>Time Complexity:</strong> O(n)</p><p><strong>Space Complexity:</strong> O(1)</p><p>This is the foundation for many DP problems: <strong>House Robber, Coin Change, Longest Increasing Subsequence, Edit Distance, and more.</strong></p><p>DP problems follow a pattern: 1) Define the state, 2) Write the recurrence, 3) determine the base cases, 4) Choose top-down (memoization) or bottom-up (tabulation) approach.</p>",
                "code_snippet": "def climb_stairs(n):\n    if n <= 2:\n        return n\n    prev2 = 1\n    prev1 = 2\n    for i in range(3, n + 1):\n        current = prev1 + prev2\n        prev2 = prev1\n        prev1 = current\n    return prev1",
                "language": "python",
                "is_unlocked": false,
                "is_required": true,
                "order": 6,
            },
        ],
        "created_at": datetime.now(timezone.utc),
    },
    {
        "question_id": "binary-tree-inorder",
        "title": "Binary Tree Inorder — DFS Mastery",
        "description": "Master depth-first traversal of binary trees with inorder traversal.",
        "difficulty": "intermediate",
        "estimated_time_minutes": 25,
        "topic": "trees",
        "xp_reward": 100,
        "badge_reward": "Tree Voyager",
        "company_tags": ["Amazon", "Google", "Meta", "Microsoft", "Apple", "LinkedIn"],
        "steps": [
            {
                "step_number": 1,
                "type": "theory",
                "title": "Tree Traversals Explained",
                "content": "<p>A <strong>binary tree</strong> has three natural ways to traverse it depth-first:</p><ul><li><strong>Inorder (LNR):</strong> Left subtree → Node → Right subtree — gives sorted order for BSTs</li><li><strong>Preorder (NLR):</strong> Node → Left → Right — used for copying trees</li><li><strong>Postorder (LRN):</strong> Left → Right → Node — used for deletion</li></ul><p><strong>Inorder traversal</strong> is the most commonly asked. For a BST, it produces elements in ascending order.</p>",
                "code_snippet": null,
                "language": null,
                "is_unlocked": true,
                "is_required": true,
                "order": 1,
            },
            {
                "step_number": 2,
                "type": "example",
                "title": "Walkthrough",
                "content": "<p><strong>Tree:</strong></p><pre>    4\n   / \\\n  2   6\n / \\ / \\\n1  3 5  7</pre><p><strong>Inorder traversal:</strong> 1 → 2 → 3 → 4 → 5 → 6 → 7</p><p><strong>Process:</strong> Go left as far as possible, visit node, then go right.</p>",
                "code_snippet": null,
                "language": null,
                "is_unlocked": false,
                "is_required": true,
                "order": 2,
            },
            {
                "step_number": 3,
                "type": "example",
                "title": "Code Example — Python",
                "content": "<p>Recursive and iterative implementations:</p>",
                "code_snippet": "class TreeNode:\n    def __init__(self, val=0, left=None, right=None):\n        self.val = val\n        self.left = left\n        self.right = right\n\ndef inorder_recursive(root):\n    result = []\n    def dfs(node):\n        if not node:\n            return\n        dfs(node.left)\n        result.append(node.val)\n        dfs(node.right)\n    dfs(root)\n    return result\n\ndef inorder_iterative(root):\n    result = []\n    stack = []\n    current = root\n    while current or stack:\n        while current:\n            stack.append(current)\n            current = current.left\n        current = stack.pop()\n        result.append(current.val)\n        current = current.right\n    return result",
                "language": "python",
                "is_unlocked": false,
                "is_required": true,
                "order": 3,
            },
            {
                "step_number": 4,
                "type": "try_it",
                "title": "Try It Yourself",
                "content": "<p>Implement <code>inorder_traversal</code>. Start with the recursive approach, then try the iterative version.</p>",
                "code_snippet": "class TreeNode:\n    def __init__(self, val=0, left=None, right=None):\n        self.val = val\n        self.left = left\n        self.right = right\n\ndef inorder_traversal(root):\n    # Your code here\n    pass",
                "language": "python",
                "is_unlocked": false,
                "is_required": true,
                "order": 4,
            },
            {
                "step_number": 5,
                "type": "hint",
                "title": "Common Mistakes",
                "content": "<ul><li><strong>Forgetting the base case</strong> — <code>if not node: return</code></li><li><strong>Wrong order in traversal</strong> — inorder is Left, Node, Right (not preorder or postorder)</li><li><strong>Not understanding when iterative is needed</strong> — interviewers love the iterative version to test stack understanding</li></ul>",
                "code_snippet": null,
                "language": null,
                "is_unlocked": false,
                "is_required": false,
                "order": 5,
            },
            {
                "step_number": 6,
                "type": "solution",
                "title": "Solution & Review",
                "content": "<p><strong>Time Complexity:</strong> O(n) — visit each node once</p><p><strong>Space Complexity:</strong> O(h) where h is tree height (O(log n) for balanced, O(n) worst case)</p><p>DFS tree traversals are foundational for: <strong>path sum problems, subtree checks, serialization/deserialization, and tree-based DP</strong>.</p>",
                "code_snippet": "def inorder_traversal(root):\n    result = []\n    def dfs(node):\n        if not node:\n            return\n        dfs(node.left)\n        result.append(node.val)\n        dfs(node.right)\n    dfs(root)\n    return result",
                "language": "python",
                "is_unlocked": false,
                "is_required": true,
                "order": 6,
            },
        ],
        "created_at": datetime.now(timezone.utc),
    },
    {
        "question_id": "product-of-array-except-self",
        "title": "Product of Array Except Self — Prefix Sums",
        "description": "Master the prefix product technique for O(n) array problems without division.",
        "difficulty": "intermediate",
        "estimated_time_minutes": 25,
        "topic": "arrays",
        "xp_reward": 100,
        "badge_reward": "Prefix Pro",
        "company_tags": ["Amazon", "Google", "Meta", "Microsoft", "LinkedIn"],
        "steps": [
            {
                "step_number": 1,
                "type": "theory",
                "title": "Prefix Products — Beyond Sums",
                "content": "<p>The <strong>prefix sum</strong> technique can be extended to <strong>prefix products</strong>. For the 'Product of Array Except Self' problem, each output element = product of all elements to its left × product of all elements to its right.</p><p><strong>Key constraint:</strong> Solve it in O(n) time without using division!</p><p>The insight: compute prefix products from the left, then accumulate from the right in a single pass.</p>",
                "code_snippet": null,
                "language": null,
                "is_unlocked": true,
                "is_required": true,
                "order": 1,
            },
            {
                "step_number": 2,
                "type": "example",
                "title": "Walkthrough",
                "content": "<p><strong>Input:</strong> nums = [1, 2, 3, 4]</p><p><strong>Left products:</strong> [1, 1, 2, 6] — each is product of all elements to the left</p><p><strong>Right products:</strong> [24, 12, 4, 1] — each is product of all elements to the right</p><p><strong>Output:</strong> [1×24, 1×12, 2×4, 6×1] = [24, 12, 8, 6]</p><p>We can do this in O(1) extra space by using the output array and a running right product.</p>",
                "code_snippet": null,
                "language": null,
                "is_unlocked": false,
                "is_required": true,
                "order": 2,
            },
            {
                "step_number": 3,
                "type": "example",
                "title": "Code Example — Python",
                "content": "<p>Optimized O(n) time, O(1) extra space solution:</p>",
                "code_snippet": "def product_except_self(nums):\n    n = len(nums)\n    result = [1] * n\n    for i in range(1, n):\n        result[i] = result[i - 1] * nums[i - 1]\n    right_product = 1\n    for i in range(n - 1, -1, -1):\n        result[i] *= right_product\n        right_product *= nums[i]\n    return result",
                "language": "python",
                "is_unlocked": false,
                "is_required": true,
                "order": 3,
            },
            {
                "step_number": 4,
                "type": "try_it",
                "title": "Try It Yourself",
                "content": "<p>Implement <code>product_except_self</code>. Use the output array for prefix products and a single variable for the running suffix product.</p>",
                "code_snippet": "def product_except_self(nums):\n    # Your code here\n    pass",
                "language": "python",
                "is_unlocked": false,
                "is_required": true,
                "order": 4,
            },
            {
                "step_number": 5,
                "type": "hint",
                "title": "Common Mistakes",
                "content": "<ul><li><strong>Using division</strong> — fails on zeros and interviewers want to see you handle the constraint</li><li><strong>Off-by-one in prefix loop</strong> — start index for prefix is 1 (not 0)</li><li><strong>Forgetting to update right_product</strong> — multiply it by nums[i] after using it</li></ul>",
                "code_snippet": null,
                "language": null,
                "is_unlocked": false,
                "is_required": false,
                "order": 5,
            },
            {
                "step_number": 6,
                "type": "solution",
                "title": "Solution & Review",
                "content": "<p><strong>Time Complexity:</strong> O(n)</p><p><strong>Space Complexity:</strong> O(1) — excluding the output array</p><p>The prefix/suffix pattern extends to: <strong>prefix sums for range queries, prefix XOR for bit manipulation problems, and 2D prefix sums for matrix queries</strong>.</p>",
                "code_snippet": "def product_except_self(nums):\n    n = len(nums)\n    result = [1] * n\n    for i in range(1, n):\n        result[i] = result[i - 1] * nums[i - 1]\n    right_product = 1\n    for i in range(n - 1, -1, -1):\n        result[i] *= right_product\n        right_product *= nums[i]\n    return result",
                "language": "python",
                "is_unlocked": false,
                "is_required": true,
                "order": 6,
            },
        ],
        "created_at": datetime.now(timezone.utc),
    },
]


async def seed_learning_modules():
    db = get_db()
    collection = db["learning_modules"]

    for module_data in MODULES:
        existing = await collection.find_one({"question_id": module_data["question_id"]})
        if existing:
            await collection.update_one(
                {"question_id": module_data["question_id"]},
                {"$set": module_data},
            )
        else:
            await collection.insert_one(module_data)

    count = await collection.count_documents({})
    print(f"Seeded {count} learning modules")


if __name__ == "__main__":
    import asyncio
    asyncio.run(seed_learning_modules())