"""
Final batch of problems to reach 470+ total.
Additional problems for each pattern to ensure complete Striver's coverage.
"""

FINAL_PROBLEMS = [
    # Additional Two Pointers
    {"striver_id": "TP-F01", "topic": "Arrays", "topic_order": 1, "problem_order": 40, "question_title": "Two Sum II - Input Array Is Sorted", "statement": "Find two numbers that add up to target in a sorted array.", "examples": [{"input": "numbers = [2,7,11,15], target = 9", "output": "[1,2]"}], "constraints": ["2 <= numbers.length <= 3000"], "visible_test_cases": [{"input": "4 9\n2 7 11 15", "expected": "1 2"}], "hidden_test_cases": [{"input": "2 3\n1 2", "expected": "1 2"}], "solution": {"approach": "Two pointers from both ends.", "code": "def twoSum(numbers, target):\n    l, r = 0, len(numbers)-1\n    while l < r:\n        s = numbers[l] + numbers[r]\n        if s == target: return [l+1, r+1]\n        elif s < target: l += 1\n        else: r -= 1", "time_complexity": "O(n)", "space_complexity": "O(1)"}, "hints": ["Use two pointers from both ends."], "topics": ["Array", "Two Pointers"], "companies": ["Amazon", "Google"], "difficulty": "medium", "type": "coding", "role": "SDE"},
    {"striver_id": "TP-F02", "topic": "Arrays", "topic_order": 1, "problem_order": 41, "question_title": "3Sum Closest", "statement": "Find three integers whose sum is closest to target.", "examples": [{"input": "nums = [-1,2,1,-4], target = 1", "output": "2"}], "constraints": ["3 <= nums.length <= 500"], "visible_test_cases": [{"input": "4 1\n-1 2 1 -4", "expected": "2"}], "hidden_test_cases": [{"input": "3 0\n0 0 0", "expected": "0"}], "solution": {"approach": "Sort + two pointers.", "code": "def threeSumClosest(nums, target):\n    nums.sort()\n    closest = float('inf')\n    for i in range(len(nums)-2):\n        l, r = i+1, len(nums)-1\n        while l < r:\n            s = nums[i] + nums[l] + nums[r]\n            if abs(s-target) < abs(closest-target): closest = s\n            if s < target: l += 1\n            else: r -= 1\n    return closest", "time_complexity": "O(n^2)", "space_complexity": "O(1)"}, "hints": ["Sort first, then use two pointers."], "topics": ["Array", "Two Pointers"], "companies": ["Amazon"], "difficulty": "medium", "type": "coding", "role": "SDE"},

    # Additional Sliding Window
    {"striver_id": "SW-F01", "topic": "Sliding Window", "topic_order": 5, "problem_order": 73, "question_title": "Longest Substring with At Most K Distinct Characters", "statement": "Find the length of the longest substring with at most k distinct characters.", "examples": [{"input": "s = 'eceba', k = 2", "output": "3"}], "constraints": ["1 <= s.length <= 50000"], "visible_test_cases": [{"input": "eceba\n2", "expected": "3"}], "hidden_test_cases": [{"input": "aa\n1", "expected": "2"}, {"input": "a\n0", "expected": "0"}], "solution": {"approach": "Sliding window with hash map.", "code": "def lengthOfLongestSubstringKDistinct(s, k):\n    if k == 0: return 0\n    char_count = {}\n    left = 0\n    max_len = 0\n    for right in range(len(s)):\n        char_count[s[right]] = char_count.get(s[right], 0) + 1\n        while len(char_count) > k:\n            char_count[s[left]] -= 1\n            if char_count[s[left]] == 0: del char_count[s[left]]\n            left += 1\n        max_len = max(max_len, right - left + 1)\n    return max_len", "time_complexity": "O(n)", "space_complexity": "O(k)"}, "hints": ["Expand window, shrink when distinct > k."], "topics": ["Sliding Window", "Hash Table"], "companies": ["Amazon", "Google"], "difficulty": "medium", "type": "coding", "role": "SDE"},

    # Additional Fast & Slow Pointers
    {"striver_id": "FS-F01", "topic": "Linked Lists", "topic_order": 2, "problem_order": 23, "question_title": "Happy Number", "statement": "Determine if a number is happy (sum of squares of digits eventually equals 1).", "examples": [{"input": "n = 19", "output": "true"}, {"input": "n = 2", "output": "false"}], "constraints": ["1 <= n <= 2^31 - 1"], "visible_test_cases": [{"input": "19", "expected": "true"}, {"input": "2", "expected": "false"}], "hidden_test_cases": [{"input": "1", "expected": "true"}, {"input": "7", "expected": "true"}], "solution": {"approach": "Floyd's cycle detection.", "code": "def isHappy(n):\n    def get_next(num):\n        return sum(int(d)**2 for d in str(num))\n    slow = fast = n\n    while True:\n        slow = get_next(slow)\n        fast = get_next(get_next(fast))\n        if slow == fast: break\n    return slow == 1", "time_complexity": "O(log n)", "space_complexity": "O(1)"}, "hints": ["Use slow and fast pointers to detect cycle."], "topics": ["Hash Table", "Two Pointers"], "companies": ["Amazon", "Google"], "difficulty": "easy", "type": "coding", "role": "SDE"},

    # Additional Merge Intervals
    {"striver_id": "MI-F01", "topic": "Arrays", "topic_order": 1, "problem_order": 42, "question_title": "Insert Interval", "statement": "Insert a new interval into a list of non-overlapping intervals.", "examples": [{"input": "intervals = [[1,3],[6,9]], newInterval = [2,5]", "output": "[[1,5],[6,9]]"}], "constraints": ["0 <= intervals.length <= 10^4"], "visible_test_cases": [{"input": "2\n1 3\n6 9\n2 5", "expected": "1 5\n6 9"}], "hidden_test_cases": [{"input": "0\n1 5", "expected": "1 5"}, {"input": "1\n1 5\n2 3", "expected": "1 5"}], "solution": {"approach": "Add all before, merge overlapping, add remaining.", "code": "def insert(intervals, newInterval):\n    result = []\n    i = 0\n    while i < len(intervals) and intervals[i][1] < newInterval[0]:\n        result.append(intervals[i]); i += 1\n    while i < len(intervals) and intervals[i][0] <= newInterval[1]:\n        newInterval[0] = min(newInterval[0], intervals[i][0])\n        newInterval[1] = max(newInterval[1], intervals[i][1])\n        i += 1\n    result.append(newInterval)\n    while i < len(intervals):\n        result.append(intervals[i]); i += 1\n    return result", "time_complexity": "O(n)", "space_complexity": "O(n)"}, "hints": ["Add non-overlapping, merge overlapping."], "topics": ["Array", "Sorting"], "companies": ["Amazon", "Google"], "difficulty": "medium", "type": "coding", "role": "SDE"},

    # Additional Cyclic Sort
    {"striver_id": "CS-F01", "topic": "Arrays", "topic_order": 1, "problem_order": 43, "question_title": "Find All Numbers Disappeared in Array", "statement": "Find all elements in [1,n] that do not appear in the array.", "examples": [{"input": "nums = [4,3,2,7,8,2,3,1]", "output": "[5,6]"}], "constraints": ["1 <= nums.length <= 10^5"], "visible_test_cases": [{"input": "8\n4 3 2 7 8 2 3 1", "expected": "5 6"}], "hidden_test_cases": [{"input": "3\n1 1 2", "expected": "3"}], "solution": {"approach": "Cyclic sort: place each number at its correct index.", "code": "def findDisappearedNumbers(nums):\n    for num in nums:\n        idx = abs(num) - 1\n        if nums[idx] > 0: nums[idx] = -nums[idx]\n    return [i+1 for i in range(len(nums)) if nums[i] > 0]", "time_complexity": "O(n)", "space_complexity": "O(1)"}, "hints": ["Mark visited indices by negating."], "topics": ["Array"], "companies": ["Amazon"], "difficulty": "easy", "type": "coding", "role": "SDE"},

    # Additional In-place Reversal
    {"striver_id": "IR-F01", "topic": "Linked Lists", "topic_order": 2, "problem_order": 24, "question_title": "Swap Nodes in Pairs", "statement": "Swap every two adjacent nodes.", "examples": [{"input": "head = [1,2,3,4]", "output": "[2,1,4,3]"}], "constraints": ["0 <= n <= 100"], "visible_test_cases": [{"input": "4\n1 2 3 4", "expected": "2 1 4 3"}], "hidden_test_cases": [{"input": "1\n1", "expected": "1"}, {"input": "2\n1 2", "expected": "2 1"}], "solution": {"approach": "Iterative with dummy node.", "code": "def swapPairs(head):\n    dummy = ListNode(0, head)\n    prev = dummy\n    while prev.next and prev.next.next:\n        a = prev.next\n        b = a.next\n        prev.next = b\n        a.next = b.next\n        b.next = a\n        prev = a\n    return dummy.next", "time_complexity": "O(n)", "space_complexity": "O(1)"}, "hints": ["Use dummy node to handle edge cases."], "topics": ["Linked List"], "companies": ["Amazon", "Microsoft"], "difficulty": "easy", "type": "coding", "role": "SDE"},

    # Additional Tree BFS
    {"striver_id": "TBFS-F01", "topic": "Binary Trees", "topic_order": 4, "problem_order": 22, "question_title": "Binary Tree Maximum Width", "statement": "Find the maximum width of a binary tree.", "examples": [{"input": "root = [1,3,2,5,3,null,9]", "output": "4"}], "constraints": ["0 <= n <= 3000"], "visible_test_cases": [{"input": "1 3 2 5 3 null 9", "expected": "4"}], "hidden_test_cases": [{"input": "1", "expected": "1"}, {"input": "1 2 3", "expected": "2"}], "solution": {"approach": "BFS with index tracking.", "code": "from collections import deque\ndef widthOfBinaryTree(root):\n    if not root: return 0\n    max_width = 0\n    queue = deque([(root, 0)])\n    while queue:\n        size = len(queue)\n        _, first = queue[0]\n        for _ in range(size):\n            node, idx = queue.popleft()\n            if node.left: queue.append((node.left, 2*idx))\n            if node.right: queue.append((node.right, 2*idx+1))\n        max_width = max(max_width, idx - first + 1)\n    return max_width", "time_complexity": "O(n)", "space_complexity": "O(n)"}, "hints": ["Track index of each node."], "topics": ["Binary Tree", "BFS"], "companies": ["Amazon", "Google"], "difficulty": "medium", "type": "coding", "role": "SDE"},

    # Additional Tree DFS
    {"striver_id": "TDFS-F01", "topic": "Binary Trees", "topic_order": 4, "problem_order": 23, "question_title": "Path Sum III", "statement": "Count paths that sum to a target value.", "examples": [{"input": "root = [10,5,-3,3,2,null,11,3,-2,null,1], targetSum = 8", "output": "3"}], "constraints": ["1 <= n <= 1000"], "visible_test_cases": [{"input": "10 5 -3 3 2 null 11 3 -2 null 1\n8", "expected": "3"}], "hidden_test_cases": [{"input": "5\n5", "expected": "1"}], "solution": {"approach": "Prefix sum with hash map.", "code": "def pathSum(root, targetSum):\n    def dfs(node, curr_sum):\n        if not node: return 0\n        curr_sum += node.val\n        count = prefix.get(curr_sum - targetSum, 0)\n        prefix[curr_sum] = prefix.get(curr_sum, 0) + 1\n        count += dfs(node.left, curr_sum) + dfs(node.right, curr_sum)\n        prefix[curr_sum] -= 1\n        return count\n    prefix = {0: 1}\n    return dfs(root, 0)", "time_complexity": "O(n)", "space_complexity": "O(n)"}, "hints": ["Use prefix sum like subarray sum equals k."], "topics": ["Binary Tree", "DFS"], "companies": ["Amazon", "Google"], "difficulty": "medium", "type": "coding", "role": "SDE"},

    # Additional Graph BFS
    {"striver_id": "GBFS-F01", "topic": "Graphs", "topic_order": 5, "problem_order": 14, "question_title": "Open the Lock", "statement": "Find minimum moves to reach target lock combination.", "examples": [{"input": "deadends = ['0201','0101','0102','1212','2002'], target = '0202'", "output": "6"}], "constraints": ["1 <= deadends.length <= 500"], "visible_test_cases": [{"input": "5\n0201 0101 0102 1212 2002\n0202", "expected": "6"}], "hidden_test_cases": [{"input": "0\n0000", "expected": "0"}, {"input": "1\n8888\n0000", "expected": "-1"}], "solution": {"approach": "BFS on state space.", "code": "from collections import deque\ndef openLock(deadends, target):\n    dead = set(deadends)\n    if '0000' in dead: return -1\n    queue = deque([('0000', 0)])\n    visited = {'0000'}\n    while queue:\n        state, steps = queue.popleft()\n        if state == target: return steps\n        for i in range(4):\n            for d in [-1, 1]:\n                new_state = state[:i] + str((int(state[i])+d)%10) + state[i+1:]\n                if new_state not in visited and new_state not in dead:\n                    visited.add(new_state)\n                    queue.append((new_state, steps+1))\n    return -1", "time_complexity": "O(10000)", "space_complexity": "O(10000)"}, "hints": ["BFS on lock combinations."], "topics": ["Graph", "BFS"], "companies": ["Amazon", "Google"], "difficulty": "medium", "type": "coding", "role": "SDE"},

    # Additional Graph DFS
    {"striver_id": "GDFS-F01", "topic": "Graphs", "topic_order": 5, "problem_order": 15, "question_title": "Alien Dictionary", "statement": "Given sorted words, find the alien dictionary order.", "examples": [{"input": "words = ['wrt','wrf','er','ett','rftt']", "output": "wertf"}], "constraints": ["1 <= words.length <= 100"], "visible_test_cases": [{"input": "5\nwrt wrf er ett rftt", "expected": "wertf"}], "hidden_test_cases": [{"input": "2\na b", "expected": "ab"}, {"input": "2\nba ab", "expected": "bad"}], "solution": {"approach": "Build graph from character ordering, topological sort.", "code": "from collections import defaultdict, deque\ndef alienOrder(words):\n    adj = defaultdict(set)\n    in_degree = {c: 0 for word in words for c in word}\n    for i in range(len(words)-1):\n        w1, w2 = words[i], words[i+1]\n        min_len = min(len(w1), len(w2))\n        if len(w1) > len(w2) and w1[:min_len] == w2:\n            return ''\n        for c1, c2 in zip(w1, w2):\n            if c1 != c2:\n                if c2 not in adj[c1]:\n                    adj[c1].add(c2)\n                    in_degree[c2] += 1\n                break\n    queue = deque([c for c in in_degree if in_degree[c] == 0])\n    result = []\n    while queue:\n        c = queue.popleft()\n        result.append(c)\n        for neighbor in adj[c]:\n            in_degree[neighbor] -= 1\n            if in_degree[neighbor] == 0:\n                queue.append(neighbor)\n    return ''.join(result) if len(result) == len(in_degree) else ''", "time_complexity": "O(C)", "space_complexity": "O(C)"}, "hints": ["Compare adjacent words to find character ordering."], "topics": ["Graph", "Topological Sort"], "companies": ["Amazon", "Google", "Meta"], "difficulty": "hard", "type": "coding", "role": "SDE"},

    # Additional DP
    {"striver_id": "DP-F01", "topic": "Dynamic Programming", "topic_order": 6, "problem_order": 20, "question_title": "Unique Paths", "statement": "Count unique paths in a grid from top-left to bottom-right.", "examples": [{"input": "m = 3, n = 7", "output": "28"}], "constraints": ["1 <= m, n <= 100"], "visible_test_cases": [{"input": "3 7", "expected": "28"}], "hidden_test_cases": [{"input": "3 2", "expected": "3"}, {"input": "1 1", "expected": "1"}], "solution": {"approach": "DP: dp[i][j] = dp[i-1][j] + dp[i][j-1].", "code": "def uniquePaths(m, n):\n    dp = [[1]*n for _ in range(m)]\n    for i in range(1, m):\n        for j in range(1, n):\n            dp[i][j] = dp[i-1][j] + dp[i][j-1]\n    return dp[m-1][n-1]", "time_complexity": "O(m*n)", "space_complexity": "O(m*n)"}, "hints": ["Each cell = sum of cell above + cell to left."], "topics": ["Dynamic Programming", "Math"], "companies": ["Amazon", "Google"], "difficulty": "medium", "type": "coding", "role": "SDE"},
    {"striver_id": "DP-F02", "topic": "Dynamic Programming", "topic_order": 6, "problem_order": 21, "question_title": "Decode Ways", "statement": "Count ways to decode a string of digits to letters.", "examples": [{"input": "s = '226'", "output": "3"}], "constraints": ["1 <= s.length <= 100"], "visible_test_cases": [{"input": "226", "expected": "3"}], "hidden_test_cases": [{"input": "0", "expected": "0"}, {"input": "10", "expected": "1"}], "solution": {"approach": "DP: similar to climbing stairs.", "code": "def numDecodings(s):\n    if s[0] == '0': return 0\n    n = len(s)\n    dp = [0] * (n + 1)\n    dp[0] = dp[1] = 1\n    for i in range(2, n + 1):\n        if s[i-1] != '0': dp[i] += dp[i-1]\n        if 10 <= int(s[i-2:i]) <= 26: dp[i] += dp[i-2]\n    return dp[n]", "time_complexity": "O(n)", "space_complexity": "O(n)"}, "hints": ["Single digit (1-9) and double digit (10-26) decode."], "topics": ["Dynamic Programming", "String"], "companies": ["Amazon", "Google"], "difficulty": "medium", "type": "coding", "role": "SDE"},

    # Additional Backtracking
    {"striver_id": "BT-F01", "topic": "Recursion", "topic_order": 3, "problem_order": 49, "question_title": "Permutations", "statement": "Return all possible permutations of distinct integers.", "examples": [{"input": "nums = [1,2,3]", "output": "[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]"}], "constraints": ["1 <= nums.length <= 6"], "visible_test_cases": [{"input": "3\n1 2 3", "expected": "1 2 3\n1 3 2\n2 1 3\n2 3 1\n3 1 2\n3 2 1"}], "hidden_test_cases": [{"input": "1\n1", "expected": "1"}, {"input": "2\n1 2", "expected": "1 2\n2 1"}], "solution": {"approach": "Backtracking: swap elements.", "code": "def permute(nums):\n    result = []\n    def backtrack(start):\n        if start == len(nums):\n            result.append(nums[:])\n            return\n        for i in range(start, len(nums)):\n            nums[start], nums[i] = nums[i], nums[start]\n            backtrack(start + 1)\n            nums[start], nums[i] = nums[i], nums[start]\n    backtrack(0)\n    return result", "time_complexity": "O(n!)", "space_complexity": "O(n)"}, "hints": ["Swap each element with the current position."], "topics": ["Recursion", "Backtracking"], "companies": ["Amazon", "Google"], "difficulty": "medium", "type": "coding", "role": "SDE"},

    # Additional Monotonic Stack
    {"striver_id": "MS-F01", "topic": "Stacks & Queues", "topic_order": 3, "problem_order": 18, "question_title": "Asteroid Collision", "statement": "Simulate asteroid collisions and return surviving asteroids.", "examples": [{"input": "asteroids = [5,10,-5]", "output": "[5,10]"}], "constraints": ["2 <= asteroids.length <= 10^4"], "visible_test_cases": [{"input": "3\n5 10 -5", "expected": "5 10"}], "hidden_test_cases": [{"input": "2\n8 -8", "expected": ""}, {"input": "3\n10 2 -5", "expected": "10"}], "solution": {"approach": "Stack: push right-moving, handle collisions.", "code": "def asteroidCollision(asteroids):\n    stack = []\n    for a in asteroids:\n        while stack and a < 0 and stack[-1] > 0:\n            if stack[-1] < -a: stack.pop()\n            elif stack[-1] == -a: stack.pop(); break\n            else: break\n        else: stack.append(a)\n    return stack", "time_complexity": "O(n)", "space_complexity": "O(n)"}, "hints": ["Use stack to track surviving asteroids."], "topics": ["Stack", "Array"], "companies": ["Amazon", "Google"], "difficulty": "medium", "type": "coding", "role": "SDE"},

    # Additional Heap
    {"striver_id": "HP-F01", "topic": "Heaps", "topic_order": 5, "problem_order": 69, "question_title": "Task Scheduler", "statement": "Find least intervals to complete all tasks with cooldown.", "examples": [{"input": "tasks = ['A','A','A','B','B','B'], n = 2", "output": "8"}], "constraints": ["1 <= tasks.length <= 10^4"], "visible_test_cases": [{"input": "6 2\nA A A B B B", "expected": "8"}], "hidden_test_cases": [{"input": "1 0\nA", "expected": "1"}, {"input": "3 1\nA B A", "expected": "5"}], "solution": {"approach": "Greedy with max-heap.", "code": "from collections import Counter\nimport heapq\ndef leastInterval(tasks, n):\n    count = Counter(tasks)\n    heap = [-c for c in count.values()]\n    heapq.heapify(heap)\n    time = 0\n    while heap:\n        cycle = []\n        for _ in range(n + 1):\n            if heap:\n                cycle.append(heapq.heappop(heap) + 1)\n        for cnt in cycle:\n            if cnt < 0: heapq.heappush(heap, cnt)\n        time += n + 1 if heap else len(cycle)\n    return time", "time_complexity": "O(n log n)", "space_complexity": "O(n)"}, "hints": ["Process most frequent tasks first."], "topics": ["Heap", "Greedy"], "companies": ["Amazon", "Google"], "difficulty": "medium", "type": "coding", "role": "SDE"},

    # Additional Greedy
    {"striver_id": "GR-F01", "topic": "Greedy", "topic_order": 7, "problem_order": 7, "question_title": "Jump Game II", "statement": "Find minimum jumps to reach the last index.", "examples": [{"input": "nums = [2,3,1,1,4]", "output": "2"}], "constraints": ["1 <= nums.length <= 10^4"], "visible_test_cases": [{"input": "5\n2 3 1 1 4", "expected": "2"}], "hidden_test_cases": [{"input": "3\n2 3 1", "expected": "1"}], "solution": {"approach": "BFS-like greedy.", "code": "def jump(nums):\n    jumps = 0\n    current_end = 0\n    farthest = 0\n    for i in range(len(nums) - 1):\n        farthest = max(farthest, i + nums[i])\n        if i == current_end:\n            jumps += 1\n            current_end = farthest\n    return jumps", "time_complexity": "O(n)", "space_complexity": "O(1)"}, "hints": ["Track the farthest reachable at each step."], "topics": ["Greedy", "Array"], "companies": ["Amazon", "Google"], "difficulty": "medium", "type": "coding", "role": "SDE"},

    # Additional Binary Search
    {"striver_id": "BS-F01", "topic": "Binary Search", "topic_order": 1, "problem_order": 31, "question_title": "Find Minimum in Rotated Sorted Array", "statement": "Find the minimum element in a rotated sorted array.", "examples": [{"input": "nums = [3,4,5,1,2]", "output": "1"}], "constraints": ["1 <= n <= 5000"], "visible_test_cases": [{"input": "5\n3 4 5 1 2", "expected": "1"}], "hidden_test_cases": [{"input": "1\n1", "expected": "1"}, {"input": "2\n2 1", "expected": "1"}], "solution": {"approach": "Binary search: compare mid with right.", "code": "def findMin(nums):\n    lo, hi = 0, len(nums) - 1\n    while lo < hi:\n        mid = (lo + hi) // 2\n        if nums[mid] > nums[hi]:\n            lo = mid + 1\n        else:\n            hi = mid\n    return nums[lo]", "time_complexity": "O(log n)", "space_complexity": "O(1)"}, "hints": ["Minimum is in the unsorted half."], "topics": ["Binary Search"], "companies": ["Amazon", "Microsoft"], "difficulty": "medium", "type": "coding", "role": "SDE"},

    # Additional Tries
    {"striver_id": "TR-F01", "topic": "Tries", "topic_order": 8, "problem_order": 91, "question_title": "Design Add and Search Words Data Structure", "statement": "Design a data structure for adding words and searching with wildcards.", "examples": [{"input": "addWord('bad'), addWord('dad'), search('bad'), search('.ad'), search('b..')", "output": "true, true, true"}], "constraints": ["1 <= word.length <= 25"], "visible_test_cases": [{"input": "add bad\nadd dad\nsearch bad\nsearch .ad\nsearch b..", "expected": "true\ntrue\ntrue"}], "hidden_test_cases": [{"input": "add a\nsearch a\nsearch .", "expected": "true\ntrue"}], "solution": {"approach": "Trie with DFS for wildcard search.", "code": "class WordDictionary:\n    def __init__(self):\n        self.children = {}\n        self.is_end = False\n    def addWord(self, word):\n        node = self\n        for c in word:\n            if c not in node.children:\n                node.children[c] = WordDictionary()\n            node = node.children[c]\n        node.is_end = True\n    def search(self, word):\n        node = self\n        for i, c in enumerate(word):\n            if c == '.':\n                return any(node.children[ch].search(word[i+1:]) for ch in node.children)\n            if c not in node.children: return False\n            node = node.children[c]\n        return node.is_end", "time_complexity": "O(26^m)", "space_complexity": "O(m)"}, "hints": ["Use DFS for '.' wildcard."], "topics": ["Trie", "DFS"], "companies": ["Amazon", "Google"], "difficulty": "medium", "type": "coding", "role": "SDE"},
]
