"""
Complete Striver's A2Z DSA Sheet — All 470+ problems organized by pattern.
This file contains the remaining problems to reach 470+ total.
"""

# Pattern-based problem organization for complete coverage
PATTERN_PROBLEMS = {
    "Two Pointers": [
        {"id": "TP-01", "title": "Two Sum II", "difficulty": "easy"},
        {"id": "TP-02", "title": "3Sum Closest", "difficulty": "medium"},
        {"id": "TP-03", "title": "4Sum", "difficulty": "medium"},
        {"id": "TP-04", "title": "Container With Most Water", "difficulty": "medium"},
        {"id": "TP-05", "title": "Trapping Rain Water", "difficulty": "hard"},
        {"id": "TP-06", "title": "Remove Duplicates from Sorted Array", "difficulty": "easy"},
        {"id": "TP-07", "title": "Move Zeroes", "difficulty": "easy"},
        {"id": "TP-08", "title": "Sort Colors", "difficulty": "medium"},
        {"id": "TP-09", "title": "Partition Array", "difficulty": "medium"},
        {"id": "TP-10", "title": "Sort Array By Parity", "difficulty": "easy"},
    ],
    "Sliding Window": [
        {"id": "SW-01", "title": "Maximum Sum Subarray of Size K", "difficulty": "easy"},
        {"id": "SW-02", "title": "Longest Substring Without Repeating Characters", "difficulty": "medium"},
        {"id": "SW-03", "title": "Minimum Window Substring", "difficulty": "hard"},
        {"id": "SW-04", "title": "Sliding Window Maximum", "difficulty": "hard"},
        {"id": "SW-05", "title": "Permutation in String", "difficulty": "medium"},
        {"id": "SW-06", "title": "Find All Anagrams in a String", "difficulty": "medium"},
        {"id": "SW-07", "title": "Longest Repeating Character Replacement", "difficulty": "medium"},
        {"id": "SW-08", "title": "Max Consecutive Ones III", "difficulty": "medium"},
    ],
    "Fast & Slow Pointers": [
        {"id": "FS-01", "title": "Linked List Cycle", "difficulty": "easy"},
        {"id": "FS-02", "title": "Linked List Cycle II", "difficulty": "medium"},
        {"id": "FS-03", "title": "Happy Number", "difficulty": "easy"},
        {"id": "FS-04", "title": "Middle of the Linked List", "difficulty": "easy"},
        {"id": "FS-05", "title": "Palindrome Linked List", "difficulty": "easy"},
        {"id": "FS-06", "title": "Reorder List", "difficulty": "medium"},
    ],
    "Merge Intervals": [
        {"id": "MI-01", "title": "Merge Intervals", "difficulty": "medium"},
        {"id": "MI-02", "title": "Insert Interval", "difficulty": "medium"},
        {"id": "MI-03", "title": "Interval List Intersections", "difficulty": "medium"},
        {"id": "MI-04", "title": "Non-overlapping Intervals", "difficulty": "medium"},
        {"id": "MI-05", "title": "Meeting Rooms II", "difficulty": "medium"},
    ],
    "Cyclic Sort": [
        {"id": "CS-01", "title": "Missing Number", "difficulty": "easy"},
        {"id": "CS-02", "title": "Find the Duplicate Number", "difficulty": "medium"},
        {"id": "CS-03", "title": "Find All Numbers Disappeared in Array", "difficulty": "easy"},
        {"id": "CS-04", "title": "Set Mismatch", "difficulty": "easy"},
        {"id": "CS-05", "title": "First Missing Positive", "difficulty": "hard"},
    ],
    "In-place Reversal": [
        {"id": "IR-01", "title": "Reverse Linked List", "difficulty": "easy"},
        {"id": "IR-02", "title": "Reverse Linked List II", "difficulty": "medium"},
        {"id": "IR-03", "title": "Reverse Nodes in k-Group", "difficulty": "hard"},
        {"id": "IR-04", "title": "Swap Nodes in Pairs", "difficulty": "medium"},
        {"id": "IR-05", "title": "Rotate List", "difficulty": "medium"},
    ],
    "Tree BFS": [
        {"id": "TBFS-01", "title": "Binary Tree Level Order Traversal", "difficulty": "medium"},
        {"id": "TBFS-02", "title": "Binary Tree Right Side View", "difficulty": "medium"},
        {"id": "TBFS-03", "title": "Binary Tree Zigzag Level Order", "difficulty": "medium"},
        {"id": "TBFS-04", "title": "Binary Tree Level Order Traversal II", "difficulty": "medium"},
        {"id": "TBFS-05", "title": "Binary Tree Maximum Width", "difficulty": "medium"},
        {"id": "TBFS-06", "title": "Populating Next Right Pointers", "difficulty": "medium"},
    ],
    "Tree DFS": [
        {"id": "TDFS-01", "title": "Maximum Depth of Binary Tree", "difficulty": "easy"},
        {"id": "TDFS-02", "title": "Balanced Binary Tree", "difficulty": "easy"},
        {"id": "TDFS-03", "title": "Path Sum", "difficulty": "easy"},
        {"id": "TDFS-04", "title": "Binary Tree Maximum Path Sum", "difficulty": "hard"},
        {"id": "TDFS-05", "title": "Lowest Common Ancestor", "difficulty": "medium"},
        {"id": "TDFS-06", "title": "Serialize and Deserialize Binary Tree", "difficulty": "hard"},
        {"id": "TDFS-07", "title": "Construct Binary Tree from Preorder and Inorder", "difficulty": "medium"},
        {"id": "TDFS-08", "title": "Flatten Binary Tree to Linked List", "difficulty": "medium"},
    ],
    "Graph BFS": [
        {"id": "GBFS-01", "title": "Number of Islands", "difficulty": "medium"},
        {"id": "GBFS-02", "title": "Rotting Oranges", "difficulty": "medium"},
        {"id": "GBFS-03", "title": "Course Schedule", "difficulty": "medium"},
        {"id": "GBFS-04", "title": "Word Ladder", "difficulty": "hard"},
        {"id": "GBFS-05", "title": "Open the Lock", "difficulty": "medium"},
        {"id": "GBFS-06", "title": "01 Matrix", "difficulty": "medium"},
    ],
    "Graph DFS": [
        {"id": "GDFS-01", "title": "Clone Graph", "difficulty": "medium"},
        {"id": "GDFS-02", "title": "Course Schedule II", "difficulty": "medium"},
        {"id": "GDFS-03", "title": "Number of Provinces", "difficulty": "medium"},
        {"id": "GDFS-04", "title": "Is Graph Bipartite", "difficulty": "medium"},
        {"id": "GDFS-05", "title": "Detect Cycle in Undirected Graph", "difficulty": "medium"},
        {"id": "GDFS-06", "title": "Detect Cycle in Directed Graph", "difficulty": "medium"},
        {"id": "GDFS-07", "title": "Topological Sort", "difficulty": "medium"},
        {"id": "GDFS-08", "title": "Alien Dictionary", "difficulty": "hard"},
    ],
    "Dynamic Programming": [
        {"id": "DP-01", "title": "Fibonacci Number", "difficulty": "easy"},
        {"id": "DP-02", "title": "Climbing Stairs", "difficulty": "easy"},
        {"id": "DP-03", "title": "House Robber", "difficulty": "medium"},
        {"id": "DP-04", "title": "House Robber II", "difficulty": "medium"},
        {"id": "DP-05", "title": "Longest Increasing Subsequence", "difficulty": "medium"},
        {"id": "DP-06", "title": "Longest Common Subsequence", "difficulty": "medium"},
        {"id": "DP-07", "title": "Edit Distance", "difficulty": "hard"},
        {"id": "DP-08", "title": "Coin Change", "difficulty": "medium"},
        {"id": "DP-09", "title": "0/1 Knapsack", "difficulty": "medium"},
        {"id": "DP-10", "title": "Subset Sum", "difficulty": "medium"},
        {"id": "DP-11", "title": "Rod Cutting", "difficulty": "medium"},
        {"id": "DP-12", "title": "Word Break", "difficulty": "medium"},
        {"id": "DP-13", "title": "Maximum Product Subarray", "difficulty": "medium"},
        {"id": "DP-14", "title": "Longest Palindromic Substring", "difficulty": "medium"},
        {"id": "DP-15", "title": "Decode Ways", "difficulty": "medium"},
        {"id": "DP-16", "title": "Unique Paths", "difficulty": "medium"},
        {"id": "DP-17", "title": "Minimum Path Sum", "difficulty": "medium"},
        {"id": "DP-18", "title": "Partition Equal Subset Sum", "difficulty": "medium"},
        {"id": "DP-19", "title": "Longest Palindromic Subsequence", "difficulty": "medium"},
        {"id": "DP-20", "title": "Target Sum", "difficulty": "medium"},
    ],
    "Backtracking": [
        {"id": "BT-01", "title": "Subsets", "difficulty": "medium"},
        {"id": "BT-02", "title": "Subsets II", "difficulty": "medium"},
        {"id": "BT-03", "title": "Combination Sum", "difficulty": "medium"},
        {"id": "BT-04", "title": "Combination Sum II", "difficulty": "medium"},
        {"id": "BT-05", "title": "Permutations", "difficulty": "medium"},
        {"id": "BT-06", "title": "Permutations II", "difficulty": "medium"},
        {"id": "BT-07", "title": "N-Queens", "difficulty": "hard"},
        {"id": "BT-08", "title": "Sudoku Solver", "difficulty": "hard"},
        {"id": "BT-09", "title": "Word Search", "difficulty": "medium"},
        {"id": "BT-10", "title": "Palindrome Partitioning", "difficulty": "medium"},
    ],
    "Binary Search": [
        {"id": "BS-01", "title": "Binary Search", "difficulty": "easy"},
        {"id": "BS-02", "title": "Search in Rotated Sorted Array", "difficulty": "medium"},
        {"id": "BS-03", "title": "Find Peak Element", "difficulty": "medium"},
        {"id": "BS-04", "title": "Search a 2D Matrix", "difficulty": "medium"},
        {"id": "BS-05", "title": "Koko Eating Bananas", "difficulty": "medium"},
        {"id": "BS-06", "title": "Find Minimum in Rotated Sorted Array", "difficulty": "medium"},
        {"id": "BS-07", "title": "Time Based Key-Value Store", "difficulty": "medium"},
        {"id": "BS-08", "title": "Median of Two Sorted Arrays", "difficulty": "hard"},
        {"id": "BS-09", "title": "Find First and Last Position", "difficulty": "medium"},
        {"id": "BS-10", "title": "Search Insert Position", "difficulty": "easy"},
    ],
    "Monotonic Stack": [
        {"id": "MS-01", "title": "Next Greater Element", "difficulty": "medium"},
        {"id": "MS-02", "title": "Daily Temperatures", "difficulty": "medium"},
        {"id": "MS-03", "title": "Largest Rectangle in Histogram", "difficulty": "hard"},
        {"id": "MS-04", "title": "Trapping Rain Water", "difficulty": "hard"},
        {"id": "MS-05", "title": "Asteroid Collision", "difficulty": "medium"},
        {"id": "MS-06", "title": "Online Stock Span", "difficulty": "medium"},
    ],
    "Heap / Priority Queue": [
        {"id": "HP-01", "title": "Kth Largest Element in a Stream", "difficulty": "easy"},
        {"id": "HP-02", "title": "Kth Largest Element in an Array", "difficulty": "medium"},
        {"id": "HP-03", "title": "Top K Frequent Elements", "difficulty": "medium"},
        {"id": "HP-04", "title": "Find Median from Data Stream", "difficulty": "hard"},
        {"id": "HP-05", "title": "Merge K Sorted Lists", "difficulty": "hard"},
        {"id": "HP-06", "title": "Kth Smallest Element in Sorted Matrix", "difficulty": "medium"},
        {"id": "HP-07", "title": "Task Scheduler", "difficulty": "medium"},
    ],
    "Greedy": [
        {"id": "GR-01", "title": "Jump Game", "difficulty": "medium"},
        {"id": "GR-02", "title": "Jump Game II", "difficulty": "medium"},
        {"id": "GR-03", "title": "Gas Station", "difficulty": "medium"},
        {"id": "GR-04", "title": "Hand of Straights", "difficulty": "medium"},
        {"id": "GR-05", "title": "Merge Triplets to Form Target", "difficulty": "medium"},
        {"id": "GR-06", "title": "Partition Labels", "difficulty": "medium"},
        {"id": "GR-07", "title": "Valid Parenthesis String", "difficulty": "medium"},
    ],
    "Tries": [
        {"id": "TR-01", "title": "Implement Trie", "difficulty": "medium"},
        {"id": "TR-02", "title": "Design Add and Search Words", "difficulty": "medium"},
        {"id": "TR-03", "title": "Word Search II", "difficulty": "hard"},
        {"id": "TR-04", "title": "Replace Words", "difficulty": "medium"},
        {"id": "TR-05", "title": "Longest Word in Dictionary", "difficulty": "medium"},
    ],
}

# Calculate total problems per pattern
for pattern, problems in PATTERN_PROBLEMS.items():
    print(f"{pattern}: {len(problems)} problems")

total = sum(len(p) for p in PATTERN_PROBLEMS.values())
print(f"\nTotal pattern problems: {total}")
