"""
Additional Striver's A2Z problems to reach 470+ total.
More problems for each topic to ensure complete coverage.
"""

EXTRA_PROBLEMS = [
    # More Arrays
    {"striver_id": "A1-31", "topic": "Arrays", "topic_order": 1, "problem_order": 31, "question_title": "Sort Colors", "statement": "Sort an array of 0s, 1s, and 2s in a single pass.", "examples": [{"input": "nums = [2,0,2,1,1,0]", "output": "[0,0,1,1,2,2]"}], "constraints": ["1 <= nums.length <= 300"], "visible_test_cases": [{"input": "6\n2 0 2 1 1 0", "expected": "0 0 1 1 2 2"}], "hidden_test_cases": [{"input": "2\n0 1", "expected": "0 1"}, {"input": "1\n2", "expected": "2"}], "solution": {"approach": "Dutch National Flag: three pointers.", "code": "def sortColors(nums):\n    lo, mid, hi = 0, 0, len(nums)-1\n    while mid <= hi:\n        if nums[mid] == 0: nums[lo], nums[mid] = nums[mid], nums[lo]; lo += 1; mid += 1\n        elif nums[mid] == 1: mid += 1\n        else: nums[mid], nums[hi] = nums[hi], nums[mid]; hi -= 1", "time_complexity": "O(n)", "space_complexity": "O(1)"}, "hints": ["Use three pointers for 0, 1, 2 regions."], "topics": ["Array", "Two Pointers"], "companies": ["Amazon", "Microsoft"], "difficulty": "medium", "type": "coding", "role": "SDE"},
    {"striver_id": "A1-32", "topic": "Arrays", "topic_order": 1, "problem_order": 32, "question_title": "Subarray with Given XOR", "statement": "Find number of subarrays with given XOR k.", "examples": [{"input": "arr = [4,2,2,6,4], k = 6", "output": "4"}], "constraints": ["1 <= n <= 10^5"], "visible_test_cases": [{"input": "5 6\n4 2 2 6 4", "expected": "4"}], "hidden_test_cases": [{"input": "3 0\n1 1 1", "expected": "3"}, {"input": "1 5\n5", "expected": "1"}], "solution": {"approach": "Prefix XOR + hash map.", "code": "def subarrayXor(arr, k):\n    count = 0\n    prefix_xor = 0\n    seen = {0: 1}\n    for num in arr:\n        prefix_xor ^= num\n        if prefix_xor ^ k in seen:\n            count += seen[prefix_xor ^ k]\n        seen[prefix_xor] = seen.get(prefix_xor, 0) + 1\n    return count", "time_complexity": "O(n)", "space_complexity": "O(n)"}, "hints": ["Use prefix XOR like prefix sum."], "topics": ["Array", "Hash Table"], "companies": ["Amazon"], "difficulty": "medium", "type": "coding", "role": "SDE"},

    # More Linked Lists
    {"striver_id": "LL-21", "topic": "Linked Lists", "topic_order": 2, "problem_order": 21, "question_title": "Add Two Numbers", "statement": "Add two numbers represented as linked lists.", "examples": [{"input": "l1 = [2,4,3], l2 = [5,6,4]", "output": "[7,0,8]"}], "constraints": ["1 <= l1.length, l2.length <= 100"], "visible_test_cases": [{"input": "3\n2 4 3\n3\n5 6 4", "expected": "7 0 8"}], "hidden_test_cases": [{"input": "1\n0\n1\n0", "expected": "0"}, {"input": "3\n9 9 9\n3\n9 9 9", "expected": "9 9 9 8"}], "solution": {"approach": "Simulate digit-by-digit addition with carry.", "code": "def addTwoNumbers(l1, l2):\n    dummy = ListNode(0)\n    curr = dummy\n    carry = 0\n    while l1 or l2 or carry:\n        val = carry\n        if l1: val += l1.val; l1 = l1.next\n        if l2: val += l2.val; l2 = l2.next\n        carry = val // 10\n        curr.next = ListNode(val % 10)\n        curr = curr.next\n    return dummy.next", "time_complexity": "O(max(m,n))", "space_complexity": "O(max(m,n))"}, "hints": ["Handle carry between digits."], "topics": ["Linked List", "Math"], "companies": ["Amazon", "Google"], "difficulty": "medium", "type": "coding", "role": "SDE"},
    {"striver_id": "LL-22", "topic": "Linked Lists", "topic_order": 2, "problem_order": 22, "question_title": "Remove Nth Node From End", "statement": "Remove the nth node from the end of a linked list.", "examples": [{"input": "head = [1,2,3,4,5], n = 2", "output": "[1,2,3,5]"}], "constraints": ["1 <= n <= size"], "visible_test_cases": [{"input": "5 2\n1 2 3 4 5", "expected": "1 2 3 5"}], "hidden_test_cases": [{"input": "1 1\n1", "expected": ""}, {"input": "2 1\n1 2", "expected": "1"}], "solution": {"approach": "Two pointers with n gap.", "code": "def removeNthFromEnd(head, n):\n    dummy = ListNode(0, head)\n    fast = slow = dummy\n    for _ in range(n+1): fast = fast.next\n    while fast:\n        fast = fast.next\n        slow = slow.next\n    slow.next = slow.next.next\n    return dummy.next", "time_complexity": "O(L)", "space_complexity": "O(1)"}, "hints": ["Advance fast pointer n steps ahead."], "topics": ["Linked List", "Two Pointers"], "companies": ["Amazon", "Google"], "difficulty": "medium", "type": "coding", "role": "SDE"},

    # More Trees
    {"striver_id": "BT-21", "topic": "Binary Trees", "topic_order": 4, "problem_order": 21, "question_title": "Zigzag Level Order Traversal", "statement": "Return zigzag level order traversal of binary tree.", "examples": [{"input": "root = [3,9,20,null,null,15,7]", "output": "[[3],[20,9],[15,7]]"}], "constraints": ["0 <= n <= 2000"], "visible_test_cases": [{"input": "3 9 20 null null 15 7", "expected": "3\n20 9\n15 7"}], "hidden_test_cases": [{"input": "empty", "expected": ""}, {"input": "1", "expected": "1"}], "solution": {"approach": "BFS with alternating direction.", "code": "from collections import deque\ndef zigzagLevelOrder(root):\n    if not root: return []\n    result = []\n    queue = deque([root])\n    left_to_right = True\n    while queue:\n        level = []\n        for _ in range(len(queue)):\n            node = queue.popleft()\n            if left_to_right: level.append(node.val)\n            else: level.insert(0, node.val)\n            if node.left: queue.append(node.left)\n            if node.right: queue.append(node.right)\n        result.append(level)\n        left_to_right = not left_to_right\n    return result", "time_complexity": "O(n)", "space_complexity": "O(n)"}, "hints": ["Use BFS, alternate direction each level."], "topics": ["Binary Tree", "BFS"], "companies": ["Amazon", "Microsoft"], "difficulty": "medium", "type": "coding", "role": "SDE"},

    # More Graphs
    {"striver_id": "GR-13", "topic": "Graphs", "topic_order": 5, "problem_order": 13, "question_title": "Number of Islands", "statement": "Count the number of islands in a 2D grid.", "examples": [{"input": "grid = [['1','1','0'],['1','1','0'],['0','0','1']]", "output": "2"}], "constraints": ["1 <= m, n <= 300"], "visible_test_cases": [{"input": "3 3\n1 1 0\n1 1 0\n0 0 1", "expected": "2"}], "hidden_test_cases": [{"input": "1 1\n1", "expected": "1"}, {"input": "2 2\n0 0\n0 0", "expected": "0"}], "solution": {"approach": "DFS/BFS to mark visited cells.", "code": "def numIslands(grid):\n    if not grid: return 0\n    count = 0\n    for i in range(len(grid)):\n        for j in range(len(grid[0])):\n            if grid[i][j] == '1':\n                count += 1\n                dfs(grid, i, j)\n    return count\ndef dfs(grid, i, j):\n    if i < 0 or j < 0 or i >= len(grid) or j >= len(grid[0]) or grid[i][j] != '1': return\n    grid[i][j] = '0'\n    dfs(grid, i+1, j); dfs(grid, i-1, j); dfs(grid, i, j+1); dfs(grid, i, j-1)", "time_complexity": "O(m*n)", "space_complexity": "O(m*n)"}, "hints": ["Count connected components using DFS."], "topics": ["Graph", "DFS"], "companies": ["Amazon", "Google"], "difficulty": "medium", "type": "coding", "role": "SDE"},

    # More DP
    {"striver_id": "DP-19", "topic": "Dynamic Programming", "topic_order": 6, "problem_order": 19, "question_title": "Longest Common Substring", "statement": "Find the length of the longest common substring.", "examples": [{"input": "s1 = 'abcde', s2 = 'abfce'", "output": "2"}], "constraints": ["1 <= s1.length, s2.length <= 1000"], "visible_test_cases": [{"input": "abcde\nabfce", "expected": "2"}], "hidden_test_cases": [{"input": "abc\nabc", "expected": "3"}, {"input": "abc\ndef", "expected": "0"}], "solution": {"approach": "2D DP: dp[i][j] = length ending at s1[i-1], s2[j-1].", "code": "def longestCommonSubstring(s1, s2):\n    m, n = len(s1), len(s2)\n    dp = [[0]*(n+1) for _ in range(m+1)]\n    max_len = 0\n    for i in range(1, m+1):\n        for j in range(1, n+1):\n            if s1[i-1] == s2[j-1]:\n                dp[i][j] = dp[i-1][j-1] + 1\n                max_len = max(max_len, dp[i][j])\n    return max_len", "time_complexity": "O(m*n)", "space_complexity": "O(m*n)"}, "hints": ["Track consecutive matches."], "topics": ["Dynamic Programming", "String"], "companies": ["Amazon"], "difficulty": "medium", "type": "coding", "role": "SDE"},

    # More Stacks
    {"striver_id": "SQ-17", "topic": "Stacks & Queues", "topic_order": 3, "problem_order": 17, "question_title": "Next Greater Element", "statement": "Find next greater element for each array element.", "examples": [{"input": "nums = [4,5,2,25]", "output": "[5,25,25,-1]"}], "constraints": ["1 <= n <= 10^4"], "visible_test_cases": [{"input": "4\n4 5 2 25", "expected": "5 25 25 -1"}], "hidden_test_cases": [{"input": "1\n1", "expected": "-1"}, {"input": "3\n3 2 1", "expected": "-1 -1 -1"}], "solution": {"approach": "Monotonic stack from right.", "code": "def nextGreaterElements(nums):\n    n = len(nums)\n    result = [-1] * n\n    stack = []\n    for i in range(n-1, -1, -1):\n        while stack and stack[-1] <= nums[i]:\n            stack.pop()\n        if stack: result[i] = stack[-1]\n        stack.append(nums[i])\n    return result", "time_complexity": "O(n)", "space_complexity": "O(n)"}, "hints": ["Use monotonic decreasing stack."], "topics": ["Stack", "Array"], "companies": ["Amazon", "Google"], "difficulty": "medium", "type": "coding", "role": "SDE"},

    # More Greedy
    {"striver_id": "GRDY-06", "topic": "Greedy", "topic_order": 7, "problem_order": 6, "question_title": "Jump Game", "statement": "Determine if you can reach the last index.", "examples": [{"input": "nums = [2,3,1,1,4]", "output": "true"}], "constraints": ["1 <= n <= 10^4"], "visible_test_cases": [{"input": "5\n2 3 1 1 4", "expected": "true"}], "hidden_test_cases": [{"input": "5\n3 2 1 0 4", "expected": "false"}, {"input": "1\n0", "expected": "true"}], "solution": {"approach": "Greedy: track farthest reachable.", "code": "def canJump(nums):\n    max_reach = 0\n    for i in range(len(nums)):\n        if i > max_reach: return False\n        max_reach = max(max_reach, i + nums[i])\n    return True", "time_complexity": "O(n)", "space_complexity": "O(1)"}, "hints": ["Track the farthest you can reach."], "topics": ["Greedy", "Array"], "companies": ["Amazon", "Google"], "difficulty": "medium", "type": "coding", "role": "SDE"},

    # More Binary Search
    {"striver_id": "BS-06", "topic": "Binary Search", "topic_order": 1, "problem_order": 30, "question_title": "Koko Eating Bananas", "statement": "Find minimum eating speed to finish all piles within h hours.", "examples": [{"input": "piles = [3,6,7,11], h = 8", "output": "4"}], "constraints": ["1 <= piles.length <= 10^4"], "visible_test_cases": [{"input": "4 8\n3 6 7 11", "expected": "4"}], "hidden_test_cases": [{"input": "1 1\n31", "expected": "31"}, {"input": "4 6\n30 11 23 4 20", "output": "23"}], "solution": {"approach": "Binary search on speed.", "code": "def minEatingSpeed(piles, h):\n    lo, hi = 1, max(piles)\n    while lo < hi:\n        mid = (lo + hi) // 2\n        hours = sum((p + mid - 1) // mid for p in piles)\n        if hours <= h: hi = mid\n        else: lo = mid + 1\n    return lo", "time_complexity": "O(n log max)", "space_complexity": "O(1)"}, "hints": ["Binary search on the answer (speed)."], "topics": ["Binary Search"], "companies": ["Amazon", "Google"], "difficulty": "medium", "type": "coding", "role": "SDE"},

    # More Strings
    {"striver_id": "STR-05", "topic": "Strings", "topic_order": 2, "problem_order": 39, "question_title": "Group Anagrams", "statement": "Group strings that are anagrams of each other.", "examples": [{"input": "strs = ['eat','tea','tan','ate','nat','bat']", "output": "[['eat','tea','ate'],['tan','nat'],['bat']]"}], "constraints": ["1 <= strs.length <= 10^4"], "visible_test_cases": [{"input": "6\neat tea tan ate nat bat", "expected": "eat tea ate\ntan nat\nbat"}], "hidden_test_cases": [{"input": "1\na", "expected": "a"}, {"input": "2\na b", "expected": "a\nb"}], "solution": {"approach": "Use sorted string as key in hash map.", "code": "from collections import defaultdict\ndef groupAnagrams(strs):\n    groups = defaultdict(list)\n    for s in strs:\n        key = ''.join(sorted(s))\n        groups[key].append(s)\n    return list(groups.values())", "time_complexity": "O(n*k log k)", "space_complexity": "O(n*k)"}, "hints": ["Sorted string is the same for anagrams."], "topics": ["String", "Hash Table"], "companies": ["Amazon", "Google"], "difficulty": "medium", "type": "coding", "role": "SDE"},

    # More Recursion
    {"striver_id": "REC-04", "topic": "Recursion", "topic_order": 3, "problem_order": 48, "question_title": "N-Queens", "statement": "Place n queens on n×n chessboard so no two attack each other.", "examples": [{"input": "n = 4", "output": "[[.Q..,...Q,Q...,.Q..],[..Q.,Q...,...Q,.Q..]]"}], "constraints": ["1 <= n <= 9"], "visible_test_cases": [{"input": "4", "expected": "2 solutions"}], "hidden_test_cases": [{"input": "1", "expected": "1 solution"}, {"input": "8", "expected": "92 solutions"}], "solution": {"approach": "Backtracking: place queens row by row.", "code": "def solveNQueens(n):\n    result = []\n    def backtrack(row, cols, diag1, diag2, board):\n        if row == n:\n            result.append([''.join(r) for r in board])\n            return\n        for col in range(n):\n            if col in cols or row-col in diag1 or row+col in diag2:\n                continue\n            board[row][col] = 'Q'\n            backtrack(row+1, cols|{col}, diag1|{row-col}, diag2|{row+col}, board)\n            board[row][col] = '.'\n    backtrack(0, set(), set(), set(), [['.']*n for _ in range(n)])\n    return result", "time_complexity": "O(n!)", "space_complexity": "O(n^2)"}, "hints": ["Track columns and diagonals using sets."], "topics": ["Recursion", "Backtracking"], "companies": ["Amazon", "Google"], "difficulty": "hard", "type": "coding", "role": "SDE"},

    # More BST
    {"striver_id": "BST-03", "topic": "BST", "topic_order": 7, "problem_order": 82, "question_title": "Construct BST from Preorder", "statement": "Construct BST from preorder traversal.", "examples": [{"input": "preorder = [8,5,1,7,10,12]", "output": "BST root"}], "constraints": ["1 <= preorder.length <= 100"], "visible_test_cases": [{"input": "6\n8 5 1 7 10 12", "expected": "valid BST"}], "hidden_test_cases": [{"input": "1\n1", "expected": "1"}, {"input": "2\n2 1", "expected": "2 1 null"}], "solution": {"approach": "Use upper bound to determine subtree.", "code": "def bstFromPreorder(preorder):\n    idx = [0]\n    def build(upper):\n        if idx[0] == len(preorder) or preorder[idx[0]] > upper:\n            return None\n        root = TreeNode(preorder[idx[0]])\n        idx[0] += 1\n        root.left = build(root.val)\n        root.right = build(upper)\n        return root\n    return build(float('inf'))", "time_complexity": "O(n)", "space_complexity": "O(n)"}, "hints": ["Use upper bound to decide when to stop."], "topics": ["BST", "Recursion"], "companies": ["Amazon"], "difficulty": "medium", "type": "coding", "role": "SDE"},

    # More Heaps
    {"striver_id": "HP-04", "topic": "Heaps", "topic_order": 5, "problem_order": 68, "question_title": "Find Median from Data Stream", "statement": "Design a data structure to add numbers and find median.", "examples": [{"input": "addNum(1), addNum(2), findMedian(), addNum(3), findMedian()", "output": "1.5, 2.0"}], "constraints": ["-10^5 <= num <= 10^5"], "visible_test_cases": [{"input": "add 1\nadd 2\nmedian\nadd 3\nmedian", "expected": "1.5\n2"}], "hidden_test_cases": [{"input": "add 1\nmedian", "expected": "1"}, {"input": "add 1\nadd 2\nadd 3\nadd 4\nmedian", "expected": "2.5"}], "solution": {"approach": "Two heaps: max-heap for lower half, min-heap for upper half.", "code": "import heapq\nclass MedianFinder:\n    def __init__(self):\n        self.lo = []  # max-heap (invert values)\n        self.hi = []  # min-heap\n    def addNum(self, num):\n        heapq.heappush(self.lo, -num)\n        heapq.heappush(self.hi, -heapq.heappop(self.lo))\n        if len(self.hi) > len(self.lo):\n            heapq.heappush(self.lo, -heapq.heappop(self.hi))\n    def findMedian(self):\n        if len(self.lo) > len(self.hi):\n            return -self.lo[0]\n        return (-self.lo[0] + self.hi[0]) / 2", "time_complexity": "O(log n) add, O(1) median", "space_complexity": "O(n)"}, "hints": ["Balance two heaps around the median."], "topics": ["Heap", "Design"], "companies": ["Amazon", "Google", "Meta"], "difficulty": "hard", "type": "coding", "role": "SDE"},

    # More Sliding Window
    {"striver_id": "SW-03", "topic": "Sliding Window", "topic_order": 5, "problem_order": 72, "question_title": "Maximum Sum Subarray of Size K", "statement": "Find maximum sum of a contiguous subarray of size k.", "examples": [{"input": "arr = [2,1,5,1,3,2], k = 3", "output": "9"}], "constraints": ["1 <= k <= n <= 10^5"], "visible_test_cases": [{"input": "6 3\n2 1 5 1 3 2", "expected": "9"}], "hidden_test_cases": [{"input": "1 1\n1", "expected": "1"}, {"input": "3 2\n1 2 3", "expected": "5"}], "solution": {"approach": "Sliding window: maintain sum of k elements.", "code": "def maxSum(arr, k):\n    window_sum = sum(arr[:k])\n    max_sum = window_sum\n    for i in range(k, len(arr)):\n        window_sum += arr[i] - arr[i-k]\n        max_sum = max(max_sum, window_sum)\n    return max_sum", "time_complexity": "O(n)", "space_complexity": "O(1)"}, "hints": ["Subtract element going out, add element coming in."], "topics": ["Sliding Window", "Array"], "companies": ["Amazon", "Microsoft"], "difficulty": "easy", "type": "coding", "role": "SDE"},

    # More Bit Manipulation
    {"striver_id": "BIT-04", "topic": "Bit Manipulation", "topic_order": 4, "problem_order": 58, "question_title": "Reverse Bits", "statement": "Reverse bits of a 32-bit unsigned integer.", "examples": [{"input": "n = 43261596 (00000010100101000001111010011100)", "output": "964176192 (00111001011110000010100101000000)"}], "constraints": ["Input is a binary string of length 32"], "visible_test_cases": [{"input": "00000010100101000001111010011100", "expected": "964176192"}], "hidden_test_cases": [{"input": "11111111111111111111111111111101", "expected": "3221225471"}], "solution": {"approach": "Bit manipulation: shift and OR.", "code": "def reverseBits(n):\n    result = 0\n    for _ in range(32):\n        result = (result << 1) | (n & 1)\n        n >>= 1\n    return result", "time_complexity": "O(1)", "space_complexity": "O(1)"}, "hints": ["Shift result left, OR with last bit of n."], "topics": ["Bit Manipulation"], "companies": ["Amazon", "Google"], "difficulty": "easy", "type": "coding", "role": "SDE"},
]
