"""
System Design Problems for Interview Preparation.
50+ problems covering scalability, architecture, and distributed systems.
"""

SYSTEM_DESIGN_PROBLEMS = [
    # ═══════════════════════════════════════════════════════════════════════════
    # CORE SYSTEM DESIGN (20 problems)
    # ═══════════════════════════════════════════════════════════════════════════
    {
        "id": "SD-001", "title": "Design a URL Shortener",
        "difficulty": "medium",
        "category": "system_design",
        "statement": "Design a URL shortening service like bit.ly that converts long URLs to short URLs and redirects back.",
        "requirements": [
            "Shorten URLs to 7-character codes",
            "Redirect short URLs to original URLs",
            "Custom aliases (optional)",
            "Analytics (click count, geography)",
            "Expiry for links (optional)",
            "High availability (99.99%)",
        ],
        "key_components": ["Load Balancer", "Web Server", "Cache (Redis)", "Database (MongoDB)", "Analytics Service"],
        "estimated_users": "100M URLs/day",
        "time_complexity": "O(1) lookup",
        "space_complexity": "O(n) storage",
        "companies": ["Amazon", "Google", "Microsoft"],
        "hints": ["Use Base62 encoding for short URLs", "Implement cache for hot URLs", "Consider database sharding by hash"],
        "solution_sketch": "1. Generate short URL using Base62 encoding of auto-increment ID or hash. 2. Store mapping in database with TTL. 3. Use Redis cache for frequent lookups. 4. Redirect via HTTP 301/302. 5. Track clicks asynchronously.",
        "video_url": "https://www.youtube.com/results?search_query=url+shortener+system+design",
    },
    {
        "id": "SD-002", "title": "Design a Chat Application",
        "difficulty": "hard",
        "category": "system_design",
        "statement": "Design a real-time chat application like WhatsApp or Slack supporting 1-on-1 and group chats.",
        "requirements": [
            "Real-time message delivery",
            "1-on-1 and group chats",
            "Message history",
            "Online/offline status",
            "Read receipts",
            "File sharing",
            "End-to-end encryption (optional)",
        ],
        "key_components": ["WebSocket Server", "Message Queue", "Database", "Notification Service", "File Storage"],
        "estimated_users": "1B messages/day",
        "time_complexity": "O(1) message delivery",
        "space_complexity": "O(messages) storage",
        "companies": ["Amazon", "Google", "Meta", "Microsoft"],
        "hints": ["Use WebSocket for real-time", "Partition messages by conversation", "Use message queue for reliability"],
        "solution_sketch": "1. WebSocket connections for real-time messaging. 2. Message queue (Kafka) for reliability and ordering. 3. Database sharded by conversation ID. 4. Push notifications via FCM/APNs. 5. File storage on S3 with CDN.",
        "video_url": "https://www.youtube.com/results?search_query=chat+application+system+design",
    },
    {
        "id": "SD-003", "title": "Design a Social Media Feed",
        "difficulty": "hard",
        "category": "system_design",
        "statement": "Design a news feed system like Facebook or Twitter's feed that shows posts from friends/followers.",
        "requirements": [
            "Post creation and deletion",
            "News feed generation (fan-out on write vs read)",
            "Like, comment, share",
            "Real-time updates",
            "Trending topics",
            "Content moderation",
        ],
        "key_components": ["Web Server", "Fan-out Service", "Cache", "Database", "Search Index", "ML Service"],
        "estimated_users": "1B users, 500M DAU",
        "time_complexity": "O(1) feed generation",
        "space_complexity": "O(followers × posts)",
        "companies": ["Meta", "Twitter", "Amazon", "Google"],
        "hints": ["Fan-out on write for celebrities, fan-out on read for regular users", "Use Redis for feed cache", "Consider edge cases like viral posts"],
        "solution_sketch": "1. Hybrid fan-out: push for <10K followers, pull for >10K. 2. Feed stored in Redis with 1-hour TTL. 3. Posts stored in Cassandra for write-heavy workload. 4. Search via Elasticsearch. 5. Trending via streaming aggregation.",
        "video_url": "https://www.youtube.com/results?search_query=news+feed+system+design",
    },
    {
        "id": "SD-004", "title": "Design a Ride-Sharing Service",
        "difficulty": "hard",
        "category": "system_design",
        "statement": "Design a ride-sharing service like Uber or Lyft with real-time matching and location tracking.",
        "requirements": [
            "Rider and driver apps",
            "Real-time location tracking",
            "Matching algorithm",
            "Pricing (surge pricing)",
            "Payment processing",
            "Trip history",
            "Rating system",
        ],
        "key_components": ["Location Service", "Matching Service", "Payment Service", "Notification Service", "Map Service"],
        "estimated_users": "10M rides/day",
        "time_complexity": "O(log n) matching",
        "space_complexity": "O(users) location data",
        "companies": ["Uber", "Amazon", "Google", "Lyft"],
        "hints": ["Use geospatial indexing for location queries", "Implement surge pricing based on supply/demand", "Consider driver-rider matching algorithms"],
        "solution_sketch": "1. Location service using geospatial indexing (QuadTree or GeoHash). 2. Matching: find nearest drivers, rank by rating/distance. 3. Dynamic pricing based on supply/demand ratio. 4. Payment via Stripe/PayPal. 5. Real-time tracking via WebSocket.",
        "video_url": "https://www.youtube.com/results?search_query=uber+system+design",
    },
    {
        "id": "SD-005", "title": "Design a Search Autocomplete",
        "difficulty": "medium",
        "category": "system_design",
        "statement": "Design a search autocomplete system like Google's search suggestions.",
        "requirements": [
            "Real-time suggestions as user types",
            "Top-K suggestions per prefix",
            "Support for millions of queries",
            "Update suggestions based on popularity",
            "Response time < 100ms",
        ],
        "key_components": ["Trie Data Structure", "Cache", "Analytics Service", "Database"],
        "estimated_users": "10B queries/day",
        "time_complexity": "O(prefix_length) lookup",
        "space_complexity": "O(total_characters) trie",
        "companies": ["Google", "Amazon", "Microsoft"],
        "hints": ["Use Trie for prefix matching", "Cache top-K results for common prefixes", "Update trie periodically from analytics"],
        "solution_sketch": "1. Trie data structure for prefix matching. 2. Each node stores top-K suggestions with frequency. 3. Cache hot prefixes in Redis. 4. Update trie hourly from click analytics. 5. Serve from edge servers for low latency.",
        "video_url": "https://www.youtube.com/results?search_query=search+autocomplete+system+design",
    },
    {
        "id": "SD-006", "title": "Design a Notification System",
        "difficulty": "medium",
        "category": "system_design",
        "statement": "Design a notification system that supports push notifications, SMS, and email.",
        "requirements": [
            "Multi-channel delivery (push, SMS, email)",
            "Priority levels (critical, normal, low)",
            "Rate limiting per user",
            "Template management",
            "Delivery tracking",
            "Retry logic for failures",
        ],
        "key_components": ["API Gateway", "Notification Service", "Message Queue", "Template Engine", "Analytics"],
        "estimated_users": "100M notifications/day",
        "time_complexity": "O(1) enqueue",
        "space_complexity": "O(pending notifications)",
        "companies": ["Amazon", "Google", "Microsoft"],
        "hints": ["Use message queue for decoupling", "Implement rate limiting per user", "Track delivery status for debugging"],
        "solution_sketch": "1. API receives notification request. 2. Validate and enqueue to message queue. 3. Worker processes queue, selects channel (push/SMS/email). 4. Send via provider APIs (FCM, Twilio, SendGrid). 5. Track delivery status asynchronously.",
        "video_url": "https://www.youtube.com/results?search_query=notification+system+design",
    },
    {
        "id": "SD-007", "title": "Design a Rate Limiter",
        "difficulty": "medium",
        "category": "system_design",
        "statement": "Design a rate limiting system to control request frequency per user/IP.",
        "requirements": [
            "Support multiple rate limiting algorithms",
            "Distributed across multiple servers",
            "Configurable limits per endpoint/user",
            "Return meaningful error messages",
            "Low latency (< 1ms overhead)",
        ],
        "key_components": ["Redis", "Rate Limiter Middleware", "Configuration Store"],
        "estimated_users": "1B requests/day",
        "time_complexity": "O(1) per request",
        "space_complexity": "O(unique_keys) in Redis",
        "companies": ["Amazon", "Google", "Microsoft"],
        "hints": ["Implement Token Bucket, Sliding Window, and Fixed Window algorithms", "Use Redis for distributed counting", "Consider race conditions in distributed systems"],
        "solution_sketch": "1. Token Bucket: refill tokens at fixed rate, consume on request. 2. Sliding Window: track requests in time window. 3. Use Redis INCR + EXPIRE for distributed counting. 4. Return 429 with Retry-After header when limited.",
        "video_url": "https://www.youtube.com/results?search_query=rate+limiter+system+design",
    },
    {
        "id": "SD-008", "title": "Design a Content Delivery Network",
        "difficulty": "hard",
        "category": "system_design",
        "statement": "Design a CDN that caches and serves static content from edge locations worldwide.",
        "requirements": [
            "Global edge locations",
            "Cache invalidation",
            "Origin server fallback",
            "DDoS protection",
            "SSL/TLS termination",
            "Analytics and monitoring",
        ],
        "key_components": ["Edge Servers", "Origin Server", "Cache Layer", "DNS", "Monitoring"],
        "estimated_users": "10B requests/day",
        "time_complexity": "O(1) cache hit",
        "space_complexity": "O(content) per edge",
        "companies": ["Amazon", "Cloudflare", "Google"],
        "hints": ["Use Anycast DNS for routing", "Implement cache invalidation via versioning", "Consider edge computing for dynamic content"],
        "solution_sketch": "1. Anycast DNS routes users to nearest edge. 2. Edge servers cache content with TTL. 3. Cache miss → fetch from origin. 4. Cache invalidation via versioned URLs or purge API. 5. DDoS protection via rate limiting and IP filtering.",
        "video_url": "https://www.youtube.com/results?search_query=cdn+system+design",
    },
    {
        "id": "SD-009", "title": "Design a Distributed Cache",
        "difficulty": "hard",
        "category": "system_design",
        "statement": "Design a distributed caching system like Redis Cluster or Memcached.",
        "requirements": [
            "Distributed across multiple nodes",
            "Consistent hashing for data placement",
            "Replication for fault tolerance",
            "Eviction policies (LRU, LFU)",
            "Pub/Sub for cache invalidation",
        ],
        "key_components": ["Cache Nodes", "Consistent Hash Ring", "Replication Manager", "Client Library"],
        "estimated_users": "1M ops/sec",
        "time_complexity": "O(1) get/set",
        "space_complexity": "O(memory_per_node × nodes)",
        "companies": ["Amazon", "Google", "Microsoft"],
        "hints": ["Use consistent hashing for data distribution", "Implement replication factor of 3", "Consider cache warming strategies"],
        "solution_sketch": "1. Consistent hash ring distributes keys across nodes. 2. Each key has N replicas on adjacent nodes. 3. Client library handles routing and failover. 4. Eviction: LRU with configurable TTL. 5. Pub/Sub for cluster-wide cache invalidation.",
        "video_url": "https://www.youtube.com/results?search_query=distributed+cache+system+design",
    },
    {
        "id": "SD-010", "title": "Design a Task Scheduler",
        "difficulty": "medium",
        "category": "system_design",
        "statement": "Design a distributed task scheduler like cron or Celery that can handle millions of scheduled tasks.",
        "requirements": [
            "Schedule tasks at specific times",
            "Recurring tasks (cron expressions)",
            "Distributed execution",
            "Task retry and failure handling",
            "Monitoring and alerting",
        ],
        "key_components": ["Scheduler Service", "Task Queue", "Worker Nodes", "Database", "Monitoring"],
        "estimated_users": "10M scheduled tasks",
        "time_complexity": "O(log n) scheduling",
        "space_complexity": "O(tasks) storage",
        "companies": ["Amazon", "Google"],
        "hints": ["Use a priority queue for scheduling", "Partition tasks by time range", "Implement dead letter queue for failed tasks"],
        "solution_sketch": "1. Scheduler stores tasks with next_run_time. 2. Polling loop checks for due tasks every second. 3. Tasks dispatched to worker queue (Redis/RabbitMQ). 4. Workers execute tasks with retry logic. 5. Dead letter queue for permanently failed tasks.",
        "video_url": "https://www.youtube.com/results?search_query=task+scheduler+system+design",
    },
    {
        "id": "SD-011", "title": "Design a Payment System",
        "difficulty": "hard",
        "category": "system_design",
        "statement": "Design a payment processing system like Stripe or PayPal.",
        "requirements": [
            "Payment processing (credit cards, bank transfers)",
            "Idempotency (no double charges)",
            "Refund handling",
            "PCI compliance",
            "Fraud detection",
            "Multi-currency support",
        ],
        "key_components": ["Payment Gateway", "Fraud Detection", "Ledger Service", "Notification Service"],
        "estimated_users": "1M transactions/day",
        "time_complexity": "O(1) payment processing",
        "space_complexity": "O(transactions) ledger",
        "companies": ["Amazon", "Google", "Stripe"],
        "hints": ["Use idempotency keys to prevent double charges", "Implement two-phase commit for consistency", "Consider circuit breaker for external payment APIs"],
        "solution_sketch": "1. Idempotency key prevents duplicate charges. 2. Two-phase commit for ledger consistency. 3. Fraud detection via ML models on transaction patterns. 4. PCI compliance via tokenization (never store card numbers). 5. Webhook notifications for payment status.",
        "video_url": "https://www.youtube.com/results?search_query=payment+system+design",
    },
    {
        "id": "SD-012", "title": "Design a Key-Value Store",
        "difficulty": "medium",
        "category": "system_design",
        "statement": "Design a distributed key-value store like DynamoDB or Redis.",
        "requirements": [
            "Put(key, value) and Get(key) operations",
            "Support for billions of keys",
            "Replication for fault tolerance",
            "Consistency options (eventual vs strong)",
            "Partitioning across nodes",
        ],
        "key_components": ["Client Library", "Coordinator Node", "Data Nodes", "Consistent Hash Ring"],
        "estimated_users": "1M ops/sec",
        "time_complexity": "O(1) get/put",
        "space_complexity": "O(data_size)",
        "companies": ["Amazon", "Google", "Microsoft"],
        "hints": ["Use consistent hashing for partitioning", "Implement vector clocks for conflict resolution", "Consider quorum reads/writes"],
        "solution_sketch": "1. Consistent hashing distributes data across nodes. 2. Replication factor of 3 for fault tolerance. 3. Vector clocks for versioning and conflict detection. 4. Quorum: W + R > N for consistency. 5. Merkle trees for anti-entropy repair.",
        "video_url": "https://www.youtube.com/results?search_query=key+value+store+system+design",
    },
    {
        "id": "SD-013", "title": "Design a Video Streaming Platform",
        "difficulty": "hard",
        "category": "system_design",
        "statement": "Design a video streaming platform like YouTube or Netflix.",
        "requirements": [
            "Video upload and transcoding",
            "Adaptive bitrate streaming",
            "Content recommendation",
            "Search and discovery",
            "Comments and ratings",
            "Content moderation",
        ],
        "key_components": ["Upload Service", "Transcoding Pipeline", "CDN", "Recommendation Engine", "Search Index"],
        "estimated_users": "1B videos/day",
        "time_complexity": "O(1) video lookup",
        "space_complexity": "O(videos × resolution)",
        "companies": ["Google", "Netflix", "Amazon"],
        "hints": ["Use pre-signed URLs for uploads", "Transcode to multiple resolutions", "Implement adaptive bitrate streaming (HLS/DASH)"],
        "solution_sketch": "1. Pre-signed S3 URLs for direct uploads. 2. Transcoding pipeline (FFmpeg) creates multiple resolutions. 3. CDN serves videos from edge locations. 4. HLS/DASH for adaptive streaming. 5. Recommendation via collaborative filtering.",
        "video_url": "https://www.youtube.com/results?search_query=youtube+system+design",
    },
    {
        "id": "SD-014", "title": "Design a Distributed File System",
        "difficulty": "hard",
        "category": "system_design",
        "statement": "Design a distributed file system like Google File System or HDFS.",
        "requirements": [
            "Store petabytes of data",
            "Fault tolerance (replication)",
            "High throughput for large files",
            "Consistency guarantees",
            "Client access via API",
        ],
        "key_components": ["Master Node", "Chunk Servers", "Client Library", "Metadata Store"],
        "estimated_users": "1PB data, 10K clients",
        "time_complexity": "O(1) metadata lookup",
        "space_complexity": "O(data × replication_factor)",
        "companies": ["Google", "Amazon", "Microsoft"],
        "hints": ["Split files into chunks (64MB)", "Replicate each chunk 3 times", "Master node manages metadata only"],
        "solution_sketch": "1. Files split into 64MB chunks. 2. Each chunk replicated 3 times across different servers. 3. Master node stores metadata (file→chunk mapping). 4. Client reads metadata from master, then reads data directly from chunk servers. 5. Heartbeat mechanism for failure detection.",
        "video_url": "https://www.youtube.com/results?search_query=distributed+file+system+design",
    },
    {
        "id": "SD-015", "title": "Design a Search Engine",
        "difficulty": "hard",
        "category": "system_design",
        "statement": "Design a web search engine like Google.",
        "requirements": [
            "Crawl and index web pages",
            "Rank results by relevance",
            "Handle billions of queries",
            "Autocomplete suggestions",
            "Spell correction",
        ],
        "key_components": ["Web Crawler", "Indexer", "Ranking Algorithm", "Query Processor", "Cache"],
        "estimated_users": "10B queries/day",
        "time_complexity": "O(1) cached, O(log n) uncached",
        "space_complexity": "O(index_size)",
        "companies": ["Google", "Microsoft", "Amazon"],
        "hints": ["Use inverted index for fast text search", "Implement PageRank for ranking", "Consider crawl scheduling to avoid overloading sites"],
        "solution_sketch": "1. Web crawler fetches pages, extracts links. 2. Indexer builds inverted index (word→document mapping). 3. Ranking via PageRank + BM25. 4. Query processor parses query, retrieves from index, ranks results. 5. Cache top queries for fast response.",
        "video_url": "https://www.youtube.com/results?search_query=search+engine+system+design",
    },
    {
        "id": "SD-016", "title": "Design a Metrics Collection System",
        "difficulty": "medium",
        "category": "system_design",
        "statement": "Design a system to collect, store, and visualize application metrics like Prometheus or Datadog.",
        "requirements": [
            "Collect metrics from thousands of services",
            "Store time-series data efficiently",
            "Query metrics by time range",
            "Alert on anomalies",
            "Dashboard visualization",
        ],
        "key_components": ["Agent", "Time-Series DB", "Query Engine", "Alert Manager", "Dashboard"],
        "estimated_users": "10M metrics/second",
        "time_complexity": "O(1) write, O(log n) query",
        "space_complexity": "O(data × retention_days)",
        "companies": ["Amazon", "Google", "Datadog"],
        "hints": ["Use time-series database (InfluxDB, TimescaleDB)", "Implement downsampling for old data", "Consider push vs pull model for collection"],
        "solution_sketch": "1. Agents collect metrics from services (push model). 2. Time-series DB stores data efficiently with compression. 3. Query engine supports range queries and aggregations. 4. Alert manager checks rules and sends notifications. 5. Dashboard renders charts from query results.",
        "video_url": "https://www.youtube.com/results?search_query=metrics+monitoring+system+design",
    },
    {
        "id": "SD-017", "title": "Design a Logging System",
        "difficulty": "medium",
        "category": "system_design",
        "statement": "Design a centralized logging system like ELK Stack or Splunk.",
        "requirements": [
            "Collect logs from thousands of services",
            "Full-text search across logs",
            "Real-time log streaming",
            "Log retention and archival",
            "Access control for sensitive logs",
        ],
        "key_components": ["Log Agent", "Log Collector", "Search Index", "Storage", "Dashboard"],
        "estimated_users": "1TB logs/day",
        "time_complexity": "O(1) write, O(log n) search",
        "space_complexity": "O(logs × retention_days)",
        "companies": ["Amazon", "Google", "Elastic"],
        "hints": ["Use structured logging (JSON)", "Implement log rotation and compression", "Consider sampling for high-volume logs"],
        "solution_sketch": "1. Agents collect logs from services. 2. Log collector aggregates and forwards to storage. 3. Elasticsearch indexes logs for full-text search. 4. Kibana provides dashboard and visualization. 5. ILM (Index Lifecycle Management) for retention.",
        "video_url": "https://www.youtube.com/results?search_query=logging+system+design",
    },
    {
        "id": "SD-018", "title": "Design an E-commerce Platform",
        "difficulty": "hard",
        "category": "system_design",
        "statement": "Design an e-commerce platform like Amazon.",
        "requirements": [
            "Product catalog with search",
            "Shopping cart and checkout",
            "Payment processing",
            "Order management",
            "Inventory management",
            "Recommendation engine",
        ],
        "key_components": ["Product Service", "Cart Service", "Order Service", "Payment Service", "Inventory Service", "Search Service"],
        "estimated_users": "100M products, 1M orders/day",
        "time_complexity": "O(1) product lookup",
        "space_complexity": "O(products + orders)",
        "companies": ["Amazon", "Google", "Microsoft"],
        "hints": ["Use event-driven architecture for order processing", "Implement inventory reservation during checkout", "Consider CQRS for read-heavy product catalog"],
        "solution_sketch": "1. Product catalog in Elasticsearch for search. 2. Cart in Redis with TTL. 3. Checkout: reserve inventory → process payment → confirm order. 4. Order events trigger fulfillment pipeline. 5. Recommendations via collaborative filtering on purchase history.",
        "video_url": "https://www.youtube.com/results?search_query=ecommerce+system+design",
    },
    {
        "id": "SD-019", "title": "Design a Ticket Booking System",
        "difficulty": "medium",
        "category": "system_design",
        "statement": "Design a ticket booking system like BookMyShow or Ticketmaster.",
        "requirements": [
            "Browse events and shows",
            "Seat selection",
            "Payment processing",
            "Handle flash sales (high concurrency)",
            "Prevent double booking",
        ],
        "key_components": ["Event Service", "Seat Map Service", "Booking Service", "Payment Service", "Queue Service"],
        "estimated_users": "10K concurrent users during flash sales",
        "time_complexity": "O(1) seat reservation",
        "space_complexity": "O(seats × shows)",
        "companies": ["Amazon", "Microsoft"],
        "hints": ["Use optimistic locking for seat reservation", "Implement virtual waiting room for flash sales", "Consider seat lock timeout for abandoned bookings"],
        "solution_sketch": "1. Seat map stored with status (available/reserved/sold). 2. Reserve seat with 10-minute TTL. 3. Flash sale: virtual waiting room, random queue position. 4. Payment confirms reservation → marks seat as sold. 5. Timeout releases reserved seats.",
        "video_url": "https://www.youtube.com/results?search_query=ticket+booking+system+design",
    },
    {
        "id": "SD-020", "title": "Design a Real-Time Leaderboard",
        "difficulty": "medium",
        "category": "system_design",
        "statement": "Design a real-time leaderboard for a gaming platform showing player rankings.",
        "requirements": [
            "Update scores in real-time",
            "Show top-K players instantly",
            "Handle millions of players",
            "Persist scores for history",
            "Range queries (players around your rank)",
        ],
        "key_components": ["Score Service", "Redis Sorted Set", "WebSocket", "Database"],
        "estimated_users": "10M players",
        "time_complexity": "O(log n) score update, O(log n + K) top-K",
        "space_complexity": "O(players) in Redis",
        "companies": ["Amazon", "Google", "Microsoft"],
        "hints": ["Use Redis Sorted Set (ZADD, ZRANGE)", "Implement WebSocket for real-time updates", "Consider sharding for very large player bases"],
        "solution_sketch": "1. Redis Sorted Set stores player_id → score. 2. ZADD updates score in O(log n). 3. ZRANGE gets top-K in O(log n + K). 4. WebSocket broadcasts score changes. 5. Periodic snapshot to database for history.",
        "video_url": "https://www.youtube.com/results?search_query=leaderboard+system+design",
    },
]
