// AUTO-GENERATED by scripts/gen-flat-api.mjs — flat aliases so both
// `api.namespace.method()` and legacy `api.method()` call styles work.
import { adminContentApi } from "./adminContent.ts";
import { adaptiveApi } from "./adaptive.ts";
import { enhancedApi } from "./enhanced.ts";
import { studentApi } from "./student.ts";
import { interviewApi } from "./interview.ts";
import { codingApi } from "./coding.ts";

export const flatApi = {
  get: (...args: Parameters<typeof adminContentApi.get>) =>
    adminContentApi.get.apply(adminContentApi, args),
  getRecommendations: (
    ...args: Parameters<typeof adaptiveApi.getRecommendations>
  ) => adaptiveApi.getRecommendations.apply(adaptiveApi, args),
  getSemanticATS: (...args: Parameters<typeof enhancedApi.getSemanticATS>) =>
    enhancedApi.getSemanticATS.apply(enhancedApi, args),
  getDailyDrill: (...args: Parameters<typeof studentApi.getDailyDrill>) =>
    studentApi.getDailyDrill.apply(studentApi, args),
  submitDrill: (...args: Parameters<typeof studentApi.submitDrill>) =>
    studentApi.submitDrill.apply(studentApi, args),
  startInterviewV2: (
    ...args: Parameters<typeof interviewApi.startInterviewV2>
  ) => interviewApi.startInterviewV2.apply(interviewApi, args),
  getTopics: (...args: Parameters<typeof codingApi.getTopics>) =>
    codingApi.getTopics.apply(codingApi, args),
};
