// AUTO-GENERATED by scripts/gen-flat-api.mjs — flat aliases so both
// `api.namespace.method()` and legacy `api.method()` call styles work.
import { adminContentApi } from "./adminContent.ts";
import { adaptiveApi } from "./adaptive.ts";
import { enhancedApi } from "./enhanced.ts";
import { studentApi } from "./student.ts";
import { interviewApi } from "./interview.ts";
import { codingApi } from "./coding.ts";

export const flatApi = {
  get: (...args) => adminContentApi.get.apply(adminContentApi, args),
  getRecommendations: (...args) => adaptiveApi.getRecommendations.apply(adaptiveApi, args),
  getSemanticATS: (...args) => enhancedApi.getSemanticATS.apply(enhancedApi, args),
  getDailyDrill: (...args) => studentApi.getDailyDrill.apply(studentApi, args),
  submitDrill: (...args) => studentApi.submitDrill.apply(studentApi, args),
  startInterviewV2: (...args) => interviewApi.startInterviewV2.apply(interviewApi, args),
  getTopics: (...args) => codingApi.getTopics.apply(codingApi, args),
};
